### ISSUE TITLE
e2e - Stop downloading the ISO and use the containerized one for tests

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental#1002]
This is about stop downloading the elemental ISO in tests and start using a containerized one provided from the channel as a ManagedOSVersion. This is also about using the SeedImage procedure to create an ISO instead of manually injecting the registartion.yaml into an ISO.

Currently the displayName (text appearing on the ISOs dropdown menu in UI) of images build in `Dev` or `Staging` include the `(unstable)` suffix.

**Comment by juadk** [comment]
Done in the UI tests ✅
