### ISSUE TITLE
Initial release of CAPI provider and agent

### ISSUE THREAD

**Issue by anmazzotti** [rancher/elemental#1031]
Since we have a working prototype, it would be best to release it properly to allow users to experiment with it more easily.

This means:
- Release the image of the operator
- Release the x86_64 and aarch64 builds of the agent
- Release manifests files and templates for inclusion in `clusterctl`
- Initial release can be done on GitHub for simplicity

**Comment by anmazzotti** [comment]
Linking parent epic #968

**Comment by kkaempf** [comment]
With yesterday's announcement, I'd guess this can be closed ?!

**Comment by anmazzotti** [comment]
First release published: https://github.com/rancher-sandbox/cluster-api-provider-elemental/releases/tag/v0.0.1

There is a pending issue with the k3s provider that is addressed by: https://github.com/cluster-api-provider-k3s/cluster-api-k3s/pull/60

A new release to apply the change to our k3s manifests will happen as soon the k3s provider is updated.
