### ISSUE TITLE
Unable to bootstrap cluster with kubernetes bersion >= 1.22

### ISSUE THREAD

**Issue by RegisHubelia** [rancher/elemental#107]
Same as https://github.com/rancher/rancherd/issues/22
Replacing the rancherd binary with [this one](https://github.com/bk201/rancherd/releases/tag/v0.0.1-alpha13-bk201.1) that includes this  [this change](https://github.com/bk201/rancherd/commit/72d10cb842a4a4f616c842426c5cb6a699fbabb3) works fine.  Of course not ideal as it wouldn't work with < 1.22.

**Comment by kkaempf** [comment]
closing for now as we're switching from `rancherd` to `system-agent`
