### ISSUE TITLE
Add default ntp configuration

### ISSUE THREAD

**Issue by RegisHubelia** [rancher/elemental#109]
Currently, when the system boots after install, ntp is not configured.

I added the following in the config file and it works fine:

write_files:
- container: ntp
  path: /etc/ntp.conf
  permissions: "0644"
  owner: root
  content: |
    server 1.pool.ntp.org iburst
    server 0.pool.ntp.org iburst

    restrict default nomodify nopeer noquery limited kod
    restrict 127.0.0.1
    restrict [::1]
runcmd:
- timedatectl set-ntp true

But I would suggest to have a default configuration as time sync problem sometime causes underlying issues.

**Comment by kkaempf** [comment]
This is fixed in recent images.
