### ISSUE TITLE
Submit required packages into SLE Micro 6.0

### ISSUE THREAD

**Issue by anmazzotti** [rancher/elemental#1101]
We need to submit all elemental packages that might be required in an elemental host to the relevant code stream.

Tracker of jira ticket SMO-303

- [x] elemental-toolkit
- [ ] elemental-agent
- [x] check if xorriso or any other library is needed

**Comment by davidcassany** [comment]
Submissions done, awaiting for approval. Some little packaging details had to be adapted to pass IBS bot checkers...
