### ISSUE TITLE
Elemental CAPI OS Upgrades

### ISSUE THREAD

**Issue by anmazzotti** [rancher/elemental#1103]
This issue is about Elemental OS upgrades.

How are users intended to upgrade the base Elemental image on active nodes? 
Can they use Rancher's [system-upgrade-controller](https://github.com/rancher/system-upgrade-controller)? Can we facilitate it? 

Should the CAPI provider also define a way/API to trigger OS upgrades without the need of an additional component?

**Comment by kkaempf** [comment]
Why is this issue in "needs review" ?

**Comment by anmazzotti** [comment]
Good one. I put the actual PR on review instead, it will close this issue
