### ISSUE TITLE
Bail out if device field in cloud-config is empty

### ISSUE THREAD

**Issue by mudler** [rancher/elemental#111]
During automated installation, we should bail out immediately if the device is empty, to avoid confusing the user on what's going on and actually helping during debugging/setup.

We could even print-out a small syntax example within the error.

**Comment by mudler** [comment]
This is now related to changes at https://github.com/rancher-sandbox/ros-installer as it got split from the os2 codebase

**Comment by mjura** [comment]
Example output when there is empty device option in config file
```
./ros-installer -automatic -config-file=cloud-test 
Running automatic installation, option -y will be enforced
FATA[0000] Target disk was not provided, please add device option to config file (e.g. device: /dev/sdb)
```
