### ISSUE TITLE
Drop "console=ttyS0" from kernel cmdline (for x86_64)

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental#1115]
After https://github.com/harvester/harvester/issues/4586 we now have a second issue (bsc#1217762) reported with a slow boot.

Harvester solved it by removing the serial console. bsc#1217762 show this in `dmesg`
~~~
[    0.081403] printk: console [tty1] enabled
[   21.553007] printk: console [ttyS0] enabled
~~~

We should probably drop the serial console for x86_64 (but keep it for aarch64 as it's pretty useful for Raspberry 😉 )

**Comment by davidcassany** [comment]
Done in https://github.com/rancher/elemental/pull/1117

**Comment by kkaempf** [comment]
It also got dropped on `aarch64` (which wasn't intended) - reopening

**Comment by kkaempf** [comment]
Hmm, rpi*raw images in `Dev` have `console=ttyS0` 🤷
