### ISSUE TITLE
[SURE-7283] Wrong partition path when specifying /dev/disk/by-path/...

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental#1140]
## See also SURE-7283

I used `/dev/disk/by-path/platform-fe340000.mmc` as the install device to point to the SD card on Raspberry.
This fails with
~~~
could not find partition device '/dev/disk/by-path/platform-fe340000.mmc' for partition 1
~~~

Partition 1 appears as
~~~
/dev/disk/by-path/platform-fe340000.mmc-part1
~~~

Things get tricky, the path for partition 1 is always different 🤦🏻
* /dev/sda -> /dev/sda1
* /dev/mmcblk0 -> mmcblk0p1
* /dev/disk/by-path/platform-fe340000.mmc -> /dev/disk/by-path/platform-fe340000.mmc-part1

**Comment by mbologna** [comment]
Found on raspberry PI, but applicable to all devices - inconsistent naming for devices
