### ISSUE TITLE
rancheros-operator-chart.tgz missing in image 0.1.0

### ISSUE THREAD

**Issue by matclab** [rancher/elemental#116]
It looks like the file is copied as `/usr/share/rancher/os2` and indeed the culprint seems to be  [Dockerfile#L61](https://github.com/rancher-sandbox/os2/blob/master/Dockerfile#L61) if the os2 dir does not exists beforehand.

```
file /usr/share/rancher/os2
/usr/share/rancher/os2: gzip compressed data, extra field, has comment
```
```
zcat /usr/share/rancher/os2 | head
rancheros-operator/Chart.yaml0000644000000000000000000000074314227743072015022 0ustar0000000000000000annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/experimental: "true"
  catalog.cattle.io/namespace: cattle-rancheros-operator-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/provides-gvr: managedoses.rancheros.cattle.io/v1
  catalog.cattle.io/release-name: rancheros-operator
apiVersion: v2
appVersion: v0.1.0
description: RancherOS Operator
```

**Comment by kkaempf** [comment]
Please use rancheros-operator from https://github.com/rancher-sandbox/rancheros-operator
(or use the rpm package from the [build service](https://build.opensuse.org/package/show/home:kwk:elemental/rancheros-operator) if you're running on (open)SUSE)

**Comment by Itxaka** [comment]
Not valid anymore, operator is now at github.com/rancher/elemental-operator
