### ISSUE TITLE
Keep track of OS versions deployed on nodes

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental#1192]
**Describe the solution you'd like:**
[A clear and concise description of what you want to happen.]
MachineInventory should keep track of which OS version (+ patch level) is deployed on a node.

This is important for OS management to schedule updates accordingly.

The UI should provide a list overview of nodes and their respective OS versions. It should be possible to sort-by and filter-by OS version.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Having OS image information (repository, tag, image id, architecture) should also be useful.

**Environment:**

- Elemental release version (use `cat /etc/os-release`):
- Rancher version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:

**Comment by davidcassany** [comment]
To me this sounds like something that could be done from the elemental-register as we do for the nodes IP addresses by setting some annotations. Unless I miss something it should be simple to implement something like that, we have all the pieces available we just need to include and additional field when registering and getting the OS version from /etc/os-release should be pretty straight forward elemental-register is already running continuously in the nodes.

**Comment by Martin-Weiss** [comment]
How often does the register process run? Inventory data (ip address / OS version etc. will change over time).

**Comment by davidcassany** [comment]
> How often does the register process run? Inventory data (ip address / OS version etc. will change over time).

On every boot and once booted it runs periodically just to update annotations every 30min.

**Comment by Martin-Weiss** [comment]
Great - thanks - then the information might be up to date.. 

Can we configure this 30min interval? It could be a challenge in disconnected scenarios and it could be a challenge in large scale environments as well (i.e. >10k machines)...

**Comment by kkaempf** [comment]
That should be added to `System Data` like rancher/elemental-operator#593 🤔

**Comment by davidcassany** [comment]
> That should be added to `System Data` like [rancher/elemental-operator#593](https://github.com/rancher/elemental-operator/pull/593) 🤔

Probably could work, but it feels weird using the OS version as a selection criteria for the nodes as this won't stay static over the node lifecycle.

**Comment by fgiudici** [comment]
> Great - thanks - then the information might be up to date..
> 
> Can we configure this 30min interval? It could be a challenge in disconnected scenarios and it could be a challenge in large scale environments as well (i.e. >10k machines)...

Hey @Martin-Weiss ,
fair request IMO. Not anyway something I would consider high prio at the moment.
 Opened a tracking issue for that: https://github.com/rancher/elemental-operator/issues/641 .
