### ISSUE TITLE
Generated .changes are useless

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental#1230]
Looking at the generated [elemental.changes](https://build.opensuse.org/package/view_file/isv:Rancher:Elemental:Dev/elemental/_service:tar_scm:elemental.changes?expand=1) in `Dev` these are pretty useless.

The expectation:
* .changes should cover package/software related information
* targeted at consumers of the package
* should be incremental

The actual content
* non-incremental
* contains `ci` related entries
* doesn't properly track version number updates

**Comment by frelon** [comment]
@kkaempf Is it possible to tweak the change-log generation? I'm not finding much except 

```
<param name="changesgenerate">enable</param>
<param name="changes">enable</param>
```

**Comment by frelon** [comment]
Documenting here that we will do manual release-notes, waiting to close this until we have disabled automatic change-generation.

**Comment by kkaempf** [comment]
As git log messages and rpm changelogs have fundamentally different use cases and target groups, lets disable automatic changelog generation.

**Comment by frelon** [comment]
@kkaempf do you want to disable changelog generation in https://build.opensuse.org/request/show/1145420 or should I put up a new request?

**Comment by kkaempf** [comment]
SR#1145420 in OBS is just a brute-force .changes cleanup, dropping all "ci" entries. 

We should probably close this SR and do a properly hand-crafted, release-notes-style .changes instead.

**Comment by davidcassany** [comment]
For now changes generation are disabled we should craft some meaningful changes for each release. Before submitting to IBS we should check and craft the changes log file for `elemental` package.

**Comment by kkaempf** [comment]
`_service` in [OBS Dev](https://build.opensuse.org/package/show/isv:Rancher:Elemental:Dev/elemental) still has `changesgenerate` enabled.
Reopening.

**Comment by davidcassany** [comment]
https://build.opensuse.org/request/show/1184233

**Comment by kkaempf** [comment]
fixed in OBS
