### ISSUE TITLE
Missing btrfs tools in example (and release?) images

### ISSUE THREAD

**Issue by anmazzotti** [rancher/elemental#1233]
**What steps did you take and what happened:**
Using the latest dev version of the `elemental-toolkit` on a brand new installation, btrfs is used by default, but the installation fails since it can't find `mkfs.btrfs`. 

The `btrfsprogs` and also `snapper` packages should always be included. 

To be considered the `btrfsmaintenance` tool for kernel 6.7 issues: https://lore.kernel.org/all/CAL3q7H5UaYcAYHijBO+QTnnpruVQXvdirg05_X94KRKrKnXDZw@mail.gmail.com/T/
This one does not seem to be required for example on Leap: 15.5 based images.

**Comment by davidcassany** [comment]
> Using the latest dev version of the `elemental-toolkit` on a brand new installation, btrfs is used by default, but the installation fails since it can't find `mkfs.btrfs`.

Elemental-toolkit rpm includes hard requirements to btrfsprogs and snapper, hence any elemental-toolkit installation from a repository already includes these. `btrfsmaintenance` though remains as an open question. I do believe we should include it, but it is definitely not a dependency of elemental-tookit. IMHO it should be part of our image definitions.

**Comment by kkaempf** [comment]
I'll ask 'upstream' 😉

**Comment by kkaempf** [comment]
> I'll ask 'upstream' 😉

And, yes, `btrfsmaintenance` must be installed on systems using btrfs.
