### ISSUE TITLE
Maintenance release for 5.5

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental#1256]
We need maintenance release for SLE Micro for Rancher 5.5 to include an elemental-toolkit binary with up to date former libraries. Also to align with harverster.
We also need to make an elemental-operator v1.4.x release to provide a fix for rancher/elemental-operator#629.
This will also be chance to prepare 5.5 project to be ready for continuous rebuilds (GA builds are build in snapshots, not continuous rebuilds) and also to stress polishing rough edges within the current 5.5 release for which the RPM repo structure needs to be fixed.

- [x] rancher/elemental#1335
- [x] rancher/elemental#1336
- [x] rancher/elemental#1356
- [x] Test OBS builds
- [x] Test maintenance incident
- [x] Release binaries and release notes

**Comment by kkaempf** [comment]
We will _not_ backport fixes but bump Elemental to 1.5 across operating systems.

**Comment by davidcassany** [comment]
Closing, release is out

marketplace release is already tracked in another issue rancher/elemental-operator#739
