### ISSUE TITLE
Cannot create an ISO image

### ISSUE THREAD

**Issue by plmercereau** [rancher/elemental#1296]
**What steps did you take and what happened:**

I followed the exact instructions ([Elemental the visual way](https://elemental.docs.rancher.com/quickstart-ui)) to install Elemental from Rancher Manager 2.8.2.

1. install Rancher with Helm following the [official instructions](https://ranchermanager.docs.rancher.com/getting-started/quick-start-guides/deploy-rancher-manager/helm-cli)
2. Install [Elemental the visual way](https://elemental.docs.rancher.com/quickstart-ui)
3. Create a Registration Endpoint

However, after I created a registration endpoint, I cannot create an ISO image: the dropdown list remains empty:

<img width="643" alt="image" src="https://github.com/rancher/elemental-toolkit/assets/24897252/9a3d0b29-ac63-4670-9b2d-6a56407ecdfe">

When clicking on the `OS version` dropdown, no option is available: "sorry, no matching options."

**What did you expect to happen:**

To make Elemental work following the quickstart instructions.

**Anything else you would like to add:**
I could not find anything unusual, except this line in the `elemental-operator` pod:

```
E0317 15:57:46.063912       1 controller.go:317] controller/machineregistration "msg"="Reconciler error" "error"="[failed to patch machine registration object: Operation cannot be fulfilled on machineregistrations.elemental.cattle.io \"test\": the object has been modified; please apply your changes to the latest version and try again, failed to patch status for machine registration object: Operation cannot be fulfilled on machineregistrations.elemental.cattle.io \"test\": the object has been modified; please apply your changes to the latest version and try again]" "name"="test" "namespace"="fleet-default" "reconciler group"="elemental.cattle.io" "reconciler kind"="MachineRegistration"
```

I started twice from scratch from an empty cluster, with the same result.

**Environment:**

- Elemental release version (use `cat /etc/os-release`):
- Rancher version: 2.8.2
- Kubernetes version (use `kubectl version`): v1.27.9+k3s1
- Cloud provider or hardware configuration: Single node. Linux 6.1.79 NixOS x86_64

**Comment by juadk** [comment]
Hello @plmercereau , thanks for the issue!

May I ask what you got when you installed the elemental operator, please?
I'm talking about this:
![image](https://github.com/rancher/elemental/assets/6025636/34a444a7-9015-4c71-a061-980ed4de4da8)
Did you write something in the two boxes or did you think it will be used as the default?

It's a known bug where default values are not used, you have to type them.

The bug is fixed in the new elemental operator chart but the one in the Rancher Marketplace is quiet old, a new one will arrive very soon with rancher 2.8.3.

**Comment by plmercereau** [comment]
thanks for pointing me to the right direction, it works!

Out of curiosity, how could I upgrade the operator to a newer version while waiting for Rancher 2.8.3?

**Comment by kkaempf** [comment]
The [elemental operator](http://elemental.docs.rancher.com/elementaloperatorchart-reference) documentation shows how to update via `helm`.

**Comment by plmercereau** [comment]
Of course 🤦 thanks!

**Comment by juadk** [comment]
> thanks for pointing me to the right direction, it works!
> 
> Out of curiosity, how could I upgrade the operator to a newer version while waiting for Rancher 2.8.3?

You're welcome! Let's close the issue then.
