### ISSUE TITLE
Prepare maintenance update for elemental and elemental-toolkit

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental#1336]
* Make sure in maintenance project we have the latest v1.1.x toolkit version
* Make sure in #1258 fix is in v2.0.x branch of elemental repository and tag a new patch version (just tag no release yet)
* Update all OS image sources and elemental package source in maintenance project
* Update channel images with all already released images.

**Comment by frelon** [comment]
- [x] Make sure in maintenance project we have the latest v1.1.x toolkit version
- [x] Make sure in
https://github.com/rancher/elemental/pull/1258 fix is in v2.0.x branch of elemental repository and tag a new patch version (just tag no release yet)
- [x] Update all OS image sources and elemental package source in maintenance project
- [x] Update channel images with all already released images.
