### ISSUE TITLE
[Question] Confused about the State of rancher os 2

### ISSUE THREAD

**Issue by batthebee** [rancher/elemental#135]
I am currently a little confused. 
I would like to use rancher os v2 and find your ideas really great. 
So I have looked at the os2 repository. There have been no commits for a few months and it is marked as "experimental". I almost broke off here. It was only by chance that I came across this repo. It looks stable, but the link for the docs leads to nirvana. 

What is the current status for rancher os2? Can it already be used productively? And are the current docs in the docs folder here?

Thank you!

**Comment by mudler** [comment]
Hi @batthebee ! 

We are currently in the process of moving out the repositories from the sandbox project and promoting them to the rancher org, so docs and links might be broken at the current timing. Meanwhile the project was renamed from os2 to Elemental, so I understand there is confusion in there, but It will take few days for docs/things to get in shape.

**Comment by batthebee** [comment]
Great, Thank you!
