### ISSUE TITLE
Merge rancher-sandbox/elemental-installer into rancher/elemental-operator

### ISSUE THREAD

**Issue by mudler** [rancher/elemental#136]
(this should be an issue under elemental-operator)

elemental-installer still lives on rancher-sandbox. The code should be merged with elemental-operator (as agreed last week) and the elemental-installer repo removed.

Once it's done, please ping @kkaempf so the respective build service projects can be adapted.

**Comment by kkaempf** [comment]
Moved to rancher/elemental-operator#4
