### ISSUE TITLE
[SELinux]: SLE 6.x deployment in Enforcing mode via Elemental

### ISSUE THREAD

**Issue by fgiudici** [rancher/elemental#1360]
Deploy successfully Elemental OS image with SELinux in Enforcing mode.
Suggested items:
- set SELinux to Enforcing by default (default is Permissive)
- perform SELinux relabeling in initramfs stage (see [example here](https://github.com/rancher/elemental-toolkit/blob/main/pkg/features/embedded/cloud-config-defaults/system/oem/10_selinux.yaml))
- double check all labels are as expected (`restorecon -Rvn /`)

**Comment by fgiudici** [comment]
related: https://github.com/rancher/elemental-toolkit/issues/1492

**Comment by kkaempf** [comment]
tracked in toolkit, dropping it here
