### ISSUE TITLE
elemental-installer to honor nginx's packet size limits

### ISSUE THREAD

**Issue by mudler** [rancher/elemental#137]
(this should be an issue on elemental-operator)

"we figured out that issue with the Bad Websocket on the ROS installer. NGINX ingress by default needs flags appended to allow for headers larger than 8k. The header we were sending (containing MachineInventory data) was ~17k. This could be a bit of an issue since it requires modifications to the default configuration of nginx ingress which both RKE1 and 2 default to."

See also: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#large-client-header-buffers

**Comment by mudler** [comment]
Depends on https://github.com/rancher/elemental/issues/136

**Comment by kkaempf** [comment]
Moved to rancher/elemental-operator#5
