### ISSUE TITLE
ci: add/modify manual upgrade worklflow to allow stable to maintenance test

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental#1373]
This is to add automation for `maintenance` tests. The regular deployment tests are already cover by the existing manual workflow, only the upgrade one needs to be adapted.

**Comment by juadk** [comment]
operator maintenance path: `oci://registry.opensuse.org/isv/rancher/elemental/maintenance/5.5/charts/rancher`

**Comment by juadk** [comment]
Well I tried to run a test using `maintenance/5.5` as input for `upgrade_os_channel` and the operator upgrade works:
https://github.com/rancher/elemental/actions/runs/10176993775
