### ISSUE TITLE
Chart sign-off for rancher 2.8.4

### ISSUE THREAD

**Issue by juadk** [rancher/elemental#1387]
Test the `1.4.3` elemental operator chart in the marketplace with the new automation.

Wait on https://github.com/rancher/charts/pull/3824

**Comment by juadk** [comment]
https://github.com/rancher/charts/pull/3824 got merged, I think we can start testing it!



![Image](https://github.com/rancher/elemental/assets/6025636/e2f32060-5fd2-4e6b-9ef7-6562bcecf973)

**Comment by kkaempf** [comment]
considered done
