### ISSUE TITLE
HowTo install elemental

### ISSUE THREAD

**Issue by batthebee** [rancher/elemental#139]
I would really like to try out elemental, but I have trouble with the docs. It is currently not clear to me what I have to do to use elemental on an existing machine. I'm sure this is also due to your current restructuring. Should I wait a little longer or can someone give me some step-by-step instructions? 
When do you think everything will be updated and consistent?

**Comment by kkaempf** [comment]
Florian, please give us another week or two to have everything settled.

If you're only interested to deploy a k8s cluster (and not creating your own, derived image), there's a [getting started](https://github.com/rancher-sandbox/rancher-node-image/blob/main/getting-started.md) documentation based on the older stack.

**Comment by kkaempf** [comment]
This is fixed. See https://rancher.github.io/elemental/
