### ISSUE TITLE
ci/cli: check how reset test is done

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental#1390]
We still have sporadic failures with the reset test, for example: https://github.com/rancher/elemental/actions/runs/8874711731/job/24362711213.

It could be an issue in the test itself, so better to verify this before doing anything else.

**Comment by juadk** [comment]
Let's try to increase the timeout when we check that the deleted machine inventory is removed from the machine inventory list => https://github.com/rancher/elemental/pull/1429
PR is merged, we keep the issue in observation mode.

**Comment by juadk** [comment]
The sporadic issue is still there even with the timeout set to 10 minutes...
https://github.com/rancher/elemental/actions/runs/9201621270/job/25310901356
