### ISSUE TITLE
Change the name of the ISO files to be more consistent with versioning

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental#1399]
The current naming set the Elemental version *BEFORE* the `Build` (for example `sl-micro-6.0-baremetal.x86_64-2.1.1-Build3.3.iso`), which mask the Elemental version in the openQA test. It could also be an issue when we will have the same build number but with different Elemental version, as openQA will see a "duplicate" `Build3.3` entry for example.

It could be better to use something like this: `sl-micro-6.0-baremetal.x86_64-Build2.1.1-3.3.iso`.

**Comment by kkaempf** [comment]
6.0 is the base OS, 2.1.1 is the Elemental version number, 3.3 is the (build service assigned) build number.
Not much we can do here 🤷🏻
