### ISSUE TITLE
Create OpenQA tests to gate Micro5.5 rebuild releases

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental#1414]
We should be capable to gate Micro55 rebuild releases based on some openQA tests applied to the derived ISO. The challenge here is gating the release of container OS image based on the success of the related ISO test.

**Comment by ldevulder** [comment]
@davidcassany can you give me the path were to download the ISOs to test?

**Comment by davidcassany** [comment]
So the images would be the ones from  `SUSE:SLE-15-SP5:Update:Products:Elemental55:Update:CR:ToTest/images` and they are named as: `sle-micro.x86_64-2.0.4-Build5.5.35.iso`.

**Comment by davidcassany** [comment]
We need to investigate further how to integrated the desired flow with the containers release bot.

* Can it be used to trigger our openQA ISO tests? (the tests are lauched in containers job group)
* Can we group multiple containers, so they are not individual assets? ISOs are a derived containers of OS container, if the ISO tests pass the OS container is also verified. Probably this could be rewritten as: auto-release all images in project only if **all** tests of **all** containers are passing.
* Do we know something about the bot cadence? Is it running daily/weekly? I don't think we want anything less than weekly, because it is likely to be the case there are some manual or semi-automated steps required to for each release (e.g channel update).

**Comment by ldevulder** [comment]
Test code added in openQA. The configuration to use the code is the remaining task for openQA, but should be done by QAM team as far as I understood.

**Comment by ldevulder** [comment]
I created a MR to try to fix the Elemental55 pipeline: https://gitlab.suse.de/qac/container-release-bot/-/merge_requests/292.

**Comment by ldevulder** [comment]
MR has been merged, let's see if it works better. Moved back to `blocked` state until we have new images to test.
PR created to add support for SLMicro5.5 based images: https://github.com/rancher/elemental/pull/1539.

**Comment by ldevulder** [comment]
Another MR to fix the ISO tests and the KVM/RT image tests: https://gitlab.suse.de/qac/container-release-bot/-/merge_requests/295.

**Comment by ldevulder** [comment]
Remaining issues have been fixed! Release looks OK now, issue can be closed!

Here an example for `sle-micro-iso/5.5`:
![Image](https://github.com/user-attachments/assets/ae266a8b-3791-4cba-9868-46c772f375c2)
