### ISSUE TITLE
Add qemu-guest-agent to micro-kvm-os image flavour

### ISSUE THREAD

**Issue by robertwbl** [rancher/elemental#1423]
**Describe the solution you'd like:**
[A clear and concise description of what you want to happen.]
Request to add the qemu-guest-agent package to Micro for Rancher (or perhaps more suitably the micro-kvm-os image flavour coming with Micro 6) so we don't have to build custom images that include this package for use in a virtualised environment.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
My specific use case is that I’m using elemental VMs as nodes in a K3S cluster on a Harvester host, and would then like to use the Harvester cloud provider loadbalancer functionality to loadbalance services in the cluster. One of the requirements for this though is that the qemu-guest-agent is installed on the nodes so that Harvester can obtain IPs ([https://docs.harvesterhci.io/v1.2/networking/loadbalancer/](https://docs.harvesterhci.io/v1.2/networking/loadbalancer/)). Given elemental’s position within Rancher’s OS management and Rancher-Harvester integration, it feels like this would be a good package to include.

There may be other issues with this particular use case, for example I believe the Harvester loadbalancer also requires the VMs to be in the same namespace as the guest elemental cluster, which I haven't been able to successfully create in any other namespace than fleet-default, but I don't think this makes including the qemu-guest-agent package any less appropriate.

**Environment:**

- Elemental release version (use `cat /etc/os-release`): v2.0.2
- Rancher version: v2.8.4
- Kubernetes version (use `kubectl version`): v1.28.9+k3s1
- Cloud provider or hardware configuration: Harvester

**Comment by kkaempf** [comment]
This is done for Micro 6.
See line 18 of https://build.opensuse.org/projects/isv:Rancher:Elemental:Staging/packages/SL-Micro-kvm-container/files/Dockerfile?expand=1
