### ISSUE TITLE
Reshape elemental-channel a new OS based schema

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental#1438]
**Describe the solution you'd like:**
We would like to distribute each OS stream with it's own channel regularly update and append new images on the channel (based on rebuilds or based on maintenance updates)

**Anything else you would like to add:**
This should also help to make obvious the OS each Elemental Linux image is based on.  

**Environment:**

- Elemental release version (use `cat /etc/os-release`):
- Rancher version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:

**Comment by anmazzotti** [comment]
Repo name could be:
- `registry.suse.com/rancher/elemental-channel/sl-micro:6.0`
- `registry.suse.com/rancher/elemental-channel/sl-micro:6.0-flavor`

**Comment by kkaempf** [comment]
see rancher/elemental-operator#727
