### ISSUE TITLE
Virtual Machine cannot boot with elemental-teal v1.2.3 iso

### ISSUE THREAD

**Issue by GrantMelvin** [rancher/elemental#1498]
**What steps did you take and what happened:**
When creating a registration endpoint with the cloud configuration below, we are not able to boot a virtual machine with the iso built from the UI.

![image](https://github.com/user-attachments/assets/e426e2bb-9b39-4859-bb8b-fd664b67cd69)

After this iso is built, we are trying to use it on a Harvester virtual machine:

![image](https://github.com/user-attachments/assets/90ef530e-a0ad-4119-82e6-b9e0aa6583fd)

The virtual machine starts, and it cannot find the boot device when we use the elemental ISO. We have also tried to boot it as "disk" instead of "cd-rom" and it leads to the same issue.

![image](https://github.com/user-attachments/assets/94a11339-d997-47b8-8b9c-c09744ab32eb)

**What did you expect to happen:**
The virtual machine to successfully start and use the elemental operating system.

**Environment:**

- Elemental release version (use `cat /etc/os-release`): 103.3.0+up1.5.3
- Rancher version: 2.8.3
- Kubernetes version (use `kubectl version`): v1.29.2
- Cloud provider or hardware configuration: Azure

**Comment by kkaempf** [comment]
You did configure the Harvester VM to boot via UEFI, right ? 🤔

**Comment by kkaempf** [comment]
http://elemental.docs.rancher.com/quickstart-cli/#prerequisites

**Comment by GrantMelvin** [comment]
That fixed it... thank you so much!
