### ISSUE TITLE
[PED-8705] Create build-xx-disk-image 'packages'

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental#1516]
We already have "build-*-iso-image" packages to create ISO images for the various flavors. See [build-baremetal-iso-image](https://build.opensuse.org/package/show/isv:Rancher:Elemental:Staging/build-baremetal-iso-image) for the baremetal flavor.

PED-8705 now asks for respective 'raw disk' images to simplify OS installation on all supported architectures.

This should be largely similar to the existing build-*-iso-image packages but run "build-disk" instead of "build-iso" when calling `elemental`.

Once done, we can probably drop [elemental-post-build-generate-rpi-image](https://build.opensuse.org/package/show/isv:Rancher:Elemental:Staging/elemental-post-build-generate-rpi-image) as it's no longer needed.

**Comment by kkaempf** [comment]
Raw images can be built from the UI: https://elemental.docs.rancher.com/next/seedimage-reference#iso-and-raw-images

**Comment by kkaempf** [comment]
Example call to [build-disk](https://github.com/rancher/elemental-operator/blob/main/controllers/seedimage_controller.go#L655)

**Comment by anmazzotti** [comment]
@kkaempf FYI the `elemental build-disk` command documentation has just been published: https://rancher.github.io/elemental-toolkit/docs/creating-derivatives/build_disk/

Not sure if that's enough (together with new elemental-operator features) to close this issue.

**Comment by davidcassany** [comment]
I realized #1574 is not enough as it misses the hook to copy firmware to the expected location. From the UI perspective that hook is present within the SeedImage builder containers. I am working on a patch to make it available as part of the image itself.

**Comment by davidcassany** [comment]
images now being build in Dev and it will become available in Staging for 6.1 when ever we prepare so, just verified the image on an RPi. It takes about 10min to boot, expand and reboot. From a build perspective this task is achieved, however it is still unclear to me what shall we do with these images from a release and delivery perspective. Moved to blocked for further discussion.
