### ISSUE TITLE
Package nmstatectl 

### ISSUE THREAD

**Issue by anmazzotti** [rancher/elemental#1519]
**Describe the solution you'd like:**

In order to use `nmstate` syntax to apply declarative networking on Elemental hosts, we do need `nmstatectl` to be properly packaged, so that it can be installed on Elemental OS images. 

This should be available on SLE, but also on openSUSE for community variants of images.

https://github.com/nmstate/nmstate

**Comment by kkaempf** [comment]
https://build.opensuse.org/package/show/home:lin_ma:ovirt-host/nmstate seems useful

**Comment by anmazzotti** [comment]
Closing this issue as `nm-configurator` has been made default by https://github.com/rancher/elemental-operator/pull/819
