### ISSUE TITLE
e2e: test uefi secure boot

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental#153]
Test UEFI boot with Secure Boot enable as soon as the issues we have are fixed.

**Comment by kkaempf** [comment]
Waiting for a fixed `grub2` package in SLE Micro :-/

**Comment by Itxaka** [comment]
Not blocked anymore :D

**Comment by ldevulder** [comment]
Planned for next sprint!

**Comment by ldevulder** [comment]
Fixed with PR #520.
