### ISSUE TITLE
New Elemental install does not boot with shim.efi

### ISSUE THREAD

**Issue by dthaha** [rancher/elemental#1545]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Upon booting a fresh install of Elemental (SLE Micro ISO x86_64 v2.0.4) on a Dell OptiPlex 7070 Ultra, system displays following error:

```shell
Invalid image
Failed to read header: Unsupported
Failed to load image: Unsupported
start_image() returned Unsupported
```

System does not continue booting. BIOS update does not resolve the issue.

**What did you expect to happen:**
System to boot to SLE Micro shell.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

This is the same issue as [harvester/harvester #3996](https://github.com/harvester/harvester/issues/3996) (since Elemental base image and Harvester are both SLE Micro). I used [this comment](https://github.com/harvester/harvester/issues/3996#issuecomment-2051871780) to workaround the issue by creating a new UEFI boot entry to boot using `grub.efi`.

This is on a Dell OptiPlex 7070 Ultra. Seems to be limited to consumer Dell hardware.

**Environment:**

- Elemental release version (use `cat /etc/os-release`): SLE Micro 5.5
- Rancher version: v2.9.1
- Kubernetes version (use `kubectl version`): v1.30.4+k3s1
- Cloud provider or hardware configuration: Dell OptiPlex 7070 Ultra, BIOS 1.25.0

**Comment by frelon** [comment]
Hi @dthaha!

Interesting, have you tried booting a regular install of SLE Micro 5.5? It could narrow down where the actual error is. We could also try with a newer version elemental that is based on SL Micro 6.0.. 

Let me know your findings!

**Comment by dthaha** [comment]
Thanks for looking at this, @frelon. I'll try both SLE Micro 5.5 and Elemental SL Micro 6.0 to validate.

**Comment by kkaempf** [comment]
Closing due to lack of response.

@dthaha feel free to reopen once you provide the requested information.
