### ISSUE TITLE
[SMO-454] Include nm-configurator in Elemental images

### ISSUE THREAD

**Issue by anmazzotti** [rancher/elemental#1559]
[nmc](https://github.com/suse-edge/nm-configurator) should be available in Elemental shipped images by default for [declarative networking](https://elemental.docs.rancher.com/next/networking) support.

- [ ] Clarify maintenance and support
- [ ] Submit to elemental-obs
- [ ] Submit to SL Micro 6.1

**Comment by kkaempf** [comment]
Is `nmc` already packaged somewhere ?

**Comment by anmazzotti** [comment]
Yes I can see it here: https://build.opensuse.org/package/show/isv:SUSE:Edge:EdgeImageBuilder/nm-configurator

**Comment by kkaempf** [comment]
Great, then it needs to be added to https://github.com/rancher/elemental-obs/tree/dev plus a respective "zypper in" call in [SL-Micro-Base-Container](https://github.com/rancher/elemental-obs/tree/dev/SL-Micro-base-container) 😉

**Comment by mbologna** [comment]
The package is not part of Micro and we don't need to ship it to Micro.
The package is maintained in Edge and we don't need to maintain it further.
