### ISSUE TITLE
Use "elemental-installer" instead of "ros-installer"

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental#160]
`grep -r ros-installer .` still shows many occurences of `ros-installer`
These should all be `elemental-installer` instead.

**Comment by Itxaka** [comment]
Fixed in part on https://github.com/rancher/elemental/pull/269
There is still some ros-installer calls on the smoke/install tests but those are not working for now and are being worked on by @ldevulder 

I would close this as this is a non-issue anymore

**Comment by kkaempf** [comment]
considered done
