### ISSUE TITLE
elemental-iso-build (replacing ros-image-build ?)

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental#165]
`ros-image-build` is outdated and should be removed.

There's [elemental-iso-build](https://github.com/rancher-sandbox/rancher-node-image/blob/main/elemental-iso-build) which should replace it.
This build script should
- use registry.opensuse.org/isv/rancher/elemental/teal52/15.3/rancher/elemental-node-image/5.2:last as the base
- use registry.opensuse.org/isv/rancher/elemental/teal52/15.3/rancher/elemental-builder-image as "tools"
- only focus on ISO creation (qcow etc can be added later, but we don't need it right now)
- be simple to run (like `elemental-iso-build <registration>.yaml` instead of the current `ros-image-build <image> iso <registration>.yaml`

Current problems with [elemental-iso-build](https://github.com/rancher-sandbox/rancher-node-image/blob/main/elemental-iso-build)
- calls `elemental build-iso` wrongly (can't find rootfs)
- is still based on `ros-installer`, probably still carries some unneeded "cruft"

**Comment by Itxaka** [comment]
This is done, but we have a divergence here.

The make proper_iso will build a proper iso based of our published images on registry.opensuse.org

BUT the rest of the repo is using the convoluted ros_image_build to build the rest of the stuff (qcow, box, iso, containers) which is wrong. 

Those are the images that get published when cutting a release...

IMHO, we should drop the full script and start from scratch, so we get in control of our CI adn release chain. I mean, the tests are currently running ros-installer to test PRs...where is ros-installer coming from? no idea...

Simple Dockerfile to build the elemental containers, simple packer template to build the qcow/box and call it a day. Have the same build workflow as in toolkit where we build container -> iso -> qcow/box from THAT iso -> run end2end tests with that generated box.

Should not take very long, especially if we drop all the uneeded stuff like aws and so on that cna come later. We really need to reign in the CI/Release pipelines in here.

**Comment by kkaempf** [comment]
> IMHO, we should drop the full script and start from scratch, so we get in control of our CI adn release chain. I mean, the tests are currently running ros-installer to test PRs...where is ros-installer coming from? no idea...

:+1: - please create a new issue (and pick it if you want :wink:)
