### ISSUE TITLE
There's still ros-operator-install and ros-populate-node-labels in framework/files/usr/sbin

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental#166]
Are these still needed ?

**Comment by Itxaka** [comment]
for the e2e testing they are still being used. Either we break the e2e testing by dropping them or we rework the e2e testing to use...elemental-installer? Which means we need to setup a rancher cluster in order to test elemental.

**Comment by kkaempf** [comment]
From discussions on the daily
- drop ros-operator-install
- rename ros-populate-node-labels to elemental-populate-node-labels
