### ISSUE TITLE
Remove cOS from GRUB entries

### ISSUE THREAD

**Issue by juadk** [rancher/elemental#176]
We will have to thing about removing cOS from GRUB entries:
![image](https://user-images.githubusercontent.com/6025636/179512465-94e35364-fbd9-4b50-a190-055b617ab319.png)

**Comment by Itxaka** [comment]
A bit weird because I thought obs build is using the framework files?? So this should show up as "RancherOS" instead of cOS ? @kkaempf are we using the framework files in teh OBS build of elemental? The spec file seems to confirm that...

**Comment by kkaempf** [comment]
`.spec` files don't lie 😉

**Comment by Itxaka** [comment]
mmmhf. `GRUB_MENU_ENTRY` is actually picked from the /etc/os-release :facepalm:

**Comment by Itxaka** [comment]
nope, not usre why we also got that lol, its picked from one of the 4 grub config files... :man_facepalming:

**Comment by Itxaka** [comment]
damn, setting custom names is broken.

This will need https://github.com/rancher/elemental-cli/pull/299 and then a bump to the elemental-cli both on cos-toolkit and obs 

cc @kkaempf

**Comment by kkaempf** [comment]
OBS ✅
