### ISSUE TITLE
Allow for change of node-name prior to install

### ISSUE THREAD

**Issue by agracey** [rancher/elemental#18]
It would be nice if we could specify the node name via the MachineInventory object when joining the cluster.

This doesn't even need to be hostname since both k3s and rke2 have the `--node-name` flag when installing!

**Comment by mudler** [comment]
There is already a node name in MachineInventory  under `.spec.config.nodeName`, or am I missing something?:

https://github.com/rancher-sandbox/os2/blob/master/pkg/apis/rancheros.cattle.io/v1/machine.go#L55

**Comment by kkaempf** [comment]
Setting `nodeName` has no influence on the actual hostname of the node :-(

**Comment by mudler** [comment]
> Setting `nodeName` has no influence on the actual hostname of the node :-(

the `hostname` can be set via either `cloud-init` during manual install, or when specifying cloud-init configuration during machine registration

**Comment by kkaempf** [comment]
`cloud-init` might not be practical, since it's part of `machineRegistration` and embedded in the installer ISO. It's not per-machine.

**Comment by mudler** [comment]
> `cloud-init` might not be practical, since it's part of `machineRegistration` and embedded in the installer ISO. It's not per-machine.

I'm not sure if there are implications in changing hostname afterwards, especially if the cluster is already bootstrapped.

In a mass-install scenario I don't see how set hostname specifically for each machine is going to help, but rather having an automated way to randomize hostname with a template. 

Our cloud-init syntax supports this, as the `hostname` field is templated, so it should be possible to set hostname like this:

```yaml
hostname: "fooprefix-{{.Values.UUID}}"
```

```yaml
hostname: "fooprefix-{{.Values.MachineID}}"
```

There is also supports for [sprig](http://masterminds.github.io/sprig/). So `env`, `uuidv4` and others can be used too, and thus you can do things like (not tested!):

```yaml
hostname: "fooprefix-{{ trunc 5 .Values.UUID}}"
```

**Comment by mudler** [comment]
> I tried `spec.config.nodeName` today and it didn't have any visible effect :-(

see here: https://rancher.github.io/os2/configuration/

the nodeName is actually the kubernetes node name, there is no relation with the `hostname`. I think that should set up on first install/bootstrap and does not apply aftewards

**Comment by kkaempf** [comment]
this is resolved
