### ISSUE TITLE
Generic install disk images

### ISSUE THREAD

**Issue by agracey** [rancher/elemental#19]
Once we can bootstrap from a container image, it might make things easier for demos and one-offs to have a generic disk image to boot from. Then you can run `cos-installer` with the image and config specified in flags.

**Comment by mudler** [comment]
What do you mean with 'disk-image'? At the moment we do have qcow images as part of releases: https://github.com/rancher-sandbox/os2/releases/download/v0.1.0-alpha16/rancheros-v0.1.0-alpha16-amd64.qcow.gz and container images are on quay.io, all tagged: https://quay.io/repository/costoolkit/os2?tab=tags

**Comment by agracey** [comment]
In my case, specifically iso.

Right now, I have to build the initial OCI image and registration data into the iso then bootstrap with it (or maybe that's just the steps that I've read). It would be nice if there was a generic install image that booted without any prep work and let me specify all of the config at install time after booting.

The benefits being: 
- No prep work prior to first boot
- Smaller bootstrap image to load with iPXE

Eventually, we'd like to be able to host everything needed to boot via iPXE with Rancher so genericizing* the pieces needed could be helpful. It also lowers the skill and tooling needed to get a demo going. 

One question that might make all of this moot: can you specify cloud-init at boot time via iPXE?



* Huh, that's actually a word?

**Comment by mudler** [comment]
There is no requirement on build an own ISO, but it's of supported to use customized ones too. The ISOs from releases can be used as well, e.g.: https://github.com/rancher-sandbox/os2/releases/tag/v0.1.0-alpha16

For IPXE a cloud init config can be specified, it just needs some tweaking from the one generated from the releases: https://github.com/rancher-sandbox/os2/releases/download/v0.1.0-alpha16/rancheros-v0.1.0-alpha16-amd64.ipxe

```
#!ipxe
set arch amd64
set version v0.1.0-alpha16
set url https://github.com/rancher-sandbox/os2/releases/download/${version}
set kernel rancheros-${version}-${arch}-kernel
set initrd rancheros-${version}-${arch}-initrd
set rootfs rancheros-${version}-${arch}.squashfs
set iso    rancheros-${version}-${arch}.iso
# set config http://example.com/machine-config
# set cmdline extra.values=1
kernel ${url}/${kernel} initrd=${initrd} ip=dhcp rd.cos.disable root=live:${url}/${rootfs} rancheros.install.automatic=true rancheros.install.iso_url=${url}/${iso} rancheros.install.config_url=${config} console=tty1 console=ttyS0 ${cmdline}
initrd ${url}/${initrd}
boot
```

`set config` here is specifically for cloud-init inputs

**Comment by kkaempf** [comment]
> It would be nice if there was a generic install image that booted without any prep work and let me specify all of the config at install time after booting.

This sounds contrary to the 'edge' target we're currently pursuing.
How would you log in to such a system to pass
- the Rancher URL
- the cloud-init URL

> Eventually, we'd like to be able to host everything needed to boot via iPXE with Rancher

That would require Rancher and all nodes to be on the same network. 


Please describe your use-case and intended workflow. Maybe there is a different solution.

**Comment by mudler** [comment]
This is already a scenario which is supported. 

The generic ISO which is currently released as part of elemental releases can be used for bootstrapping another system. You can either specify a container image to be deployed, and on the same way you can supply a custom cloud-config via either network or by a partition or with yet an additional ISO, which could actually be also an USB stick.

I'm closing this unless there are other action items on this, which currently I fail to see.
