### ISSUE TITLE
Restore release pipeline

### ISSUE THREAD

**Issue by Itxaka** [rancher/elemental#193]
Currently the release pipeline is disabled (well it just echoes a "build") as we were reworking the artifacts.

 - Re-enable the pipeline build_all target and release jobs to release the created artifacts on new tag

**Comment by Itxaka** [comment]
No idea what we would release as part of elemental...maybe the docker image built? A text file containing the links tot he docker images released?

Note that the official release comes from OBS, not from github so maybe we dont release stuff, only tag points in time?

**Comment by davidcassany** [comment]
IMHO a release of Elemental Teal should encompass essentially three elements:

* Elemental Teal OS image version X. This is based on or it includes:
  * Elemental-toolkit version Y
  * Elemental-operator version Z
  
IMHO the release page of this repo should not include any binary, just links to the registry fro OS Image version X and links to the appropriate releases of elemental-toolkit and elemental-operator.

The challenge here is how sync all this and make it automated, specially given the fact this includes OBS builds... 🤔 

@rancher/elemental what you think? does it makes sense.

**Comment by fgiudici** [comment]
The discussion is moved on #361
