### ISSUE TITLE
Build arm64 images

### ISSUE THREAD

**Issue by Itxaka** [rancher/elemental#197]
We need:

 - https://github.com/rancher/elemental-operator/issues/75
 - https://github.com/rancher/elemental-cli/issues/292

We have:
 - Artifacts repo for teal arm64
 - elemental support for building arm64 isos
 - sle-micro arm64 (`skopeo inspect docker://registry.suse.com/suse/sle-micro-rancher/5.2:latest --override-arch arm64 | jq '.Digest'`)

**Comment by Itxaka** [comment]
Note that downstream OBS already builds for arm64

**Comment by kkaempf** [comment]
this is considered done
