### ISSUE TITLE
UI - Add Cypress tests in the CI

### ISSUE THREAD

**Issue by juadk** [rancher/elemental#199]
Right now, to run the Cypress tests, I have to build a rancher dev environment on my laptop with the followings steps:

- Deploy k3s with latest Rancher stack
- Clone the developer's branch and build the latest dashboard from it
```
git clone -b os-elemental-resources git@github.com:aalves08/dashboard.git
cd dashboard/
 
# Remove elemental from EXCLUDE_PKG in nuxt.config.js
sed -ie "s/, elemental//g" nuxt.config.js
 
yarn install
API=https://<YOUR_RANCHER>  yarn dev
```
- Install the latest elemental-operator
```
helm upgrade --create-namespace -n cattle-elemental-system \
  --install elemental-operator oci://registry.opensuse.org/isv/rancher/elemental/charts/elemental/elemental-operator
``` 

Waiting the code to be merged in the rancher/dashboard (main), I think there are several ways to automate the process:

1. deploy k3s, install rancher, clone and build the dev dashboard => will take time to build
2. k3s + create a docker image with the dev dashboard => will be faster than 1
3. k3d, it should be possible but we have to keep in mind that at some point, we will probably have to add other nodes in the CI, it should work anyway but we will have to play with the network.
4. 
For Epinio, I was able to create a docker image with the latest UI, let's see if it can be done for Elemental.

**Comment by juadk** [comment]
I wonder if it's possible to generate a rancher image with custom Alexandre's branch. He doesn't know, he told me to reach out Richard but he is on vacation (back next Monday). Meanwhile, I will continue my research.

**Comment by juadk** [comment]
Richard's answer:

> I wouldn't advise building custom Rancher Manager images with custom embedded UIs (rather complicated process). However you could make use of the same process we were using to test the embedded epinio. That would require Alex pushing his changes to a branch on rancher/dashboard ending in -dev which would create a build and publish it. The URL of those published bits can then be applied to the rancher setting ui-dashboard-index (there's another setting that may be required depending on if the rancher manager version ended in -head)

@aalves08  will try it next week.

**Comment by juadk** [comment]
Waiting this one https://github.com/rancher/dashboard/pull/6494

**Comment by aalves08** [comment]
@juadk please disregard PR 6494. https://github.com/rancher/dashboard/pull/6624 is now the reference as is merged.

Sorry for the time taken to get this done, but 2.6.7 was really a handful. 🙏

**Comment by juadk** [comment]
@aalves08 Thanks for it!, no worries because I was on vacations.
I should be able to test it next week.

**Comment by juadk** [comment]
Well. first test this morning and it works like a charm!
![image](https://user-images.githubusercontent.com/6025636/185868626-19b0b3f3-5823-4320-bcfd-84987abcccaf.png)

I use:
```
 --set "extraEnv[0].name=CATTLE_UI_DASHBOARD_INDEX" \
 --set "extraEnv[0].value=https://releases.rancher.com/dashboard/elemental-dev/index.html" \
 --set "extraEnv[1].name=CATTLE_UI_OFFLINE_PREFERRED" \
 --set "extraEnv[1].value=Remote" \
```
