### ISSUE TITLE
Installation iso doesn't load resolv.conf from DHCP on boot

### ISSUE THREAD

**Issue by agracey** [rancher/elemental#223]
For some reason, the new node image doesn't create the /etc/resolv.conf when I boot the installation iso. I can ping out but can't call home because the name resolution fails.

It seems like even if I add a nameserver myself, the registration fails.

![image](https://user-images.githubusercontent.com/442274/181650496-75935aad-e08d-496e-b71a-98bead069d17.png)

**Comment by Itxaka** [comment]
elemental runs after network is enabled so that log is much older than when you added the nameserver. You can retry by running `elemental run-stage network` after adding the dns

I think @kkaempf also hit that today.

ISO source? Iso build date/version?

**Comment by agracey** [comment]
I used the elemental-iso-build against the obs built image.

**Comment by agracey** [comment]
It does seem like if I edit the resolv.conf fast enough it just works so yeah, the follow on error isn't real. It's just the lack of dns resolution

**Comment by kkaempf** [comment]
I also see this in KVM/libvirtd, where `wicked` doesn't populate `/etc/resolv.conf` 🤔

**Comment by kkaempf** [comment]
Installation itself passes for me, just cluster creation fails with an empty `resolv.conf`

**Comment by Itxaka** [comment]
This should already be fixed both on install and upgrade :D

**Comment by Itxaka** [comment]
https://github.com/rancher/elemental/issues/247
