### ISSUE TITLE
Document how to add kernel params 

### ISSUE THREAD

**Issue by agracey** [rancher/elemental#224]
It would be nice to have it documented how to change the kernel params for a system both before installation (via MachineRegistraion) as well on an existing system.

**Comment by agracey** [comment]
Editing on a running system is less important as any kernel params should be known in advanced but mistakes happen so it would be nice to not require re-imaging

**Comment by Itxaka** [comment]
I think this is covered by https://rancher.github.io/elemental-toolkit/docs/customizing/configure_grub/ and https://rancher.github.io/elemental-toolkit/docs/customizing/runtime_persistent_changes/

Before installation (The iso boot params) I dont think its possible unless you create your own derivative as we ship a default bootargs.cfg that contains the default kernel params from elemental-toolkit.

**Comment by kkaempf** [comment]
Not sure it the `elemental-toolkit` is the best place for it. The current `node-image` doesn't use `elemental-toolkit` at all. 🤔 

Does the "elemental" documentation link to the "elemental-toolkit" docs ?

**Comment by Itxaka** [comment]
Doesnt use any scripts from cos-toolkit? Where does the inmutability comes from? Where does the grub stuff comes from? Its all from the toolkit, and you can get the persistence enabled for root by setting the params provided in those docs.

Not that I dont agree with this, we dont have a proper way of passing extra cloud-configs or other args properly currently. But this card is about docs more than implementation. Implementation wise it probably requires some changes to how we consume, but we can currently do what is asked by following the docs.

See how c3os does it via cloud-init: https://github.com/c3os-io/c3os/blob/master/overlay/files/system/oem/21_grub.yaml

**Comment by kkaempf** [comment]
Closing as of https://github.com/rancher/elemental/issues/224#issuecomment-1200901060
Follow up: rancher/elemental-cli#297
