### ISSUE TITLE
interactive ros-installer does not allow setting root password

### ISSUE THREAD

**Issue by radioflyer28** [rancher/elemental#228]
Running ros-installer interactively doesn't prompt to set a root password and results in an install with an unknown root password. I was expecting it to be `ros` for `root`, like it is when booted from the ISO, but it is not.
https://rancher.github.io/elemental/installation/#interactive

**Comment by radioflyer28** [comment]
Found answer in old RancherOS repo...
https://github.com/rancher/os/issues/2842#issuecomment-513696833

Turns out there's no root password and must be set in the cloud-config at installation. And/or an ssh-key can be added too.
https://rancher.github.io/elemental/configuration/

**Comment by Itxaka** [comment]
unfortunately ros-installer has been deprecated. The new way of installing elemental is by using github.com/rancher/elemental-operator in conjunction with rancher

**Comment by radioflyer28** [comment]
Thanks, that clears things up. I'm not sure that path will work for me, using Elemental Operator to provision machines via Rancher. My goal was to use Elemental to provision machines with Rancher installed on them so I could stand up a Rancher multi-cluster management server (I don't have an existing Rancher server to use).

P.S. can I request/suggest updating the docs to strongly indicate ros-installer is deprecated? That may save someone else a few hours. I'm referring to this page in particular: https://rancher.github.io/elemental/installation/

**Comment by Itxaka** [comment]
Good point, we are in the process of updating the docs because they are terribly outdated.


Btw I think you can probably achieve the same thing by using a combination of a custom elemental-toolkit derivative + elemental-cli + cloud-init files. Have a look at https://github.com/c3os-io/c3os for something similar that setups a k8s cluster based on elemental-toolkit 😀👍

**Comment by radioflyer28** [comment]
> Good point, we are in the process of updating the docs because they are terribly outdated.
> 
> Btw I think you can probably achieve the same thing by using a combination of a custom elemental-toolkit derivative + elemental-cli + cloud-init files. Have a look at https://github.com/c3os-io/c3os for something similar that setups a k8s cluster based on elemental-toolkit 😀👍

I've been trying out c3os, just wanted to say thanks!
