### ISSUE TITLE
Docs: Elemental community release

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental#233]
While we have all the functional pieces working, noone from the community can consume the great work the team has done in the last 2-3 weeks.
Let's share our achievement with the community and enable them to use the "new" elemental stack

overhaul of rancher.github.io/elemental (written descending priority)

- [x] #235
- [x] #237
- [x] #236
- [x] #241
- [x] #244
- [x] #242
- [x] #243
- [x] #240
- [x] #239
- [x] #224
- [ ] Clarify what en Elemental release encompasses, which are the artifacts, where they are, etc. Related to #193

Goal: Have someone from the community deploy an Elemental cluster (single node k3s is sufficient)

**Comment by Itxaka** [comment]
We also need to fix https://github.com/rancher/elemental/issues/193 as the release pipeline is currently disabled.


@kkaempf  What are the requirements for the release? A OCI artifact? ISO? vagrant environment? ISOs are useless currently unless we create some script to inject the cloud config into a final iso, as the iso will boot and do nothing. We have the create-elemental-iso which accepts that but also with defaults wont work out of the box.


What is the acceptable steps that someone from the community need to do to deploy a cluster? Manual elemental install and then manual call to elemental-register with an url? We want everything automated? half of it?

**Comment by Itxaka** [comment]
For example, on the elemental-operator we have a target int he makefile that locally installs a kind cluster and installs everything, including the operator.

Would that be acceptable for the community to play with? OR do we want VMs for that? Or we want them to install the operator and play with it in a real k8s cluster?

**Comment by kkaempf** [comment]
> @kkaempf What are the requirements for the release? 

Documentation (esp. a "quick start") to get a machine deployed with Elemental Teal (based on the build service artefacts) and connected to Rancher.

> What is the acceptable steps that someone from the community need to do to deploy a cluster? Manual elemental install and then manual call to elemental-register with an url? We want everything automated? half of it?

No automation, no UI, just a handful of CLI commands. This is my usual script for deployments:

- "helm install elemental-operator"
- `kubectl apply` -f <machine-registration-yam>
- `wget` https://<management-cluster>/elemental/registration/....
- `elemental-iso-build` ...
- boot the ISO (this should auto-install and reboot)
- lookup the `machineInventory` in the Rancher UI
- `kubectl label MachineInventory` ...
- `kubectl apply` -f machine-selector-template-...
- `kubectl apply` -f create-cluster.yaml

**Comment by kkaempf** [comment]
> Would that be acceptable for the community to play with? OR do we want VMs for that? Or we want them to install the operator and play with it in a real k8s cluster?

We should assume that people have successfully deployed Rancher Manager before. (Ideally, this is just a `docker` call :wink:)

**Comment by kkaempf** [comment]
Discussions ongoing. Will close this issue now.
