### ISSUE TITLE
Custom bootstrap local plan

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental#242]
New section about providing custom system agent plans that are executed at bootstrap phase.

**Comment by Itxaka** [comment]
rancher-system-agent or elemental-system-agent?

**Comment by Itxaka** [comment]
also doesnt help that we call our stuff bootstrap and rancher-system-agent also does a bootstrap ¬_¬

**Comment by fgiudici** [comment]
😅 yep, a bit confusing... In this case is the local plan, which is processed by elemental-system-agent I think (if nothing has changed!).

**Comment by Itxaka** [comment]
I think this meant elemental-system-agent as that is the only one that has a local plan enabled
