### ISSUE TITLE
Exploratory testing with Rancher / Elemental on ARM64

### ISSUE THREAD

**Issue by juadk** [rancher/elemental#294]
To get more familiar with Elemental, I would like to test building and installing it on my Raspberry pi 4 cluster.
I will report my findings here.
My plan:

1. Install k3s and Rancher on my Raspberry pi system (TW system, already done on Raspbian)
2. Build image for another system
3. Boot it and check if I can see it in the elemental UI

**Comment by kkaempf** [comment]
Be aware that deploying aarch64 clusters is not supported with Rancher. Only _import_ of such cluster is.
Elemental on aarch64 won't make much sense :-(

**Comment by juadk** [comment]
Ok thanks Klaus, let's forget this one then.

**Comment by chris13524** [comment]
Does Rancher plan to support Raspberry Pi clusters in the future? I would like to use Elemental w/ Raspberry Pi

**Comment by agracey** [comment]
Yes, but before we do so we need to make sure all of the pieces (including the provisioning of k3s from Rancher) are supported. 

We will likely continue to need a TPM chip when using more than a single device. I have a few of these on order to be able to play around with: https://thepihut.com/products/letstrust-tpm-for-raspberry-pi
