### ISSUE TITLE
Guidance on using rd.cos.debugrw  ( Testing and debug support )

### ISSUE THREAD

**Issue by sudheermygapula** [rancher/elemental#306]
sudo zypper in cockpit-wicked
**The target filesystem is mounted as read-only. Please make sure the target filesystem is writeable.**

how to configure this param to generate the elemental ISO which allow to install packages.

**Comment by davidcassany** [comment]
I am not sure what you are attempting to do here, however this parameter was only created at early days of Elemental only for debugging purposes, it should not be used for anything else. This was meant to be used for debugging issues while we were developing the immutable rootfs setup.

That being said the way to permanently include software in Elemental images is by using one of the following approaches:
* create a derivative image. As Elemental OS is a container image you can layer on top of it including the software you desire, then you can rebuild the ISO based on your custom Elemental image including extra software.
* install software in persistent areas. You can install under `/usr/local` or make the specific locations of the installed software persistent by configuring them as such, see [immutable rootfs dracut module](https://rancher.github.io/elemental-toolkit/docs/reference/packages/system-immutable-rootfs/) reference docs and the default setup in `system/oem/01_elemental-rootfs.yaml`.

Given that you are aiming to install a distro provided package I believe the easiest is to build a derivative container image.

**Comment by sudheermygapula** [comment]
Hello Thanks for the input  ,  The aim was to have debug /test build where we can test the distro or our own application before creating derivative image.  One way currently am doing is editing boot parameter  , i also explored that this can be done using grub config . would like to know if you already have documentation for creating such debug or test builds .
