### ISSUE TITLE
Software bill of materials (SBOM)

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental#307]
(This is created as an `elemental` issue simply because we don't have a better place for Elemental (the product) )

Elemental Teal should be accompanied with a ["Software Bill Of Materials" (SBOM)](https://en.wikipedia.org/wiki/Software_supply_chain) to document the software supply chain.

Apparently [Kubewarden](https://en.wikipedia.org/wiki/Software_supply_chain) is using [CLO Monitor](https://clomonitor.io) to visualize their SBOM efforts.

- reach out to Kubewarden team to learn about their SBOM efforts
- create a document (github issue/epic) on how to implement this for Elemental Teal

**Comment by Itxaka** [comment]
This is the PR that aded the sbom to kubewarden. Seems simple enough: https://github.com/kubewarden/kubewarden-controller/pull/246

**Comment by Itxaka** [comment]
https://github.com/rancher/elemental-operator/pull/160

**Comment by fgiudici** [comment]
PR reverted: https://github.com/rancher/elemental-operator/pull/191

**Comment by Itxaka** [comment]
Dont really understand why it could not find the command. Will try in a separate repo to see what is going on.

**Comment by kkaempf** [comment]
Just for the record: https://fosdem.org/2023/schedule/event/sbom_key_ingredients/
