### ISSUE TITLE
Using Elemental as base image when creating a new cluster using Harvester

### ISSUE THREAD

**Issue by RegisHubelia** [rancher/elemental#311]
Hi,

I'm not sure this is the right channel for this or if it is better to open this issue on the harvester repo, but basically, Harvester's images to create new clusters from rancher on harvester isn't extensively documented.  I currently use ubuntu images to create new clusters, but I would like to see some documentation on how to use Elemental images instead of using ubuntu.  There is documentation on how to create ISOs, but I couldn't find anything on how to use Elemental as the base image for new clusters created within Rancher using Harvester.  Is this a use case that will be supported eventually?

Thanks!

**Comment by davidcassany** [comment]
@RegisHubelia thanks to reach us out and for the interest on Elemental. I am not sure what are you attempting to do and I am not knowledgeable about Harvester, I might be very unprecise. Probably @bk201 can correct me if wrong and provide a Harvester PoV.

I assume you want to create Rancher managed clusters based on Elemental nodes using Harvester provided VMs, is that right?

Note we are not producing Elemental disk images for the time being as we are targeting edge at the moment and for that we aim to bootstrap hardware from ISOs as the main installation media. I am not aware if one can boot VMs from custom ISOs in Harvester, but if so then following our [quick start](https://rancher.github.io/elemental/quickstart/) guide should be enough to get you started. As long you have Rancher 2.6 deployed and you are capable to boot a box with a custom crafted ISO that can reach Rancher manager it should be enough.

Building disk images is something we have in our radar but there is no ETA at the moment.

**Comment by RegisHubelia** [comment]
Thanks @davidcassany, this answers my question.  I appreciate it.

Regards
