### ISSUE TITLE
Empty `/etc/resolv.conf`

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental#319]
Since the latest release (11th of September 2022) elemental does not properly set `/etc/resolv.conf` file at boot. In fact, sle-micro-for-rancher introduced `NetworkManager` in this release.

**Comment by kkaempf** [comment]
This only happens when using sle-micro-rancher:5.3, right ?!

**Comment by Itxaka** [comment]
> This only happens when using sle-micro-rancher:5.3, right ?!

Yup, @ldevulder tested with 5.2 and it doesn't have the issue

**Comment by Itxaka** [comment]
on an iso built from github I get no network at all on the iso, due to NetworkManager being stopped. Once started I get network but no resolv.conf

In any case, the default should call netconfig anyways, but Im not getting any dns, even when calling `netconfig update -f` :thinking:

**Comment by Itxaka** [comment]
weird, NetworkManager knows about the dns its just not setting it for some reason

```
rancher-3553:~ # nmcli con show ffa53cb0-d2e2-3102-aada-45fc870449ba|grep -i dns
connection.mdns:                        -1 (default)
connection.dns-over-tls:                -1 (default)
ipv4.dns:                               --
ipv4.dns-search:                        --
ipv4.dns-options:                       --
ipv4.dns-priority:                      0
ipv4.ignore-auto-dns:                   no
ipv6.dns:                               --
ipv6.dns-search:                        --
ipv6.dns-options:                       --
ipv6.dns-priority:                      0
ipv6.ignore-auto-dns:                   no
IP4.DNS[1]:                             192.168.122.1
```

**Comment by Itxaka** [comment]
oh yeah, found it, netconfig checks to see if NetworkManager service is enabled. If it its it merges the config via STATIC_FALLBACK * NetworkManager, thus obtaining the dns from NetworkManager and adding any static servers in there.

Of course in elemental we dont have NetworkManager enabled so it fails and only sets the static servers, which there are none.

Simple Patch incoming

**Comment by kkaempf** [comment]
Hmm, we should add it to systemd-presets-branding-Elemental, no ?!
(which used to be generic for any Teal version. Not sure what happens when we enable a non-existing service 🤔 )

**Comment by Itxaka** [comment]
yeah, Im not sure why I said it was gonna be simple :)

**Comment by kkaempf** [comment]
Hmm, I just pulled registry.opensuse.org/isv/rancher/elemental/teal53/15.4/rancher/elemental-node-image/5.3 and had a look. There's still `wicked` in there and no `NetworkManager` ?!

/me confused 😕

**Comment by Itxaka** [comment]
yes, OBS builds will probably be ok until a new rebuild is done

Basically the 5.3 that we used on the current image has no networkmanager but if we trigger a new build it will pick the refreshed 5.3 image which contains networkmanager.


This is mostly affecting github builds currently which will also affect OBS down the line.

**Comment by kkaempf** [comment]
I just updated packages in OBS which will trigger an image rebuild ... 🙄

**Comment by kkaempf** [comment]
Booted with new ISO, `NetworkManager` is running and `/etc/resolv.conf` is present.

Closing as fixed.

**Comment by Itxaka** [comment]
nooo, github still not fixed, tests not running :D

**Comment by Itxaka** [comment]
partially fixed by https://github.com/rancher/elemental/pull/321 for github, will discuss the approach of enabling the services on the dockerfile instead which sounds nicer.
