### ISSUE TITLE
Design 3rd party driver loading

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental#334]
https://github.com/rancher/elemental/discussions/331 points to an important aspect - loading of 3rd party drivers at boot time.

This issue is about documenting a possible approach (or multiple with their pros and cons) how a customer could integrate (and load) a kernel driver into the boot process.

- how to load a driver when booting from ISO
- how to load a driver when booting from installed disk
- how to handle kernel updates (possibly requiring a new driver) ?
- how to handle secure boot ?
- make it declarative (cloud-config ?) and permanent (gets loaded on every boot)

Plans don't seem to help here as they're only run once and thus not permanent. 🤔 

Derived images might be hard to support as there's no clear boundary between supported and unsupported. Also allowing derived images might be misused for adding all kinds of rpms.

Acceptance criteria

- Documentation (similar to an RFC - see [here](https://github.com/kubewarden/rfc) for examples) on a possible process

**Comment by kkaempf** [comment]
Initial environment assumption
- boot image is accessible without 3rd party driver
- driver might be required to setup network (to access Rancher management cluster)
- driver might be required to install Elemental on persistant storage

**Comment by davidcassany** [comment]
I have been thinking about it for a while and I came to the conclusion we could eventually consider all solved by providing a custom configuration yaml file for the `elemental install`. Currently `elemental-register` calls a plain `elemental install` command passing the install parameters of the machine registration as environment variables. These variables only represent a small portion of all the possibilities of the installation configuration. See most of the options in [docs](https://rancher.github.io/elemental-toolkit/docs/customizing/general_configuration/). In addition the installation reads cloud-init style hooks from the install media in three different stages:

* before install
* after install chroot (chrooted into the installed system)
* after install 

The installation hooks (and any cloud-init file) by default are read from `/oem/`, `/system/oem` and `/usr/local/cloud-config`, additional paths can be included with the `config.yaml`. So, having the flexibility of including custom `config.yaml` into the installation media widely opens (probably too much!) the available options at install time.

Then with a custom `config.yaml` we could:

1. Include additional cloud-init files to install and make use of extra software at boot time. 
2. Include custom installation hooks that could modify the OS at install time in almost any way (including the installation of third party drivers).

@rancher/elemental does it make sense in elementa-operator change the elemental-cli so we include a `--config-dir` flag pointing to a path outside the squashed filesystem? 

Imagine `elemental --config-dir /run/initramfs/live/etc/elemental install` so the root of the ISO filesystem could include a `/etc/elemental/config.yaml` that could injected in a similar way the machine registration is added. If no `config.yaml` exists in the path defaults apply as they are now.

**Comment by Itxaka** [comment]
Sounds good, kairos does something like that to modify the system grub stuff after install and after upgrade, so their changes are always stored to disk. Its a good approach and its tested to work to modify the root system with any extra random stuff that you want. Very generic approach to any modifications.

**Comment by davidcassany** [comment]
Also the `--config-dir` value could be passed as part of the install spec in the machine registration. So I think we can simply solve this issue by adding this flag value into the Install struct in https://github.com/rancher/elemental-operator/blob/9c1d506fa944fcd4f7afe96db2dd2853f0427b61/pkg/config/config.go#L19-L33 and using it for the `elemental install` command in elemental-register.

Then we could document two different scenarios:

* Add custom cloud-init files to the installation so they are eventually executed at boot
* Add custom after install hooks to modify installed system
