### ISSUE TITLE
Bring elemental-iso-build (or something similar) back

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental#347]
#342 removed `elemental-iso-build`, breaking our documentation and everyone's workflow who has worked with Teal.

We need to bring this script back (or something similar)

No, `make iso` is not a replacement as this requires to have `make` installed. Not everyone out there has a developer environment :wink:

**Comment by Itxaka** [comment]
`elemental-iso-build` is now prepared to be shipped as part of the release, which should provide the script with a fixed tag, so you can download it from the releases and it builds an iso for the given image.

The script is still available under the `.github` dir if you want to build from main :)
