### ISSUE TITLE
How to set api-server domain name?

### ISSUE THREAD

**Issue by jclab-joseph** [rancher/elemental#355]
Can't set rke2/config.yaml because elemental installs rke2 automatically.
How can I set tls-san and api-server address?

**Comment by kkaempf** [comment]
Cluster installation isn't handled by Elemental itself but by the management cluster. The [standard Rancher documentation abour RKE2 installation](https://rancher.com/docs/rancher/v2.6/en/cluster-admin/editing-clusters/rke2-config-reference) should apply here.

**Comment by jclab-joseph** [comment]
Move to https://forums.rancher.com/t/how-to-set-server-url-for-ha-via-elemental/39076
