### ISSUE TITLE
[DOCS] Where is the `https://raw.githubusercontent.com/rancher/elemental/main/elemental-iso-build`

### ISSUE THREAD

**Issue by east4ming** [rancher/elemental#362]
Follow the [quickstart](https://rancher.github.io/elemental/quickstart/), I can't find the `https://raw.githubusercontent.com/rancher/elemental/main/elemental-iso-build`.

**Comment by east4ming** [comment]
`https://raw.githubusercontent.com/rancher/elemental/main/.github/elemental-iso-build` ?

**Comment by fgiudici** [comment]
Yep, just moved under .github ... 
Good catch, thanks!

**Comment by fgiudici** [comment]
Related: https://github.com/rancher/elemental/issues/347
