### ISSUE TITLE
Create an Architectural Decision Record document to explain the migration from Wrangler to Controller Runtime

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental#377]
This card is about creating a simple document to explain and showcase the motivations of moving from Wrangler framework to Controller Runtime framework in elemental-operator.

The idea is to mimic the procedure described in https://github.com/rancher/rke2/tree/master/docs/adrs#architectural-decision-records-adrs.

For that I'd suggest to create a new discussion in https://github.com/rancher/elemental/discussions trying to briefly cover three aspects: 
* The motivation (upstream community, maintainability, testing, etc.)
* Rough steps on the process to achieve it (swap controllers one by one in a parallel branch, prepare current ci pipes on main for the new branch, links to the draft PRs, etc.) 
* Few thoughts about the impact of the change over the product (is that implying changes on the API, backward compatibility, etc.)

**Comment by alexander-demichev** [comment]
https://github.com/rancher/elemental/discussions/409

**Comment by davidcassany** [comment]
Closing, there is already a ADR posted as a discussion within the repository
