### ISSUE TITLE
Create QA test plan when an Elemental release happens

### ISSUE THREAD

**Issue by juadk** [rancher/elemental#397]
We need a document to describe what to do/check for every release of Elemental, is it automated or manual etc...
First words are in this issue https://github.com/rancher/elemental/issues/288

**Comment by kkaempf** [comment]
👍🏻 

and we would need a sub-plan for every maintenance update (like a kernel update) 😉

**Comment by juadk** [comment]
Ok, I'm thinking about a template and we will duplicate it for every validation we will have to do.

**Comment by ldevulder** [comment]
Test plan is done in confluence. Something for maintenance still need to be done.
