### ISSUE TITLE
Research - Use autoscaling for self-hosted runners in public cloud

### ISSUE THREAD

**Issue by juadk** [rancher/elemental#399]
Right now, we have self hosted runners in the public cloud, the machines is started and stopped on demand.
It is a good first step but when we will add more tests, we will need something better.

We can think about autoscaling the runners, it is possible with the Github API and there are some resources on how to achieve it.
For instance:
https://www.dev-eth0.de/2021/03/09/autoscaling-gitlab-runner-instances-on-google-cloud-platform/
https://medium.com/philips-technology-blog/scaling-github-action-runners-a4a45f7c67a6
https://github.blog/changelog/2021-09-20-github-actions-ephemeral-self-hosted-runners-new-webhooks-for-auto-scaling/

But it's low priority at the moment.

**Comment by aktech** [comment]
By the way, if you want a no-maintenance method to achieve that, you can use [cirun.io](https://cirun.io) for the same.

**Comment by juadk** [comment]
Done here https://github.com/rancher/elemental/pull/546
