### ISSUE TITLE
Helm chart release and maintenance flow in OBS

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental#411]
In our current helm chart builds in OBS `isv:Rancher:Elemental:Dev` or `isv:Rancher:Elemental:Staging` the repository of the elemental operator image is set in `_services` to be replaced at build time to a value that is dependent on the OBS project path. This bad because it means OBS sources needs to be adapted depending on the project the build is happening. In an RPM context I would simply solve this by setting some macro in the project configuration, something like `%define repo <published repository>` and make use of such a variable in spec. This way it would be possible to move sources from project A to project B without having to modify them as the project configuration of each would include the value of the appropriate repository. This is relevant for testing, so we can test in project A and submit to project B without modifying the sources and being sure they are the same.

This card is about finding a solution for the eventual chart build in `isv:Rancher:Elemental:Stable`, which should include exact same sources in IBS and the build should be functional in both cases.

**Comment by kkaempf** [comment]
Uhm, not sure how to solve this.

(Trying to be explicit here for those without IBS knowledge :wink:)

There are (resp. will be) 3 builds in IBS
1. Devel:Elemental - linked to ...:Stable
1. SUSE:Maintenance:... (tbd) - the 'staging' project for every maintenance update requested by us. <- this is what we need to test
1. SUSE:...:Elemental (tbd) - the official build project, owned by maintenance - this is synced to registry.suse.com

We can only influence 1. and submit to 2. Copying from 2. to 3. is not in our hands.

**Comment by davidcassany** [comment]
I was wondering if there was a way to add environment variables to the build env from project configuration or something similar, in that case we could define some build service to actually run a replacement based on some env variable.

**Comment by davidcassany** [comment]
My idea is to expand the [obs-service-replave_using_env](https://build.opensuse.org/package/show/Virtualization/obs-service-replace_using_env) to support expanding from rpm macros too, so we could eventually have something in services like:

```xml
<services>
  <service name="replace_using_env" mode="buildtime">
    <param name="file">values.yaml</param>
    <param name="macro">image_repo</param>
  </service>
</services>
```

and project configuration including:

```
%define image_repo registry.opensuse.org/my/project/path/repository
```

and a values.yaml with

```yaml
...
  repository: "%%image_repo%%"
...
```

It is a damn simple bash script and the new `--macro` flag would simply call `rpm -E "%<falg_value>"`, as macros define in project configuration are included into the build environment as part of `~/.rpmmacros`

**Comment by davidcassany** [comment]
I consider this done. The macro setup has been included in the Elemental OBS builds confluence page with a link to this issue for full reference if needed.
