### ISSUE TITLE
ServiceAccount for MachineRegistration doesn't get Secret added when created through UI

### ISSUE THREAD

**Issue by agracey** [rancher/elemental#422]
**What steps did you take and what happened:**
When a user creates a MachineRegistration in the Rancher UI (not the extension) by browsing to the MachineRegistration list and clicking "Create" or by clicking "Import Yaml" and pasting in the contents, the ServiceAccount tied to that MachineRegistration doesn't get the correct Secret applied to it and machines can't register correctly. 

The really interesting thing is that if I apply the same YAML through kubectl, it works as expected and the Secret shows up. 

This seems to only start happening once we added the GlobalRole to the helm chart. (I've since accidentally destroyed my environment so I can't A/B test anymore... but I did confirm that it only happened post upgrade where that was the only change in the chart)

I'm 99% sure that this is a Rancher issue but it's worth a look to see if there's a way we can solve it on our side.

**What did you expect to happen:**
It shouldn't matter how to MachineRegistration is created, the system should just work. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Elemental release version (use `cat /etc/os-release`): operator at 0.6.0 
- Rancher version: 2.6.8
- Kubernetes version (use `kubectl version`): 1.24.6
- Cloud provider or hardware configuration: Digital Ocean, NUCs

**Comment by fgiudici** [comment]
Hey @agracey , this is tracked in https://github.com/rancher/elemental-operator/issues/197 and should be now fixed.
The required change was in OBS only.

**Comment by agracey** [comment]
Ah, thank you! I knew there was an issue but I couldn't find it again.

**Comment by agracey** [comment]
Closing this issue. If you can reproduce, let's reopen other ticket.
