### ISSUE TITLE
Booting takes a while on more recent releases

### ISSUE THREAD

**Issue by agracey** [rancher/elemental#428]
**What steps did you take and what happened:**
On the latest stable version in OBS, booting takes a while and the logging seems to get stuck on initrd starting. This seems to be some new behavior as it used to be very fast.

**What did you expect to happen:**
The OS should boot quickly given that it's relatively minimal.

**Environment:**

- Elemental release version (use `cat /etc/os-release`): 20.20
- Rancher version: 2.6.8
- Kubernetes version (use `kubectl version`): 
- Cloud provider or hardware configuration: Have seen this on both Intel NUC and VMs

**Comment by kkaempf** [comment]
The [ISO](https://download.opensuse.org/repositories/isv:/Rancher:/Elemental:/Staging:/Teal53/media/iso/elemental-teal.x86_64.iso) boots normal under virt-manager.

Where do you see slowness, ISO or installed system ?
If booting is slow, please attach `dmesg` output.

**Comment by kkaempf** [comment]
No further reports, closing
