### ISSUE TITLE
Acceptance tests: manual upgrades

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental#43]
Split of https://github.com/rancher-sandbox/os2/issues/28

Manual upgrades, following cOS default usage and `ros-installer`

**Comment by ldevulder** [comment]
Playing with `Dockerfile` and elemental cli to see how it works, as I mainly used it through Rancher.

**Comment by ldevulder** [comment]
@mudler for manual upgrade I think that executing something like `elemental upgrade -d quay.io/costoolkit/os2:v0.1.0-amd64` is enough?

In a e2e test I think I can install the latest released version in a VM and upgrade it to the latest build one with this kind of command. Pretty much what is already done with the e2e test with Rancher, but manually :-)

**Comment by mudler** [comment]
in a e2e test scenario I think we could even push some releases here over github so we can pick them up somehow in the tests. 
In c3os I played with this and ended up to pull off latest artifacts releases from github and giving them as input iso: https://github.com/c3os-io/c3os/blob/master/.github/workflows/image.yaml#L308 As test suites run over SSH, at the end is easy enough to hook em up from a different medium

**Comment by ldevulder** [comment]
> https://github.com/c3os-io/c3os/blob/master/.github/workflows/image.yaml#L308

Interesting! I also upload/download for the current build but a handmade code to download the lastet build, sounds easier with `robinraju/release-downloader`. I will git it a try then!
