### ISSUE TITLE
Testing all hands

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental#431]
Tracker issue to report and collect any failure or bug found in Staging OBS artifacts.

Artifacts to test can be found in `isv:Rancher:Elemental:Staging` (helm chart) and `isv:Rancher:Elemental:Staging:Teal53` (iso).

Tests against rancher 2.6.9

**Comment by davidcassany** [comment]
I am wondering if shouldn't we include https://github.com/rancher/elemental-operator/pull/222 for the 2.6.9 release, even we initially targeted it for 2.7.0.

**Comment by fgiudici** [comment]
yep we should

**Comment by kkaempf** [comment]
considered done
