### ISSUE TITLE
Open source clearance support

### ISSUE THREAD

**Issue by sudheermygapula** [rancher/elemental#444]
**What steps did you take and what happened:**
where to download source code registry.suse.com/suse/sle-micro-rancher/5.3  , typically to ship elemental along with other products need to have clearance from open source team , looking for instructions to download the source code for base images **registry.suse.com/suse/sle-micro-rancher/5.3** .

**What did you expect to happen:**
Clear instructions to get the sources for open source clearance.

**Anything else you would like to add:**
NA

**Environment:**

- Elemental release version (use `cat /etc/os-release`): v0.2.0
- Rancher version:2.6.6
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:

**Comment by davidcassany** [comment]
I am not sure I fully understand what is expected here. The base image is provided as part of the SLE Micro initiative, the base image `suse/sle-micro-rancher/5.3` is created ad-hoc for Elemental Teal. The base image sources can be found in the [Open Build Service](https://build.opensuse.org), it is the `SLE-Micro-Rancher` package from `SUSE:SLE-15-SP4:Update:Products:Micro53` project.

Would you have expected a similar explanation in Elemental docs?

**Comment by kkaempf** [comment]
Requirement to publish source comes from [GPL](https://opensource.org/licenses/GPL-2.0). However, Elemental is [Apache-2.0]( https://www.apache.org/licenses/LICENSE-2.0.html) licensed.

That said, SUSE is a good open-source citizen and source code is published here:
* [SLE Micro 5.3](https://build.opensuse.org/project/show/SUSE:SLE-15-SP4:Update:Products:Micro53)
* [Elemental](https://build.opensuse.org/project/show/isv:Rancher:Elemental)

Closing this issue.

Please reopen if you think this is not fully resolved.
