### ISSUE TITLE
[rke2] configure NetworkManager to ignore calico/flannel related network interfaces.

### ISSUE THREAD

**Issue by Itxaka** [rancher/elemental#446]
According to rke2 docs we need to tell NM to not manage the calico/flannel interfaces in case we are deploying rke2 with elemental.

This is in the middle of being a bug and a feature to be honest, I havent find any issues when deploying rke2 but its tru that we were using wicked back then and now elemental ships with NM by default.

https://docs.rke2.io/known_issues/#networkmanager

**Comment by kkaempf** [comment]
Looks fairly simple to do ...

**Comment by ldevulder** [comment]
What is the current impact? I didn't saw issues with rke2 on my test (manual or automated).

**Comment by Itxaka** [comment]
Me neither but its clear on the docs that NM can interfere with the network interfaces of calico/flannel. Maybe on advanced deployments with complicated network setups it will appear? Maybe some specific configurations trigger this? No idea to be honest, but I rather us cover this before it happens :D

**Comment by kkaempf** [comment]
Updated `elemental` package in OBS ✅

**Comment by Itxaka** [comment]
> Updated `elemental` package in OBS white_check_mark

@kkaempf I thought that was now automatic?

**Comment by kkaempf** [comment]
> > Updated `elemental` package in OBS white_check_mark
> 
> @kkaempf I thought that was now automatic?

Yes, that's why the build failed 😉 
The `%files` section does not get updated auto'magic'ally 😆
