### ISSUE TITLE
docs: update docs (section by section)

### ISSUE THREAD

**Issue by fgiudici** [rancher/elemental#458]
Review the actual docs and check if they are up-to-date:
- links are up-to-date to the latest and greatest
- provided documentation is correct
- check if the documentation is complete (all features, parameters, etc.)

Let's split the work section by section:

- [x] #452 
- [x] #453 
- [x] #454 
- [x] #455 
- [x] #456 
- [x] #457

**Comment by pgonin** [comment]
All done. Closing.
