### ISSUE TITLE
Drop squashfs path in grub.cfg and elemental-cli

### ISSUE THREAD

**Issue by Itxaka** [rancher/elemental#488]
**Describe the solution you'd like:**
REmove squashfs stuff from grub.cfg as we are not using it

**Anything else you would like to add:**
This means we have to override the grub.cfg file that ships by default with the toolkit by our custom one. Changes done to the toolkit ones would need to be reflected in ours.

**Comment by davidcassany** [comment]
Probably before doing that I'd be more in favor of making the change in elemental-toolkit directly. I know changing grub in there is painful, but I think we probably can do it without actually breaking anything. For secure boot if the efi image already includes the module I don't think it has to be loaded in the grub.cfg (no `insmod squash4` needed), if that's the case, then we can probably easily drop it directly from elemental-toolkit. In that case squashfs would still be possible if efi image contains the module or, for non secure boot scenarios, the `insmod squash4` could be added as part of the `custom_blk` variable if rebuilding the efi image is not possible or undesired (are currently doing it in grub-efi-image package).

**Comment by davidcassany** [comment]
> Doesnt this means a breaking change for anything using the toolkit?

It is a change with as similar impact as splitting BIOS vs EFI, no feature is strictly lost, but the change is not transparent. So my take if the current squashfs support is not satisfying and needs to evolve, probably even die at some point, now it is a good point in time to prepare the ground.

I'd be satisfied if the outcome of the discussion in https://github.com/rancher/elemental-toolkit/discussions/1626 leads to drop squashfs from CI scope and from bootloader scope. That is removing squashfs installation tests and removing squashfs explicit support in bootloader configuration. IMHO the less we have in `grub.cfg` the better, less risk we actually need or desire to touch it in the future.
