### ISSUE TITLE
test: test Elemental and Rancher Manager interactions with a proxy

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental#492]
More a manual test first, could be added in E2E later, if technically possible.

**Comment by juadk** [comment]
As we don not have more information about that test, I did some research over documentation and confluence and it looks like Rancher QA is testing:
- Deploying Rancher with a proxy | Provision downstream RKE2 cluster without a proxy
- Deploying Rancher without a proxy | Provision downstream custom RKE2 cluster with a proxy
- Deploying Rancher without a proxy | Provision downstream node driver RKE2 cluster with a proxy

I think we can do the same, I'm trying getting access to code.

**Comment by juadk** [comment]
I spoke with Rancher QA and they pointed me to https://github.com/rancher/rancher/blob/release/v2.7/tests/validation/tests/v3_api/test_proxy.py

**Comment by juadk** [comment]
Well, I was able to manually test two scenarios:
Of course you need a running proxy, I used squid in a container for that:
`docker run -d -v /root/squid.conf:/etc/squid/squid.conf -p 3128:3128 wernight/squid`
[squid.conf.txt](https://github.com/rancher/elemental/files/10278981/squid.conf.txt)

## Rancher behind proxy and elemental node without proxy
Install Rancher with these additional options:
`--set http_proxy=http://YOUR_PROXY:PORT --set https_proxy=http://YOUR_PROXY:PORT --set no_proxy=127.0.0.0/8\\,10.0.0.0/8\\,cattle-system.svc\\,172.16.0.0/12\\,192.168.0.0/16\\,.svc\\,.cluster.local`

## Rancher without proxy and elemental node behind proxy
When you create your elemental cluster, make sure to add the following variables in the Agent Environment Vars:
HTTP_PROXY, HTTPS_PROXY, NO_PROXY

![image](https://user-images.githubusercontent.com/6025636/208942081-5b9fae80-cc23-4376-b56b-837e74d81613.png)

Then I deployed an app to my elemental node and I checked my proxy's logs (access.log) and the traffic went through it.

**Comment by juadk** [comment]
I keep this issue open to track the automation.
