### ISSUE TITLE
Propagate machineInventory labels to nodes

### ISSUE THREAD

**Issue by frelon** [rancher/elemental#509]
When a new node is provisioned we should propagate the labels from the machineInventory to the actual k3s/rke2 node.

**Comment by agracey** [comment]
I was under the impression that this did happen but it looks like only the hostname gets propogated. This might be something that we need to wait for the CAPI work to adopt.

IMO, I think we should focus on cluster selections for updates at the moment until we see a user request for upgrading certain nodes differently.

**Comment by alexander-demicev** [comment]
@agracey Label sync between machines and nodes is coming in close future https://github.com/kubernetes-sigs/cluster-api/pull/7296

**Comment by alexander-demicev** [comment]
we already expose nodeselector field https://github.com/rancher/elemental-operator/blob/main/pkg/apis/elemental.cattle.io/v1beta1/os.go#L46 that allows updating nodes on the clusters individually.

**Comment by frelon** [comment]
> @agracey Label sync between machines and nodes is coming in close future [kubernetes-sigs/cluster-api#7296](https://github.com/kubernetes-sigs/cluster-api/pull/7296)

@alexander-demicev That looks interesting! I'm guessing we will still need to implement this propagation in the elemental-operator? Or will this work out of the box for our CRD:s as well?

**Comment by alexander-demicev** [comment]
It will work for us too, the labels will be set through MachineDeployment.

**Comment by frelon** [comment]
Great, then I will close this!

**Comment by kkaempf** [comment]
rancher/elemental-operator#243
