### ISSUE TITLE
Docs: quickstart "location" label is confusing

### ISSUE THREAD

**Issue by agracey** [rancher/elemental#521]
When working through the quickstart, the usage of "location" as a label provided by the MachineRegistration can cause confusion where a reader will assume that each cluster/location needs its own MachineRegistration. 

I'm thinking that a better flow might be to add a step of patching the MachineInventory with a label to act as the selector. That tells a story that's closer to how we expect a real use-case to look.

**Comment by frelon** [comment]
I'm thinking about removing the location-label entirely from the quickstart and create a new section for more advanced use-cases where we mention this flow, WDYT? @agracey

**Comment by agracey** [comment]
What are you thinking of keying the selector template off of instead?

**Comment by agracey** [comment]
Also, we should likely move this issue to the docs repo (I don't think I have access to do that move)

**Comment by frelon** [comment]
> What are you thinking of keying the selector template off of instead?

Aha, I thought an empty selector would match anything, but that might not be the case! Then I'm out of ideas! I could have a shot at changing the docs in the new repo to reflect the flow with patching a machine-inventory!

**Comment by frelon** [comment]
Looking at the docs i guess something like this would also work:

```yaml
...
spec:
  template:
    spec:
      selector:
        matchExpressions:
          - key: manufacturer
            operator: Exists
```

**Comment by agracey** [comment]
I think the patching flow since it tells the story better. 

Then, in the advanced topics section we can explain how to get the node to discover and label itself. (I put this together but haven't had a chance to test it: https://github.com/agracey/label-elemental-nodes)

**Comment by frelon** [comment]
@agracey Here we go: https://github.com/rancher/elemental-docs/pull/18
