### ISSUE TITLE
Not able to set the static IP address in elemental OS

### ISSUE THREAD

**Issue by divyashukla25** [rancher/elemental#529]
**How to set the static IP address in elemental?**
I want to update the IP address from dynamic to static ip address. So, I have created a custom file and also set the static IP address in /etc/sysconfig/network/ifcfg-eth0 network file in my elemental machine and then rebooted the machine. But after reboot, static IP dosn't reflect. my system still picking the dhcp IP.

*What did you expect to happen:**

I want to set the static IP address on my elemental machine.

##### Network files

```
divya:~ # cat /etc/sysconfig/network/ifcfg-eth0 
IPADDR="192.168.6.167"
BOOTPROTO="none"
STARTMODE="onboot"
NAME="eth0"
NETMASK="255.255.255.0"
GATEWAY="192.168.6.2"
USERCONTROL="no"
MTU=''
TYPE="Ethernet"
PROXY_METHOD="none"
BROWSER_ONLY="no"
DEFROUTE="yes"
IPV4_FAILURE_FATAL="no"
DEVICE="eth0"
ONBOOT="yes"
divya:~ # 
```
Network /oem/91_custom.yaml file

```
name: "Default network configuration"
stages:
   initramfs:
     - name: "Setup network"
       files:
       - path: /etc/sysconfig/network/ifcfg-eth0
         content: |
                  IPADDR="192.168.6.167"
                  BOOTPROTO="none"
                  STARTMODE="onboot"
                  NAME="eth0"
                  NETMASK="255.255.255.0"
                  GATEWAY="192.168.6.2"
                  USERCONTROL="no"
                  MTU=''
                  TYPE="Ethernet"
                  PROXY_METHOD="none"
                  BROWSER_ONLY="no"
                  DEFROUTE="yes"
                  IPV4_FAILURE_FATAL="no"
                  DEVICE="eth0"
                  ONBOOT="yes"
         permissions: 0600
         owner: 0
         group: 0
```

**Environment:**

- Elemental release version (use `cat /etc/os-release`): Elemental 5.3
- Rancher version: 2.6.9
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:

**Comment by divyashukla25** [comment]
Please help me on how to set the static IP address. I need it on urgent basis.

**Comment by kkaempf** [comment]
https://github.com/rancher/elemental-toolkit/blob/main/docs/content/en/docs/Examples/cloud_config.md has an example of setting a static IP address.
The obvious diff to your example above is
```
            BOOTPROTO='static'
```

**Comment by divyashukla25** [comment]
Thanks for your reply. But this didn't work for me. 

Basically, I'm trying to do is "Runtime persistence changes". We are applying changes to the image in runtime. I'm also using NetworkManager, and trying to set the static IP. And its work but after the reboot all the changes I have made to set the static IP is removed and my IP is set to dhcp again.
Please tell me how I can do the runtime persistence changes and so, I can keep the static IP even after the reboot.

Is there any guidance for updating the Ip address and hostname using this "elemental upgrade" concept?
I tried by using this one also https://rancher.github.io/elemental-toolkit/docs/customizing/stages/#after-install-chroot but didn't work
<img width="500" alt="image" src="https://user-images.githubusercontent.com/112463911/203487573-99d38ea8-528d-4f9b-b14f-0799605c5205.png">

Please help us, we need it on urgent basis.

**Comment by kkaempf** [comment]
> Thanks for your reply. But this didn't work for me.

😮 

> 
> Basically, I'm trying to do is "Runtime persistence changes". We are applying changes to the image in runtime.

Any runtime changes to `/etc` are ephemeral.

> I'm also using NetworkManager, and trying to set the static IP. And its work but after the reboot all the changes I have made to set the static IP is removed and my IP is set to dhcp again. Please tell me how I can do the runtime persistence changes and so, I can keep the static IP even after the reboot.

See https://rancher.github.io/elemental-toolkit/docs/customizing/configuration_persistency/

If you're using Rancher [Elemental Teal](https://rancher.github.io/elemental/quickstart), you would add a respective `files:` entry to `spec.config.cloud-config` in [`machineRegistration`](https://rancher.github.io/elemental/quickstart)

> 
> Is there any guidance for updating the Ip address and hostname using this "elemental upgrade" concept?

`elemental upgrade` is for upgrading the base operating system. It does not touch the configuration files.

> 
> Also, after putting above file and then reboot, got the below issue <img alt="image" width="346" src="https://user-images.githubusercontent.com/112463911/203493305-6fab6872-ee6d-4a6f-82fb-16156e185564.png">

You would need to share your complete `machineRegistration` (resp. cloud-config yaml) with us. It looks like some grub parameter is wrong.

**Comment by divyashukla25** [comment]
Thanks, it works with this https://rancher.github.io/elemental-toolkit/docs/customizing/configuration_persistency/ 

And **elemental upgrade** we are using the elemental airgap.

**Comment by kkaempf** [comment]
Glad that it works for you.
