### ISSUE TITLE
Image names and labels for elemental stack

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental#541]
In our current built artifacts we have the following image names and labels. `<NUM>` is the OBS build ID and `<registry>` is the registry domain and base repository where OBS pushes to.

HELM CHART:
```
<registry>/elemental/elemental-operator:
   * latest
   * 1.0.0
   * 1.0.0-build<NUM>
```   
TEAL IMAGE:
```
<registry>/rancher/elemental-teal/5.3:
   * 1.0.0
   * 1.0.0-<NUM>
  
<registry>/rancher/elemental-node-image/5.3:
   * latest
   * 1.0.0
```
   
BUILDER IMAGE:
```
<registry>/rancher/elemental-builder-image/5.3:
   * latest
   * 0.1.3
   * 0.1.3-<NUM>
```
   
OPERATOR IMAGE:
```
<registry>/rancher/elemental-operator/5.3:
   * latest
   * 1.0.0
   * 1.0.0-<NUM>
```

I see a couple of little issues here, I'd say they should be fixed before the release:
* Helm chart is not under `rancher` repository like all others, I doubt this was on purpose.
* Teal image has two different repositories but they do not follow the tree tags approach like other images, note that including a tag with the build ID might be relevant for base OS upgrades not coming from us (CVEs in the base image)

Beyond this two little issues I am wondering if the schema of `/rancher/<image>/5.3` repository is what we want. Also it is unclear to me why do we have two different repositories for the teal image, it doesn't hurt, but I don't see how this could be used.

@kkaempf @agracey @rancher/elemental  are you fine with the current tags? Anything you think it should be arranged?

**Comment by kkaempf** [comment]
I think `builder` can also be promoted to `1.0.0`

**Comment by kkaempf** [comment]
> Helm chart is not under rancher repository like all others, I doubt this was on purpose.

How about putting it under `.../rancher/elemental-operator-chart` (also to not conflict with the respective image path) ?!

**Comment by kkaempf** [comment]
> Teal image has two different repositories but they do not follow the tree tags approach like other images

You're free to change this. `node-image` was just invented by me when I needed it. Probably time to drop this name 🤔

**Comment by davidcassany** [comment]
> > Helm chart is not under rancher repository like all others, I doubt this was on purpose.
> 
> How about putting it under `.../rancher/elemental-operator-chart` (also to not conflict with the respective image path) ?!

Yes, that looks simple and obvious, I'd go for it.

**Comment by kkaempf** [comment]
>  I am wondering if the schema of /rancher/<image>/5.3 repository is what we want.

We're still having the problem of how to reflect changes of the OS. Going from 5.3 (aka SLE 15 SP 4) to 5.4 (aka SLE 15 SP5) might not be a simple step depending on the hardware. So keeping the `5.3` suffix is probably helpful.

Not sure how to express the OS version otherwise 🤔

**Comment by davidcassany** [comment]
> > Teal image has two different repositories but they do not follow the tree tags approach like other images
> 
> You're free to change this. `node-image` was just invented by me when I needed it. Probably time to drop this name thinking

Right, then I think dropping it might be good, so we will not be asked about the differences between the two. I can already foresee queries about it.

**Comment by davidcassany** [comment]
> We're still having the problem of how to reflect changes of the OS. Going from 5.3 (aka SLE 15 SP 4) to 5.4 (aka SLE 15 SP5) might not be a simple step depending on the hardware. So keeping the 5.3 suffix is probably helpful.
>
> Not sure how to express the OS version otherwise :thinking:

I am absolutely fine with the current setup, I just raised it because I saw there used to be something different in IBS.

**Comment by kkaempf** [comment]
The project setup in IBS is independent from the registry path. The latter is set with the `BuildTag`

**Comment by davidcassany** [comment]
> The project setup in IBS is independent from the registry path. The latter is set with the `BuildTag`

Sure, I know, in fact the `BuildTag` is what I pretend to agree on here. All the values discusses here are set by `BuildTag`, so all this applies to IBS too. In IBS the `<registry>` placeholder form the above list will simply be (once released) `registry.suse.com`, while in OBS it is `registry.opensuse.org/<project-path>`.

**Comment by davidcassany** [comment]
So up to now these are the changes to include:

* Drop `/rancher/elemental-node-image/5.3`
* Add `latest` tag to `rancher/elemental-teal/5.3`
* Change helm chart repo to `rancher/elemental-operator-chart`

I'll wait for @agracey feedback before and then coordinate the change with the testing so we do not step over each other.

**Comment by agracey** [comment]
These changes make sense to me. 

I feel like there was a reason that I'm not finding in my notes, but why not have the elemental-teal image be:
- `rancher/elemental-teal:5.3-latest`
- `rancher/elemental-teal:5.3-1.0.0`
- `rancher/elemental-teal:5.3-1.0.0-<num>`

Was is that we didn't like non-semvar tags?

**Comment by davidcassany** [comment]
Honestly I prefer `rancher/elemental/5.3:1.0.0` as to my eyes this gives a better hint on that an eventual `rancher/elemental/5.4:x.y.z` might be something else than  just a version bump, but a different code stream. Also if we ever have to support something like `rancher/elemental/5.4:x.y.z` and `rancher/elemental/5.3:x.y.z` I believe this separation beyond the tag makes sense.

No strong opinion though

**Comment by kkaempf** [comment]
Considered done
