### ISSUE TITLE
How to change the Elemental BIOS password?

### ISSUE THREAD

**Issue by divyashukla25** [rancher/elemental#548]
I'm using the elemental airgap os. I'm trying to update the Bios password after the installation. Could you please tell me how I can update the Bios password in elemental OS?

**Environment:**

- Elemental release version (use `cat /etc/os-release`): v5.3
- Rancher version: v2.6.9
- Kubernetes version (use `kubectl version`): v1.24.4

**Comment by davidcassany** [comment]
I have few doubts about the environment.

Which is the OS you installed? so far we don't have any v5.3 version, where did you get the OS? could you provide the whole `/etc/os-release`?

Then I am not sure I understand what are you referring to by the Bios password. BIOS support in elemental is likely to be deprecated in favor of UEFI and I'd strongly recommend using UEFI firmware to enable secure boot and use nowadays firmware. However it is not entirely clear to me you are actually referring to a firmware setup, elemental doesn't perform any firmware setup or configuration beyond setting UEFI boot entries.

Our expectation is that the only really important password you should have to setup in an Elemental deployment is the root user password (or keys for remote access) so you can actually login to the system if needed. Could it be you are trying to set the root password?

**Comment by divyashukla25** [comment]
I'm using the elemental airgap os.

I'm picking the latest version of the base images from: -
- OS_IMAGE=registry.opensuse.org/isv/rancher/elemental/stable/teal53/15.4/rancher/elemental-node-image/5.3:${ELEMENTAL_OS_VERSION} 
export TOOL_IMAGE?=registry.opensuse.org/isv/rancher/elemental/stable/teal53/15.4/rancher/elemental-builder-image/5.3:${ELEMENTAL_TOOL_VERSION}

My custom elemental airgap os /etc/os-release file looks like this
<img width="317" alt="image" src="https://user-images.githubusercontent.com/112463911/205251453-e2f1aab7-4fc5-4281-ab58-98808dfdb7bf.png">
  
And yes, I'm also using the UEFI firmware. Could you please tell me, is it possible to update the Bios password, if yes, then how we can do it?

**Comment by davidcassany** [comment]
Elemental does not perform any kind of firmware setup (BIOS or UEFI), as this is mostly OS unrelated and likely to be vendor specific. Which hardware are you using? Does your vendor provide some tooling to set the firmware from the client OS? If so then you could try to include such tool in the elemental based OS and script its usage as part of a cloud-init configuration.

We are not targeting BIOS firmware, we are mostly keeping BIOS bootloader support for testing purposes in virtualized environments.

**Comment by kkaempf** [comment]
Closing due to lack of response
