### ISSUE TITLE
Injection script should be able to reuse local iso

### ISSUE THREAD

**Issue by Itxaka** [rancher/elemental#552]
currently if you have the iso already downloaded in the same dir, it will refuse to inject the file. It should be safe to reuse the same iso over and over to inject the registration file.

```
$ .github/elemental-iso-add-registration initial-registration.yaml
Pulling artifacts from isv:Rancher:Elemental:Stable OBS project
Error: /home/itxaka/projects/elemental/elemental-teal.x86_64.iso already exists, aborting

```

**Comment by davidcassany** [comment]
This is already supported, `elemental-iso-add-registration` only downloads the iso if you don't provide one. If the ISO is explicitly provided as the second argument it is not downloaded.
