### ISSUE TITLE
Quickstart docs include how to boot on raspberry pi

### ISSUE THREAD

**Issue by jpke** [rancher/elemental#558]
**Describe the solution you'd like:**
Following along in the [Quickstart docs](https://rancher.github.io/elemental/quickstart#preparing-the-iso), I am trying to boot an aarch64 iso image on a Raspberry Pi 3b. My Rancher server is accessible on my local network, however the pi fails to register. I cannot even see it on my local network. Attempting to boot while plugged into a monitor fails to show anything on the screen (which I assume is expected, given elemental does not include a gui).

I've tried googling to find instructions for how to boot Elemental Teal on a raspberry pi, but have found nothing. I would assume this should be straightforward- I just need to flash the teal iso onto an SD card, put the card into the pi and turn the pi on. If other steps are required, please add these to the quickstart, or link to them.

**Anything else you would like to add:**
I'm very excited to get Elemental Teal working on a raspberry pi. Thanks for your help!

**Environment:**

- Elemental release version (use `cat /etc/os-release`): Unable to boot elemental teal os to find this. Builder image was `registry.opensuse.org/isv/rancher/elemental/stable/teal53/15.4/rancher/elemental-builder-image/5.3:latest`
- Rancher version: `v2.7.0`
- Kubernetes version (use `kubectl version`): `v1.24.8+k3s1`
- Cloud provider or hardware configuration: Running k3s in multipass vm

**Comment by agracey** [comment]
We don't support aarch64 yet but you can follow the development in the issues found here: https://github.com/rancher/elemental-toolkit/issues?q=is%3Aissue+is%3Aopen+arm

**Comment by kkaempf** [comment]
It's done !
The [development documentation](http://elemental.docs.rancher.com/next/) has quickstart instructions for Raspberry Pi now.

**Comment by jpke** [comment]
Thanks! Working through this - I'm on this step `The written USB stick will have two partitions. RPI_BOOT contains the boot loader files and COS_LIVE the Elemental files.`, however, I can only see `RPI_BOOT` mounted. I'm on OSX 12.6, and used Etcher to write the rpi.raw file to an empty usb stick.

When running `diskutil list`, I can see 
```
/dev/disk6 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *4.0 GB     disk6
   1:             Windows_FAT_32 RPI_BOOT                134.2 MB   disk6s1
   2:                      Linux                         664.8 MB   disk6s2
                    (free space)                         3.2 GB     -
```

But when I try to mount the partition I assume `COS_LIVE` is on, I get:
```
▶ diskutil mount /dev/disk6s2
Volume on disk6s2 failed to mount
Perhaps the operation is not supported (kDAReturnUnsupported)
If you think the volume is supported but damaged, try the "readOnly" option
```

Is there any way I can access the `COS_LIVE` partition, so I can run `sudo cp initial-registration.yaml /run/media/$USER/COS_LIVE/livecd-cloud-config.yaml`? Currently returns `No such file or directory`, since this partition is not mounted.

**Comment by kkaempf** [comment]
@jpke how did you download the `.raw` image ?
I sometimes had problems with Firefox doing incomplete downloads. This seems to be the case here.
Please try to download the image using `curl` or `wget` on the command line.

I will extend the documentation to include how to download and check the `sha256` checksum file.

**Comment by jpke** [comment]
No luck.

I downloaded the `.raw` image via the `wget` command from the docs. Interestingly, the `sha256` checksum failed when I tested, following the updated docs. I downloaded the `.raw` file again via `wget` and verified this new download had a valid checksum. However, loading this image onto the usb stick via etcher and also via `dd` failed to show any difference. I can only see the `RPI_BOOT` partition when the usb stick is mounted to my osx machine.

`diskutil list` and `diskutil mount /dev/disk5s2` show the same output as posted above.

**Comment by kkaempf** [comment]
🤯 🤔 

What does `file rpi.raw` report for you ?
It should show
```
rpi.raw: DOS/MBR boot sector; partition 1 : ID=0xc, active, start-CHS (0x0,32,33), end-CHS (0x10,113,33), startsector 2048, 262144 sectors; partition 2 : ID=0x83, start-CHS (0x10,113,34), end-CHS (0x61,68,35), startsector 264192, 1298432 sectors
```

Please also make sure to run `sync` after `dd` finishes. Then unplug the stick and re-plug it in order to resync the kernel's partition knowledge.

Can you find someone with Linux ? I fear that OSX fails to correctly write/recognize the image 😞
