### ISSUE TITLE
elemental-system-agent (seems to be) started before timesyncd

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental#567]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

When booting an installed image on Raspberry Pi, `elemental-system-agent` complains about 
```
panic: error while connecting to Kubernetes cluster: Get "https://192.168.0.28/k8s/clusters/local/version": x509: certificate has expired or is not yet valid: current time 2022-11-03T12:01:01Z is before 2022-12-01T14:19:13Z
```

after a while these messages stop as `systemd-timesyncd` kicks in.

Raspberry Pi has no (buffered) hardware clock and depends on network and timesyncd to get the correct date/time.

**What did you expect to happen:**

`elemental-system-agent` not getting in panic.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Elemental release version (use `cat /etc/os-release`):
- Rancher version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:

**Comment by Itxaka** [comment]
same for obs https://build.opensuse.org/request/show/1041879

**Comment by kkaempf** [comment]
#575 should fix that.
