### ISSUE TITLE
e2e: test iso bulding API

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental#578]
~Related to #207.~

We just need to wait for this feature to be done and then check if this have to be tested on UI only or CLI too.

**Comment by fgiudici** [comment]
Also related to https://github.com/rancher/elemental-operator/issues/207

**Comment by juadk** [comment]
## Manuel tests ongoing

https://github.com/rancher/elemental-operator/issues/398
https://github.com/rancher/elemental-ui/issues/91

Other thing we have to talk about is the seed image pod:
```
fleet-default               vvnfnalelnavgfct                          1/1     Running     0          23h
fleet-default               gzvdorojkbcbeqre                          1/1     Running     0          87m
```
I think we need a mechanism to delete the pod after a certain amount of time.

**Comment by juadk** [comment]
The new automation is ready but I face network issue in the CI, probably an issue between Rancher manager and cypress inside a container:


![Image](https://user-images.githubusercontent.com/6025636/226909481-8b0db771-aa2c-436b-89bf-985e80735bf0.png)

**Comment by juadk** [comment]
Bad gateway happened because I didn't use latest operator...

I face another issue today when building the ISO:
`fleet-default               xdhmwkojkxqtmnlw                           0/1     Init:Error   0          28m`

```
gh-runner@elemental-ci-d045cf02-222e-47f6-a91b-2f1ef89cc61d:~> kubectl logs xdhmwkojkxqtmnlw -n fleet-default build
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
100  642M  100  642M    0     0  7722k      0  0:01:25  0:01:25 --:--:-- 14.9M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: elemental-ci-d045cf02-222e-47f6-a91b-2f1ef89cc61d.us-central1-a.c.ei-container-eco.internal
```

**Comment by juadk** [comment]
I did some tests inside a github runner and we can make it by using the public dns name of the runner instead the google internal one. 
`72.147.72.34.bc.googleusercontent.com` instead of `elemental-ci-c79f114c-8b34-41a4-be97-9f6e9e8f6704.us-central1-a.c.ei-container-eco.internal`

![image](https://user-images.githubusercontent.com/6025636/227481784-6b6b4287-3249-4295-9615-daa5e5f13be4.png)

The issue depends on https://github.com/rancher/elemental/issues/729
Once, resolved, I will be able to continue the automation.
