### ISSUE TITLE
ci: find a way to add autogenerated tests description

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental#596]
It could be useful to find a way to autogenerated a `tests/README.md` file that summarize the integration/e2e/ui tests. In addition find, a way to schedule this with GHA could be good.

EDIT: this [GH action](https://github.com/marketplace/actions/add-commit) sounds interesting to add the commit automatically, will give it a try.

**Comment by Itxaka** [comment]
you can generate a json report with the following: `ginkgo -v --dry-run --json-report=report.json ./e2e` which includes the suite, number of tests and so on, so we should be then able to parse that to generate a decent markdown file.

This is without executing the test, which I gues its the intention here, to have a file that tracks the tests. If something more complex is required (i.e. parse the comments as explanations, like we do with error codes on elemental-cli) then its a bit more complicated.

**Comment by ldevulder** [comment]
@Itxaka thanks, I will check the `ginkgo` command. But I already have a script for this that parses `Describe/It/By`. The script works with Ginkgo and Cypress code and can be adapted for other frameworks as long as they follow this TestSuite syntax.
