### ISSUE TITLE
Base image for the container `rancher/elemental-builder-image/5.4`

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental#619]
Currently the [builder image](https://build.opensuse.org/package/show/isv:Rancher:Elemental:Dev:Teal53/builder-image) is being used to build the ISO and it is based on the generic `suse/sle15:15.4` base image. This image is likely to be delivered on a regular elemental-operator installations as part of the ISO building feature rancher/elemental-operator#207 The question here is which should be the right base for this image. Note this is actually a regular container image, it does not require kernel, systemd and friends.

**Comment by fgiudici** [comment]
🤔 adding just a note here: seems the right choice to me, as the base system we target there is SLE micro.
SLE micro will likely miss all the build tools we need for the build image (as is.... micro) but shares the same libraries (and so their versions) as SLE.
Good to review this though.

**Comment by kkaempf** [comment]
The builder image isn't supposed to be shipped or supported. It's just used within OBS to create the seed image (ISO for x86_64, .raw for aarch64).
Once we think about allowing 3rd parties to build their own ISOs, the base image becomes relevant.

**Comment by davidcassany** [comment]
> It's just used within OBS to create the seed image (ISO for x86_64, .raw for aarch64).

Currently this image is also used within the script to inject the registration yaml. I mostly did this card to properly consider if the builder image should be used or not within the context of the `Download ISO` feature or not. We could use elemental-teal for that too, but feels like an overkill to pull a full OS image just to download and an ISO and call xorriso on it.

**Comment by kkaempf** [comment]
For the RPi (probably all `aarch64` images) I'm currently working on a different solution. Without the need for `mount` or any other privileged commands 😉

**Comment by davidcassany** [comment]
> For the RPi (probably all `aarch64` images) I'm currently working on a different solution. Without the need for `mount` or any other privileged commands wink

Interesting, I am revisiting the whole `elemental build-disk` command to build full images without the need of mount (having the data center use case in mind). I guess today I'll start the actual testing 🤞🏽

**Comment by kkaempf** [comment]
This is done in "Dev"
