### ISSUE TITLE
Elemental node registered to Rancher but elemental-system-agent at node keeps on loop with no proper error message

### ISSUE THREAD

**Issue by yshashix** [rancher/elemental#620]
- I took steps as suggested in the Elemental Quickstart guide but after booting Elemental Teal ISO, my machine reboot and then get stuck with error as below:

rancher-31156:~ # journalctl -f -u elemental-system-agent
Jan 18 17:29:06 rancher-31156 elemental-system-agent[1738]: time="2023-01-18T17:29:06Z" level=debug msg="[K8s] Processing secret m-e1473c86-171d-4f84-a67f-54b20398180b in namespace fleet-default at generation 0 with resource version 467933"
Jan 18 17:29:06 rancher-31156 elemental-system-agent[1738]: time="2023-01-18T17:29:06Z" level=debug msg="[K8s] Applied checksum was the same as the plan from remote. Not applying."
Jan 18 17:29:06 rancher-31156 elemental-system-agent[1738]: time="2023-01-18T17:29:06Z" level=debug msg="[K8s] last applied resource version (467933) did not change. running probes, skipping apply."
Jan 18 17:29:06 rancher-31156 elemental-system-agent[1738]: time="2023-01-18T17:29:06Z" level=debug msg="[Applyinator] Applying plan with checksum 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a"
Jan 18 17:29:06 rancher-31156 elemental-system-agent[1738]: time="2023-01-18T17:29:06Z" level=debug msg="[Applyinator] Writing applied calculated plan contents to historical plan directory /var/lib/elemental/agent/applied"
Jan 18 17:29:06 rancher-31156 elemental-system-agent[1738]: time="2023-01-18T17:29:06Z" level=debug msg="[Applyinator] Not writing applied plan to file 20230118-172906-applied.plan as the last file written (20230118-171542-applied.plan) had identical contents"
Jan 18 17:29:06 rancher-31156 elemental-system-agent[1738]: time="2023-01-18T17:29:06Z" level=debug msg="[Applyinator] Cleaning working directory before applying /var/lib/elemental/agent/work"
Jan 18 17:29:06 rancher-31156 elemental-system-agent[1738]: time="2023-01-18T17:29:06Z" level=debug msg="[K8s] writing an applied checksum value of 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a to the remote plan"
Jan 18 17:29:06 rancher-31156 elemental-system-agent[1738]: time="2023-01-18T17:29:06Z" level=debug msg="[K8s] Enqueueing after 5.000000 seconds"
Jan 18 17:29:06 rancher-31156 elemental-system-agent[1738]: time="2023-01-18T17:29:06Z" level=debug msg="[K8s] secret data/string-data did not change, not updating secret"
Jan 18 17:29:11 rancher-31156 elemental-system-agent[1738]: time="2023-01-18T17:29:11Z" level=debug msg="[K8s] Processing secret m-e1473c86-171d-4f84-a67f-54b20398180b in namespace fleet-default at generation 0 with resource version 467933"
Jan 18 17:29:11 rancher-31156 elemental-system-agent[1738]: time="2023-01-18T17:29:11Z" level=debug msg="[K8s] Applied checksum was the same as the plan from remote. Not applying."
Jan 18 17:29:11 rancher-31156 elemental-system-agent[1738]: time="2023-01-18T17:29:11Z" level=debug msg="[K8s] last applied resource version (467933) did not change. running probes, skipping apply."
Jan 18 17:29:11 rancher-31156 elemental-system-agent[1738]: time="2023-01-18T17:29:11Z" level=debug msg="[Applyinator] Applying plan with checksum 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a"
Jan 18 17:29:11 rancher-31156 elemental-system-agent[1738]: time="2023-01-18T17:29:11Z" level=debug msg="[Applyinator] Writing applied calculated plan contents to historical plan directory /var/lib/elemental/agent/applied"
Jan 18 17:29:11 rancher-31156 elemental-system-agent[1738]: time="2023-01-18T17:29:11Z" level=debug msg="[Applyinator] Not writing applied plan to file 20230118-172911-applied.plan as the last file written (20230118-171542-applied.plan) had identical contents"
Jan 18 17:29:11 rancher-31156 elemental-system-agent[1738]: time="2023-01-18T17:29:11Z" level=debug msg="[Applyinator] Cleaning working directory before applying /var/lib/elemental/agent/work"
Jan 18 17:29:11 rancher-31156 elemental-system-agent[1738]: time="2023-01-18T17:29:11Z" level=debug msg="[K8s] writing an applied checksum value of 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a to the remote plan"
Jan 18 17:29:11 rancher-31156 elemental-system-agent[1738]: time="2023-01-18T17:29:11Z" level=debug msg="[K8s] Enqueueing after 5.000000 seconds"
Jan 18 17:29:11 rancher-31156 elemental-system-agent[1738]: time="2023-01-18T17:29:11Z" level=debug msg="[K8s] secret data/string-data did not change, not updating secret"
^C
rancher-31156:~ # journalctl -f -u rancher-system-agent
^C
rancher-31156:~ #

- Where as elemental shows no error:

rancher-31156:~ # journalctl -f -t elemental
Jan 18 17:15:41 rancher-31156 elemental[1699]: INFO[2023-01-18T17:15:41Z] Done executing stage 'network.after'
Jan 18 17:15:41 rancher-31156 elemental[1699]: INFO[2023-01-18T17:15:41Z] Running stage: network.before
Jan 18 17:15:41 rancher-31156 elemental[1699]: INFO[2023-01-18T17:15:41Z] Executing BOOT_IMAGE=(loop0)/boot/vmlinuz console=tty1 console=ttyS0 root=LABEL=COS_ACTIVE cos-img/filename=/cOS/active.img panic=5 rd.cos.oemlabel=COS_OEM rd.neednet=0 rd.emergency=reboot rd.shell=0 panic=5 systemd.crash_reboot systemd.crash_shell=0
Jan 18 17:15:41 rancher-31156 elemental[1699]: INFO[2023-01-18T17:15:41Z] Done executing stage 'network.before'
Jan 18 17:15:41 rancher-31156 elemental[1699]: INFO[2023-01-18T17:15:41Z] Running stage: network
Jan 18 17:15:41 rancher-31156 elemental[1699]: INFO[2023-01-18T17:15:41Z] Executing BOOT_IMAGE=(loop0)/boot/vmlinuz console=tty1 console=ttyS0 root=LABEL=COS_ACTIVE cos-img/filename=/cOS/active.img panic=5 rd.cos.oemlabel=COS_OEM rd.neednet=0 rd.emergency=reboot rd.shell=0 panic=5 systemd.crash_reboot systemd.crash_shell=0
Jan 18 17:15:41 rancher-31156 elemental[1699]: INFO[2023-01-18T17:15:41Z] Done executing stage 'network'
Jan 18 17:15:41 rancher-31156 elemental[1699]: INFO[2023-01-18T17:15:41Z] Running stage: network.after
Jan 18 17:15:41 rancher-31156 elemental[1699]: INFO[2023-01-18T17:15:41Z] Executing BOOT_IMAGE=(loop0)/boot/vmlinuz console=tty1 console=ttyS0 root=LABEL=COS_ACTIVE cos-img/filename=/cOS/active.img panic=5 rd.cos.oemlabel=COS_OEM rd.neednet=0 rd.emergency=reboot rd.shell=0 panic=5 systemd.crash_reboot systemd.crash_shell=0
Jan 18 17:15:41 rancher-31156 elemental[1699]: INFO[2023-01-18T17:15:41Z] Done executing stage 'network.after'

**What did you expect to happen:**
- I expect Device on boarded to RMS elemental cluster and install k3s and my elemental cluster active, not in provisioning 

**Anything else you would like to add:**
- I tried multiple times and even tried after uninstalling elemental-operator helm charts from scratch, but still get same issue.

**Environment:**

- Elemental release version (use `cat /etc/os-release`):

     rancher-31156:~ # cat /etc/os-release
    NAME="SLE Micro"
    VERSION="5.3"
    VERSION_ID="5.3"
    PRETTY_NAME="SUSE Linux Enterprise Micro for Rancher 5.3"
    ID="sle-micro-rancher"
    ID_LIKE="suse"
    ANSI_COLOR="0;32"
    CPE_NAME="cpe:/o:suse:sle-micro-rancher:5.3"
    IMAGE_REPO="registry.opensuse.org/isv/rancher/elemental/stable/teal53/15.4/rancher/elemental-teal/5.3"
    IMAGE_TAG="1.0.0-33.29"
    IMAGE="registry.opensuse.org/isv/rancher/elemental/stable/teal53/15.4/rancher/elemental-teal/5.3:1.0.0-33.29"
    TIMESTAMP=20230110084743
    GRUB_ENTRY_NAME="Elemental"
    rancher-31156:~ #
    
 - Rancher version: 2.7
    
- Kubernetes version (use `kubectl version`):

hades22@hades2xxxx:~$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4+k3s1", GitCommit:"c3f830e9b9ed8a4d9d0e2aa663b4591b923a296e", GitTreeState:"clean", BuildDate:"2022-08-25T03:45:26Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.26) and server (1.24) exceeds the supported minor version skew of +/-1

- Cloud provider or hardware configuration:
HW is Intel NUC i7 with 8 core , 32 GB ram and TPM in it

![Rancher server Dashboard of provisioning](https://user-images.githubusercontent.com/86843454/213255473-69f38b21-f928-4056-9167-0c153b457960.png)

**Comment by frelon** [comment]
Hi @yshashix 

Could you also please post the elemental-operator logs `kubectl logs -n cattle-elemental-system -l app=elemental-operator` and the resources used (MachineRegistration, Cluster,  and MachineInventorySelectorTemplate)  and also the generated MachineInventory `kubectl get machineinventory -n fleet-default -o yaml`

**Comment by frelon** [comment]
Did you remove the elemental resources when reinstalling the operator? One thing that could show this behavior is reinstalling a machine without removing the MachineInventory. Then the rancher-system-agent will still believe plans are applied to the machine and do nothing.

**Comment by yshashix** [comment]
@frelon ,
I have deleted selector.yaml ,cluster.yaml ,registration.yaml and also deleted Namespace: [cattle-elemental-system]. It was fresh installation and there was no MachineInventory before I reboot node with ISO, so I guess it could be something more.

Steps I followed to delete operators are:

           kubectl delete -f registration.yaml
  501  kubectl delete -f cluster.yaml
  502  kubectl delete -f selector.yaml
  503  helm --uninstall elemental-operator -n cattle-elemental-system
  504  helm uninstall elemental-operator -n cattle-elemental-system
  505  helm list -A
  506  kubectl get pods -n cattle-elemental-system
  507  kubectl get ns
  508  kubectl delete namespace cattle-elemental-system
  --------------------------------------
  
  Elemental Operator is not able to connect to steve aggregations:
  hades22@hades22-NUC8i7HVK:~$ kubectl logs -n cattle-elemental-system -l app=elemental-operator
time="2023-01-19T08:41:58Z" level=info msg="Starting steve aggregation client"
time="2023-01-19T08:41:58Z" level=info msg="Starting /v1, Kind=ServiceAccount controller"
time="2023-01-19T08:41:58Z" level=error msg="Failed to dial steve aggregation server: dial tcp 10.43.177.163:443: connect: connection refused"
time="2023-01-19T08:42:01Z" level=error msg="error syncing 'fleet-default/my-nodes': handler machine-registration: add Secret to my-nodes ServiceAccount: Internal error occurred: failed calling webhook \"rancher.cattle.io\": failed to call webhook: Post \"https://rancher-webhook.cattle-system.svc:443/v1/webhook/mutation?timeout=10s\": proxy error from 127.0.0.1:6443 while dialing 10.42.0.61:9443, code 503: 503 Service Unavailable, requeuing"
time="2023-01-19T08:42:04Z" level=error msg="error syncing 'fleet-default/my-nodes': handler machine-registration: add Secret to my-nodes ServiceAccount: Internal error occurred: failed calling webhook \"rancher.cattle.io\": failed to call webhook: Post \"https://rancher-webhook.cattle-system.svc:443/v1/webhook/mutation?timeout=10s\": proxy error from 127.0.0.1:6443 while dialing 10.42.0.61:9443, code 503: 503 Service Unavailable, requeuing"
time="2023-01-19T08:42:07Z" level=error msg="error syncing 'fleet-default/my-nodes': handler machine-registration: add Secret to my-nodes ServiceAccount: Internal error occurred: failed calling webhook \"rancher.cattle.io\": failed to call webhook: Post \"https://rancher-webhook.cattle-system.svc:443/v1/webhook/mutation?timeout=10s\": proxy error from 127.0.0.1:6443 while dialing 10.42.0.61:9443, code 503: 503 Service Unavailable, requeuing"
time="2023-01-19T08:42:10Z" level=error msg="error syncing 'fleet-default/my-nodes': handler machine-registration: add Secret to my-nodes ServiceAccount: Internal error occurred: failed calling webhook \"rancher.cattle.io\": failed to call webhook: Post \"https://rancher-webhook.cattle-system.svc:443/v1/webhook/mutation?timeout=10s\": proxy error from 127.0.0.1:6443 while dialing 10.42.0.61:9443, code 503: 503 Service Unavailable, requeuing"
time="2023-01-19T08:42:13Z" level=error msg="error syncing 'fleet-default/my-nodes': handler machine-registration: add Secret to my-nodes ServiceAccount: Internal error occurred: failed calling webhook \"rancher.cattle.io\": failed to call webhook: Post \"https://rancher-webhook.cattle-system.svc:443/v1/webhook/mutation?timeout=10s\": proxy error from 127.0.0.1:6443 while dialing 10.42.0.61:9443, code 503: 503 Service Unavailable, requeuing"
time="2023-01-19T08:42:16Z" level=error msg="error syncing 'fleet-default/my-nodes': handler machine-registration: add Secret to my-nodes ServiceAccount: Internal error occurred: failed calling webhook \"rancher.cattle.io\": failed to call webhook: Post \"https://rancher-webhook.cattle-system.svc:443/v1/webhook/mutation?timeout=10s\": proxy error from 127.0.0.1:6443 while dialing 10.42.0.61:9443, code 503: 503 Service Unavailable, requeuing"
time="2023-01-19T09:41:58Z" level=info msg="Creating event broadcaster for mos-sync"
hades22@hades22-NUC8i7HVK:~$


---------------------
Generated Mahineinventory:

hades22@hades22-NUC8i7HVK:~$ kubectl get machineinventory -n fleet-default -o yaml
apiVersion: v1
items:
- apiVersion: elemental.cattle.io/v1beta1
  kind: MachineInventory
  metadata:
    creationTimestamp: "2023-01-18T17:10:09Z"
    generation: 1
    labels:
      machineUUID: e1473c86-171d-4f84-a67f-54b20398180b
      manufacturer: Intel-R-Client-Systems
      productName: NUC7i7DNHE
      serialNumber: BTDN018000NP
    name: m-e1473c86-171d-4f84-a67f-54b20398180b
    namespace: fleet-default
    resourceVersion: "467936"
    uid: 63439049-8b42-4979-ad34-910b2af6e28a
  spec:
    tpmHash: 4964b06a18e943db64b547996fc17e22513667fa175766679905582571c3a313
  status:
    conditions:
    - lastUpdateTime: "2023-01-18T17:10:09Z"
      reason: InitializedPlan
      status: "True"
      type: Initialized
    - lastUpdateTime: "2023-01-18T17:16:21Z"
      reason: PlanSuccefullyApplied
      status: "True"
      type: Ready
    - lastUpdateTime: "2023-01-18T17:16:21Z"
      reason: PlanSuccefullyApplied
      status: "True"
      type: PlanReady
    plan:
      appliedChecksum: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
      checksum: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
      secretRef:
        name: m-e1473c86-171d-4f84-a67f-54b20398180b
        namespace: fleet-default
kind: List
metadata:
  resourceVersion: ""
hades22@hades22-NUC8i7HVK:~$


-------------------------------------
MachineRegistration, Cluster, and MachineInventorySelectorTemplate are attached
![rancher elemental resource yaml](https://user-images.githubusercontent.com/86843454/213418379-52b6e17d-d05b-411f-886e-1aef59f29204.png)

**Comment by fgiudici** [comment]
Hey @yshashix 👋🏼 
I think you miss the location=europe label in your MachineInventory, which is used to pick up nodes for building cluster.
You can either add the label in the MachineRegistration (under _machineInvetoryLabels_, but *before* doing the registration) or you can add the label manually once the MachineInventory got created. Something like:
`kubectl label -n fleet-default machineinventories.elemental.cattle.io m-e1473c86-171d-4f84-a67f-54b20398180b location=europelocation=europe
`

**Comment by yshashix** [comment]
Ohh yes, I mentioned ith using kubectl label and restarted machine. But somehow it seems doing nothing even now I don't see anything in journalctl -f -u elemental-system-agent but in rancher-system-agent I see below message:

```
m-e1473c86-171d-4f84-a67f-54b20398180b:~ # journalctl -f -u rancher-system-agent
Jan 20 08:45:52 m-e1473c86-171d-4f84-a67f-54b20398180b systemd[1]: Started Rancher System Agent.
Jan 20 08:45:53 m-e1473c86-171d-4f84-a67f-54b20398180b rancher-system-agent[1703]: time="2023-01-20T08:45:53Z" level=info msg="Rancher System Agent version v0.2.13 (4fa9427) is starting"
Jan 20 08:45:53 m-e1473c86-171d-4f84-a67f-54b20398180b rancher-system-agent[1703]: time="2023-01-20T08:45:53Z" level=info msg="Using directory /var/lib/rancher/agent/work for work"
Jan 20 08:45:53 m-e1473c86-171d-4f84-a67f-54b20398180b rancher-system-agent[1703]: time="2023-01-20T08:45:53Z" level=info msg="Starting remote watch of plans"
Jan 20 08:45:53 m-e1473c86-171d-4f84-a67f-54b20398180b rancher-system-agent[1703]: time="2023-01-20T08:45:53Z" level=info msg="Starting /v1, Kind=Secret controller"
^C
```
May be I should do fresh installation next week with Europe location

**Comment by fgiudici** [comment]
Well, if all went right you should have elemental-system-agent stopped now, and rancher-system-agent running (as above).
Seems the selector (which should pick the node based on labels) did not picked up the machineinventory of the host (yet?). 
That would explain rancher-system-agent waiting for plans.
You should also get "Waiting for viable init node" on Rancher, for the cluster. If not, I would bet the selector already picked up a "old?" machineinventory (old installed system). In that case I would delete the cluster and then recreate it.

**Comment by kkaempf** [comment]
closing for lack of progress
