### ISSUE TITLE
machineName not converted to lowercase

### ISSUE THREAD

**Issue by abonillabeeche** [rancher/elemental#626]
**What steps did you take and what happened:**
`machineName: m-${Base Board Information/Serial Number}`

```
ERRO[0005] failed to register machine inventory: MachineInventory creation failed: failed to create machine inventory fleet-default/m-: MachineInventory.elemental.cattle.io "m-" is invalid: metadata.name: Invalid value: "m-": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

...
dmidecode shows
	Serial Number: GEMY52300N1B
```

**What did you expect to happen:**
The serial number which is capitalized, should be set as lowercase

**Environment:**

- Elemental release version (use `cat /etc/os-release`): Staging Op/Staging ISO
rancher-884:~ # cat /etc/os-release
NAME="SLE Micro"
VERSION="5.3"
VERSION_ID="5.3"
PRETTY_NAME="SUSE Linux Enterprise Micro for Rancher 5.3"
ID="sle-micro-rancher"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sle-micro-rancher:5.3"
IMAGE_REPO="registry.opensuse.org/isv/rancher/elemental/staging/teal53/15.4/rancher/elemental-teal/5.3"
IMAGE_TAG="1.0.0-28.37"
IMAGE="registry.opensuse.org/isv/rancher/elemental/staging/teal53/15.4/rancher/elemental-teal/5.3:1.0.0-28.37"
TIMESTAMP=20230120212710
GRUB_ENTRY_NAME="Elemental"
- Rancher version: 2.7.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: Baremetal Intel NUC

**Comment by fgiudici** [comment]
Moving the issue to elemental-operator: https://github.com/rancher/elemental-operator/issues/343
