### ISSUE TITLE
UI - Can't filter using values from known labels

### ISSUE THREAD

**Issue by abonillabeeche** [rancher/elemental#627]
**What steps did you take and what happened:**
Using the UI to Filter nodes based on a label isn't providing a result. I've added a video below.

**What did you expect to happen:**
The UI should filter by the provided value of a label

**Anything else you would like to add:**

https://user-images.githubusercontent.com/5146963/214170462-1c785a14-234e-41b6-a176-ebbb812fd6a7.mov

**Environment:**

- Elemental release version (use `cat /etc/os-release`): Staging/Staging
- Rancher version: 2.7.0
- Kubernetes version (use `kubectl version`): 1.24.7 for local cluster
- Cloud provider or hardware configuration: bare-metal

**Comment by juadk** [comment]
I was able to reproduce the bug and it looks related to lowercase/uppercase...
Using `authenticamd` instead of `AuthenticAMD` does the trick.
![image](https://user-images.githubusercontent.com/6025636/214360716-8b28b9d3-3c04-4078-917e-4e8367d0c7d9.png)

**Comment by juadk** [comment]
Fixed by https://github.com/rancher/dashboard/pull/8055 and tested here https://github.com/rancher/elemental-ui/issues/68
