### ISSUE TITLE
Missing TPM example in doc

### ISSUE THREAD

**Issue by cbosdo** [rancher/elemental#640]
From the quickstart page the link to the libvirt TPM hint is a redirection to Elemental main page... so no TPM tip. Probably this redirection is wrong: https://github.com/rancher/elemental/blob/gh-pages/tpm/index.html

**Comment by davidcassany** [comment]
Indeed, there is something to fix here... thanks for opening the issue :+1:

**Comment by kkaempf** [comment]
Fixed in https://elemental.docs.rancher.com/tpm/#add-tpm-emulation-to-bare-metal-machine
