### ISSUE TITLE
Boot from ISO burned on USB key doesn't work on aarch64 boards

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental#645]
**What steps did you take and what happened:**
Boot from the ISO burned on a USB key doesn't work on my aarch64 boards, but the same works on x86_64. I tried different boards/SoCs (Allwinner, Amlogic, Rockchip) and I have the same issue on all. The same artifacts boot from iPXE on the same boards. I also tested with a Leap 15.4 ISO and all boot well.
I wanted to test on an aarch64 VM but my HV on Tumbleweed seems to have a broken implementation of aarch64... I will try to do it on Leap when I will have enough time.

Maybe some USB modules missing from the initrd?

**What did you expect to happen:**
Be able to boot from the ISO burned on a USB key like on x86_64.

**Anything else you would like to add:**
N/A

**Environment:**
Elemental on aarch64 boards/SoCs with aarch64 version of the Elemental Dev ISO.

- Elemental release version (use `cat /etc/os-release`): Dev one
- Rancher version: 2.7.1
- Kubernetes version (use `kubectl version`): N/A
- Cloud provider or hardware configuration: aarch64 boards/SoCs

**Comment by kkaempf** [comment]
Haven't seen any documentation about ISO booting on Raspberry Pi. Do you have any pointers ?

**Comment by ldevulder** [comment]
> Haven't seen any documentation about ISO booting on Raspberry Pi. Do you have any pointers ?

Not directly, it's not RPi specific. I do this through U-Boot.

**Comment by ldevulder** [comment]
I still need to redo some test with a "basic" SLE Micro, but it seems that the needed modules are missing in the default initramfs.

**Comment by kkaempf** [comment]
Every ARM board boots differently. I doubt there's a generic solution.

That said, there's ARM's [SystemReady](https://github.com/ARM-software/arm-systemready) initiative which we probably should focus on.

**Comment by kkaempf** [comment]
I'm closing this issue now as wontfix.

If you have a specific board which doesn't boot with the current [seed image](http://elemental.docs.rancher.com/next/quickstart#preparing-the-installation-seed-image), please open a separate issue with full logs.

**Comment by ldevulder** [comment]
> Every ARM board boots differently. I doubt there's a generic solution.

It's not an issue with the boot but with the missing of some kernel modules in SLE Micro initramfs.

> If you have a specific board which doesn't boot with the current [seed image](http://elemental.docs.rancher.com/next/quickstart#preparing-the-installation-seed-image), please open a separate issue with full logs.

In that case why closing this one?

**Comment by ldevulder** [comment]
> That said, there's ARM's [SystemReady](https://github.com/ARM-software/arm-systemready) initiative which we probably should focus on.

This will not resolve missing modules in initramfs ;-)

**Comment by kkaempf** [comment]
This one here is too unspecific ("Boot from ISO burned on USB key doesn't work on aarch64 boards") and has too little information to make it actionable. It's certainly not a generic aarch64 issue as we have plenty of successful installs on Raspberry Pi.

I'd recommend to open a separate issue and focus on
- one board (ideally with links to the board's documentation)
- a clear explanation of the problem, including logs
