### ISSUE TITLE
How to add swap space in elemental and Is it ok to do so

### ISSUE THREAD

**Issue by swetasgit** [rancher/elemental#647]
**Describe the solution you'd like:**
I would like to see swap space of 2gb when I run command "free" over elemental

**Anything else you would like to add:**
Currently I am getting Out of Memory issue on my elemental system.How can we add more swap space in elemental OS? Is it ok to do so?

**Environment:**

- Elemental release version : Kernel version is 5.14.21-150400.24.33
- Rancher version:2.6.9
- Kubernetes version (use `kubectl version`):1.24.4- k3s
- Cloud provider or hardware configuration: Hardware with 4 GB RAM

**Comment by agracey** [comment]
Is there a specific use-case you need this for? Kubernetes doesn't tend to like swap being enabled.

**Comment by swetasgit** [comment]
I understand that the issue is solved in the Kubernetes version after 1.22 as per below article:
https://kubernetes.io/blog/2021/08/09/run-nodes-with-swap-alpha/

As RAM of our hardware used for elemental deployment cannot be increased the team is asking for adding swap as they are getting "Out of Memory Error " while uploading some files in their application hosted over k3s.

But is it recommended by SUSE ?

**Comment by agracey** [comment]
I don't know explicitly but I wonder if there's a way to set it up in the cloud-config section. My initial thought would be to write a ["plan" ](https://elemental.docs.rancher.com/next/elemental-plans) that runs `swapon`.

**Comment by kkaempf** [comment]
> I don't know explicitly but I wonder if there's a way to set it up in the cloud-config section. My initial thought would be to write a ["plan" ](https://elemental.docs.rancher.com/next/elemental-plans) that runs `swapon`.

That could be used to enable file-based swap.

However, partition-based swap should be more efficient. This needs to be set in Elemental toolkit's [general configuration](https://rancher.github.io/elemental-toolkit/docs/customizing/general_configuration/)

**Comment by swetasgit** [comment]
Thanks @agracey @kkaempf for sharing the information.I will try this.

But is it ok to add swap space in elemental OS or do you see there is some challenges after adding swap?

**Comment by kkaempf** [comment]
The challenge is not with Elemental but with Kubernetes.
See https://serverfault.com/a/881518 for example.

**Comment by swetasgit** [comment]
Yes I understand that but as it has been solved starting Kubernetes 1.22.X . I wanted to know if SUSE still recommends for system running K3S as per the article one can face some performance issue.
https://kubernetes.io/blog/2021/08/09/run-nodes-with-swap-alpha/.

But I guess I will take my chances and try to create swapfile and observe it. Thanks for helping :)
