### ISSUE TITLE
k3s/rke2 is not deployed on the node (sporadic)

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental#667]
**What steps did you take and what happened:**
A node is successfully provisioned with Elemental but after the reboot `element-system-agent` doesn't connect to Rancher Manager and the configuration/cluster deployment is not done. For example the hostname is not set as well as the configured user/password.

It's something very sporadic that I have sometimes during manual testing and it also seems to happen from time to time on the CI ([here](https://github.com/rancher/elemental/actions/runs/4173563257/jobs/7228158013) for example).

**What did you expect to happen:**
The node to be added in the cluster.

**Anything else you would like to add:**
Find attached some logs from elemental-support and journalctl.
[journal.log](https://github.com/rancher/elemental/files/10733987/journal.log)
[rancher-8050-2023-02-14T150600Z.tar.gz](https://github.com/rancher/elemental/files/10733988/rancher-8050-2023-02-14T150600Z.tar.gz)

**Environment:**

- Elemental release version (use `cat /etc/os-release`): Dev version
- Rancher version: 2.7.1
- Kubernetes version (use `kubectl version`): N/A
- Cloud provider or hardware configuration: VM on KVM

**Comment by ldevulder** [comment]
I had the issue again on a 15 nodes cluster in the CI: https://github.com/rancher/elemental/actions/runs/4312380600/jobs/7523570584.
Some logs are available here: https://github.com/rancher/elemental/actions/runs/4312380600

Here also logs taken with `elemental-support`:
- from the problematic node: 
[node-63c74412-8c70-47e4-a98f-3e47c68de602-2023-03-02T103611Z.tar.gz](https://github.com/rancher/elemental/files/10870449/node-63c74412-8c70-47e4-a98f-3e47c68de602-2023-03-02T103611Z.tar.gz)

- from the 1st master node:
[node-38892689-eb92-4237-bc33-132ac2daa0c0-2023-03-02T103850Z.tar.gz](https://github.com/rancher/elemental/files/10870450/node-38892689-eb92-4237-bc33-132ac2daa0c0-2023-03-02T103850Z.tar.gz)

**Comment by kkaempf** [comment]
adding @moio

**Comment by kkaempf** [comment]
What are the hardware specs of the nodes, esp. the (speed of) storage used ?
Are you trying to deploy K3S or RKE2 ?

**Comment by kkaempf** [comment]
> Are you trying to deploy K3S or RKE2 ?

From the logs, I looks like RKE2

**Comment by ldevulder** [comment]
It fails on both, rke2 or k3s. As of the HW it fails on the CI runner with 16 cpus and 64GB of RAM and on my lab with half. SSD on my lab as well as on the CI runner.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kkaempf** [comment]
>     * from the problematic node:
>       [node-63c74412-8c70-47e4-a98f-3e47c68de602-2023-03-02T103611Z.tar.gz](https://github.com/rancher/elemental/files/10870449/node-63c74412-8c70-47e4-a98f-3e47c68de602-2023-03-02T103611Z.tar.gz)

The `rancher-system-agent.log` doesn't show any errors.

> Here what I have in the logs of the failing node:
> 
> ```
> Mar 02 10:34:50 node-63c74412-8c70-47e4-a98f-3e47c68de602 elemental-system-agent[1549]: time="2023-03-02T10:34:50Z" level=debug msg="[K8s] Processing secret node-63c74412-8c70-47e4-a98f-3e47c68de602 in namespace fleet-default at generation 0 with resource version 12854"
> ...
> ```

This is **elemental**-system-agent and the logs look normal. 🤷🏻‍♂️ 


Did you choose the wrong title ?! 😉

**Comment by kkaempf** [comment]
> 
>     * from the problematic node:
>       [node-63c74412-8c70-47e4-a98f-3e47c68de602-2023-03-02T103611Z.tar.gz](https://github.com/rancher/elemental/files/10870449/node-63c74412-8c70-47e4-a98f-3e47c68de602-2023-03-02T103611Z.tar.gz)

The `elemental-system-agent.log` shows the normal "waiting for Rancher cluster provisioning to kick in" cycle.

It looks more like a `MachineInventorySelector` mismatch and the node in question isn't considered as a valid cluster node.

**Comment by kkaempf** [comment]
How do the `MachineInventorySelector` and the `MachineInventory` of the "bad" node look like ?

**Comment by ldevulder** [comment]
> How do the `MachineInventorySelector` and the `MachineInventory` of the "bad" node look like ?

I've attached the log from `elemental-support`, it should be in no? (otherwise it could be a good improvement). The Rancher Manager/VMs are not up anymore, I will check next time I have this issue again. But on my lab as far as I remember the Inventory parts were correct.

> Did you choose the wrong title ?! wink

Maybe, in fact it's more the `elemental-system-agent` which looks to have issue. The log messages above are from it. Sometimes it stop after and sometimes I have these messages in loop. But as I don't know exactly the issue yes maybe the title is wrong ;-) Maybe better to name this issue `Cluster is not deployed on the node`? Or `k3s/rke2 is not deployed on the node`?

**Comment by ldevulder** [comment]
I have another cluster that had the issue.

Here the `MachineInventorySelector` and the `MachineInventory` of the good node:
```
$ kubectl -n fleet-default get MachineInventorySelector selector-master-cluster-rke2-s64pj -o yaml
apiVersion: elemental.cattle.io/v1beta1
kind: MachineInventorySelector
metadata:
  annotations:
    cluster.x-k8s.io/cloned-from-groupkind: MachineInventorySelectorTemplate.elemental.cattle.io
    cluster.x-k8s.io/cloned-from-name: selector-master-cluster-rke2
    machine.cluster.x-k8s.io/exclude-node-draining: "true"
  creationTimestamp: "2023-03-02T11:58:25Z"
  generation: 1
  labels:
    cattle.io/os: linux
    cluster.x-k8s.io/cluster-name: cluster-rke2
    cluster.x-k8s.io/control-plane: "true"
    cluster.x-k8s.io/deployment-name: cluster-rke2-pool-master-cluster-rke2
    machine-template-hash: "4203142204"
    rke.cattle.io/cluster-name: cluster-rke2
    rke.cattle.io/control-plane-role: "true"
    rke.cattle.io/etcd-role: "true"
    rke.cattle.io/rke-machine-pool-name: pool-master-cluster-rke2
    rke.cattle.io/worker-role: "true"
  name: selector-master-cluster-rke2-s64pj
  namespace: fleet-default
  ownerReferences:
  - apiVersion: cluster.x-k8s.io/v1beta1
    kind: MachineSet
    name: cluster-rke2-pool-master-cluster-rke2-8647586648
    uid: 16fe33f5-a4a9-488d-a547-bd664b184163
  - apiVersion: cluster.x-k8s.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: Machine
    name: cluster-rke2-pool-master-cluster-rke2-8647586648-gk49w
    uid: e2684f04-d7b1-41c8-9873-0b8faa5e54dd
  resourceVersion: "4768"
  uid: 162bae4f-13e8-44c2-a765-20a24278cfde
spec:
  selector:
    matchExpressions:
    - key: pool-type
      operator: In
      values:
      - master
    - key: cluster-id
      operator: In
      values:
      - just-a-dumb-value
      - id-cluster-rke2
status:
  bootstrapPlanChecksum: 1267158e91a8cbe49b521bee8f2913361df26f9b0c483fb2e07f71bb4e70b62f
  conditions:
  - lastTransitionTime: "2023-03-02T11:58:26Z"
    message: ""
    reason: SelectorReady
    status: "True"
    type: Ready
  machineInventoryRef:
    name: node-1e2d406b-fa8b-46ff-a2ee-9ac19474060a
  ready: true

$ kubectl -n fleet-default get MachineInventory node-1e2d406b-fa8b-46ff-a2ee-9ac19474060a -o yaml
apiVersion: elemental.cattle.io/v1beta1
kind: MachineInventory
metadata:
  annotations:
    elemental.cattle.io/registration-ip: 192.168.122.2
  creationTimestamp: "2023-03-02T11:56:48Z"
  finalizers:
  - machineinventory.elemental.cattle.io
  generation: 1
  labels:
    cluster-id: id-cluster-rke2
    pool-type: master
  name: node-1e2d406b-fa8b-46ff-a2ee-9ac19474060a
  namespace: fleet-default
  ownerReferences:
  - apiVersion: elemental.cattle.io/v1beta1
    controller: true
    kind: MachineInventorySelector
    name: selector-master-cluster-rke2-s64pj
    uid: 162bae4f-13e8-44c2-a765-20a24278cfde
  resourceVersion: "4991"
  uid: e828001a-80b0-48db-b6ba-97d4ccf09b8c
spec:
  tpmHash: 0572428932e6245959f2fd6c45f0ad86f094e4428771627670377f9aa1bd9a27
status:
  conditions:
  - lastTransitionTime: "2023-03-02T11:59:08Z"
    message: plan successfully applied
    reason: PlanSuccessfullyApplied
    status: "True"
    type: Ready
  plan:
    checksum: 1267158e91a8cbe49b521bee8f2913361df26f9b0c483fb2e07f71bb4e70b62f
    secretRef:
      name: node-1e2d406b-fa8b-46ff-a2ee-9ac19474060a
      namespace: fleet-default
    state: Applied
```

And here the `MachineInventorySelector` and the `MachineInventory` of the bad node:
```
$ kubectl -n fleet-default get MachineInventorySelector selector-master-cluster-rke2-zrt6h -o yaml
apiVersion: elemental.cattle.io/v1beta1
kind: MachineInventorySelector
metadata:
  annotations:
    cluster.x-k8s.io/cloned-from-groupkind: MachineInventorySelectorTemplate.elemental.cattle.io
    cluster.x-k8s.io/cloned-from-name: selector-master-cluster-rke2
    machine.cluster.x-k8s.io/exclude-node-draining: "true"
  creationTimestamp: "2023-03-02T11:58:25Z"
  generation: 1
  labels:
    cattle.io/os: linux
    cluster.x-k8s.io/cluster-name: cluster-rke2
    cluster.x-k8s.io/control-plane: "true"
    cluster.x-k8s.io/deployment-name: cluster-rke2-pool-master-cluster-rke2
    machine-template-hash: "4203142204"
    rke.cattle.io/cluster-name: cluster-rke2
    rke.cattle.io/control-plane-role: "true"
    rke.cattle.io/etcd-role: "true"
    rke.cattle.io/rke-machine-pool-name: pool-master-cluster-rke2
    rke.cattle.io/worker-role: "true"
  name: selector-master-cluster-rke2-zrt6h
  namespace: fleet-default
  ownerReferences:
  - apiVersion: cluster.x-k8s.io/v1beta1
    kind: MachineSet
    name: cluster-rke2-pool-master-cluster-rke2-8647586648
    uid: 16fe33f5-a4a9-488d-a547-bd664b184163
  - apiVersion: cluster.x-k8s.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: Machine
    name: cluster-rke2-pool-master-cluster-rke2-8647586648-q2z58
    uid: f913269f-9090-420a-b394-66c6fd647c25
  resourceVersion: "4772"
  uid: 9edc68b7-9b45-4484-b392-5473d93d304d
spec:
  selector:
    matchExpressions:
    - key: pool-type
      operator: In
      values:
      - master
    - key: cluster-id
      operator: In
      values:
      - just-a-dumb-value
      - id-cluster-rke2
status:
  bootstrapPlanChecksum: 35005c0d4bd9af61a795ed88eec85f80c65a5270995bcca25c95068219dcf209
  conditions:
  - lastTransitionTime: "2023-03-02T11:58:26Z"
    message: ""
    reason: SelectorReady
    status: "True"
    type: Ready
  machineInventoryRef:
    name: node-315cbd85-331f-4372-9a9b-fe2b32d70e03
  ready: true

$ kubectl -n fleet-default get MachineInventory node-315cbd85-331f-4372-9a9b-fe2b32d70e03 -o yaml
apiVersion: elemental.cattle.io/v1beta1
kind: MachineInventory
metadata:
  annotations:
    elemental.cattle.io/registration-ip: 192.168.122.3
  creationTimestamp: "2023-03-02T11:56:35Z"
  finalizers:
  - machineinventory.elemental.cattle.io
  generation: 1
  labels:
    cluster-id: id-cluster-rke2
    pool-type: master
  name: node-315cbd85-331f-4372-9a9b-fe2b32d70e03
  namespace: fleet-default
  ownerReferences:
  - apiVersion: elemental.cattle.io/v1beta1
    controller: true
    kind: MachineInventorySelector
    name: selector-master-cluster-rke2-zrt6h
    uid: 9edc68b7-9b45-4484-b392-5473d93d304d
  resourceVersion: "4989"
  uid: 3906fb2f-d2fa-40a7-947f-aa757aa185be
spec:
  tpmHash: ed751d263bfc655746d9899bbac76c56d433e702c3f6f84bbbe925d4e21cb271
status:
  conditions:
  - lastTransitionTime: "2023-03-02T11:59:08Z"
    message: plan successfully applied
    reason: PlanSuccessfullyApplied
    status: "True"
    type: Ready
  plan:
    checksum: 35005c0d4bd9af61a795ed88eec85f80c65a5270995bcca25c95068219dcf209
    secretRef:
      name: node-315cbd85-331f-4372-9a9b-fe2b32d70e03
      namespace: fleet-default
    state: Applied
```

**Comment by kkaempf** [comment]
> > How do the `MachineInventorySelector` and the `MachineInventory` of the "bad" node look like ?
> 
> I've attached the log from `elemental-support`, it should be in no?

No, it isn't. `elemental-support` collects client logs, the asked CRDs are part of the management cluster.

> Maybe better to name this issue `Cluster is not deployed on the node`? Or `k3s/rke2 is not deployed on the node`?

:+1:

**Comment by kkaempf** [comment]
We need logs from Rancher provisioning. I'm not convinced (yet ?) that this has anything to do with Elemental.
- does the MachineInventorySelector match (well, it does looking at the yamls above, but what does the management cluster think)
- does Rancher provisioning try to talk to elemental-system-agent (I don't think so) ?
- what's the node's status from a Rancher provisioning perspective ?
