### ISSUE TITLE
Adding Custom Kernel Module via RPM

### ISSUE THREAD

**Issue by swetasgit** [rancher/elemental#674]
Describe the solution you'd like:
I would like to install custom kernel modules via rpm

Anything else you would like to add:
I am trying to add our custom kernel module (abc.ko) by packaging it a rpm and installing it at the time of image creation as suggested in Remastering custom docker image section:
https://elemental.docs.rancher.com/customizing

I am able to add other default packages from rpm repository but kernel modules rpm. I observed the modules are getting copied and all the files are getting written but the commands like modprobe and depmode are not running. 
When I enable my custom elemental system with rpm installed in writable mode and just run depmode manually and reboot it . The new kernel modules get loaded .

I am able to load kernel module if I follow the hook architecture suggested in above document. But we want to have a structure for custom services and modules and so we want to use only rpm's rather than writing yaml file for each services.
Could you please suggest why kernel module are not loading or what can I do to load it as rpm?

I understand yaml are read after every reboot can I write a script which will run after reboot to load my kernel module. Will that work in elemental?
Environment:

Elemental release version : Kernel version is 5.14.21-150400.24.33
Rancher version:2.6.9
Kubernetes version (use kubectl version):1.24.4- k3s
Cloud provider or hardware configuration: Hardware with 4 GB RAM

**Comment by davidcassany** [comment]
@swetasgit I am not entirely sure I followed all the details. I assume you are adding additional RPMs to the OS by creating a new container image using a Dockerfile, then in this Dockerfile you install your additional RPMs. When you say commands like modprobe and depmod are not running I assume you mean within the Dockerfile, which makes sense as, at least `modprobe`, requires privileges and affects the host, not the image being build. Are you calling those commands within the RPM scriptlets or in a `RUN`  instruction within the Dockerfile? Is this raising errors during `docker build`? '_modprobe and depmode are not running_' meas they fail or they are omitted?

> When I enable my custom elemental system with rpm installed in writable mode and just run depmode manually and reboot it . The new kernel modules get loaded.

Well, I assume in that case `depmod` is writing the `modules.dep` and `modules.dep.bin` files at `/lib/modules/<kernel>/` folder. I am not that versed in `depmod`, but according to the behavior you explain probably `depmod` requires privileges as `modprobe` does. Probably you can easily verify if `depmod` requires privileges by running the built image with `docker run --rm -ti --entrypoint /bin/bash <yourimage>:<yourtag>` and on the shell verify if `depmod` can be executed. 

> I am able to load kernel module if I follow the hook architecture suggested in above document. But we want to have a structure for custom services and modules and so we want to use only rpm's rather than writing yaml file for each services.

In fact I'd say this is a good approach for your needs. Also, nothing forces you to write a yaml file for each service. You can also have a simple yaml file doing everything:

```yaml
stages:
  after-install-chroot:
  - commands: |
           # install additional repository for extra modules and services
           zypper addrepo --refresh <uri> <alias>
           zypper --non-interactive install <module_package> <service_package> ...
           
           # Run depmod
           depmod
           
           # Enable services
           systemctl enable <service>
 ```

**Comment by swetasgit** [comment]
Hello @davidcassany , thanks for your reply.

Are you calling those commands within the RPM scriptlets or in a RUN instruction within the Dockerfile? Is this raising errors during docker build? 'modprobe and depmode are not running' meas they fail or they are omitted?

I am running rpm install command while creating docker image and no I am not getting the error when I am running it as rpm:
RUN rpm -Uvh /tmp/*1.0-100.el7.x86_64.rpm

But when I tried running depmod or modprobe directly, I am getting below error:
 => ERROR [iqem-airgap iqem-airgap  7/15] RUN depmod                                                                                                                                                      0.4s
------
 > [iqem-airgap iqem-airgap  7/15] RUN depmod:
#0 0.298 depmod: ERROR: could not open directory /lib/modules/4.18.0-305.25.1.el8_4.x86_64: No such file or directory
#0 0.298 depmod: FATAL: could not search modules: No such file or directory
------
error: failed to solve: executor failed running [/bin/sh -c depmod]: exit code: 1
make: *** [Makefile:75: container-image] Error 1



The RPM I created for installing kernel module has the below spec file. I am running depmod not only in directly spec file but also calling a script do so:
[root@siedge SPECS]# cat kernelt.spec 
Name:           kernel-module
Version:        1.0
Release:        100.el7
Summary:        kernel module service
Group:          Unspecified
License:        oss
URL:            http://www.zzzz.com
Source0:        led-module-0.tar.gz
BuildRoot:      %(mktemp -ud %{_tmppath}/%{name}-%{version}-100-XXXXXX)

%description
Custom kernel module


%prep
%setup -q

%build

%install
install -m 0755 -d $RPM_BUILD_ROOT/lib/modules/kernel/
install -m 0755 -d $RPM_BUILD_ROOT/etc/modprobe.d/
install -m 0755 -d $RPM_BUILD_ROOT/etc/modules-load.d/
install -m 0755 -d $RPM_BUILD_ROOT/tmp/test/
install -m 0755 -d $RPM_BUILD_ROOT/lib/modules/<Kernel>/
install -m 0755 -d $RPM_BUILD_ROOT/lib/modules/<KERNEL>/kernel/

cp led-kernelpath.sh $RPM_BUILD_ROOT/tmp/test/
cp <Kernel module>.ko  $RPM_BUILD_ROOT/lib/modules/<KERNEL>/kernel/
cp 10-unsupported-modules.conf $RPM_BUILD_ROOT/etc/modprobe.d/
/usr/sbin/depmod


/usr/bin/echo <Kernel module name> > /etc/modules-load.d/<Kernel module name>.conf
/usr/bin/bash $RPM_BUILD_ROOT/tmp/test/led-kernelpath.sh
cp kernelmodule.conf $RPM_BUILD_ROOT/etc/modules-load.d/
/usr/sbin/depmod

%clean
rm -rf %{buildroot}


%files
%attr(777,root,root) /etc/modprobe.d/10-unsupported-modules.conf
%attr(777,root,root) /etc/modules-load.d/kernelmodule.conf
%attr(777,root,root) /lib/modules/<kernel name>t/kernel/<Kernel module>.ko
%config(noreplace) /tmp/test/led-kernelpath.sh 
/lib/modules/kernel/<Kernel module>.ko


%post
/usr/sbin/depmod
/usr/sbin/modprobe <kernel-module> --allow-unsupported


%changelog



You can also have a simple yaml file doing everything:

I have tried this approach that you suggested but as we have multiple teams developing multiple services for elemental the simple Yaml get cluttered with many service details. 
This is the YAML file that I used and worked for me but I wanted to move from this approach and add everything as rpm in Docker image creation:

#Executed on system startup
# FIXME: Build modules specifically
name: "Kernel  module"
stages:
 after-install-chroot:
  - name: "Install module"
    commands:
    - |
      export MOULDES_PATH=/lib/modules/$(uname -r)/kernel/
      cp /lib/modules/kernel/* ${MOULDES_PATH}
      chmod 777 ${MOULDES_PATH}<Kernelmodule>.ko ${MOULDES_PATH}<Kernelmodule>.ko
      cp /etc/modprobe.d/10-unsupported-modules.conf /etc/modprobe.d/
      chmod 777 /etc/modprobe.d/10-unsupported-modules.conf
      sudo depmod
      sudo modprobe <kernelmodule> --allow-unsupported
      cp /etc/modules-load.d/<kernelmodule>.conf /etc/modules-load.d/
      chmod 777 /etc/modules-load.d/<kernelmodule>.conf


Do you think this only rpm approach work for installing new kernel module and services will work with elemental?

**Comment by davidcassany** [comment]
Hi @swetasgit I am really sorry for the late replay, got sidetracked by other duties and nearly forgot to ansawer.

Regarding you issue

> ## But when I tried running depmod or modprobe directly, I am getting below error:
> => ERROR [iqem-airgap iqem-airgap 7/15] RUN depmod 0.4s
> 
> > [iqem-airgap iqem-airgap  7/15] RUN depmod:
> > #0 0.298 depmod: ERROR: could not open directory /lib/modules/4.18.0-305.25.1.el8_4.x86_64: No such file or directory
> > #0 0.298 depmod: FATAL: could not search modules: No such file or directory

This seams to be a reasonable issue. I am not really familiar with `depmod` logic, but I'd assume it tries to process the modules for the current kernel (`uname -r`), which is the *host* kernel if running in a container. Note the kernel is shared with host in containers, hence running kernel operations in such a context requires special care and tends to be tricky. `man depmod` makes me think that making use of `--basedir basedir` flag might help you in this particular case, so you add the base dir if the actual elemental kernel modules folder. I bet `/lib/modules/4.18.0-305.25.1.el8_4.x86_64` is the kernel modules folder of your building host, not elemental, see the kernel version mismatch. 

From depmod man pages:

```
depmod creates a list of module dependencies by reading each module under /lib/modules/version
and determining what symbols it exports and what symbols it needs. By default, this list is written
to modules.dep, and a binary hashed version named modules.dep.bin, in the same directory.
```
I assume `/lib/modules/version` translates to `/lib/modules/$(uname -r)`.

> I have tried this approach that you suggested but as we have multiple teams developing multiple services for elemental the simple Yaml get cluttered with many service details.

Out of curiosity, could you share a bit of your specific use case of Elemental? Mostly asking because Elemental is a young project and knowing about the use cases out there is quite relevant to us to better support and enhance it where it makes sense and actual impact.

> This is the YAML file that I used and worked for me but I wanted to move from this approach and add everything as rpm in Docker image creation:

Right the yaml file you shared I think is good for the installation, but I believe you missed upgrades and reset (in case they are relevant to you). So the given hook will only be executed during the installation. Probably you can think of a different approach and just configure the module in the install/upgrade/reset hooks, so you install the RPM in Dockerfile where there is no depmode call or similar to activate it, but you have few hooks to do so as:

```yaml
name: "Kernel module"
stages:
  after-install-chroot:
  - &setupmodules
    name: "Install module"
    commands: |
        depmod --basedir <folder of installed/upgrade/reset kernel>
        # and any other command you may need
  after-upgrade-chroot:
  - <<: *setupmodules
  after-reset-chroot:
  - <<: *setupmodules
```

**Comment by swetasgit** [comment]
@davidcassany Thanks for answering my queries. I will try to implement as you suggested.
