### ISSUE TITLE
e2e: Make elemental-operator version configurable

### ISSUE THREAD

**Issue by juadk** [rancher/elemental#686]
In our e2e test, we always [install elemental-operator dev version](https://github.com/rancher/elemental/blob/main/tests/e2e/install_test.go#L292) .
If we want to install stable version, we [upgrade the helm deployment ](https://github.com/rancher/elemental/blob/main/tests/e2e/install_test.go#L304-L308). 
It looks weird to install dev and then update to stable instead of directly installing stable version.

**Comment by ldevulder** [comment]
Related to https://github.com/rancher/elemental-operator/issues/329.
