### ISSUE TITLE
e2e: Check upgrade happens without downtime

### ISSUE THREAD

**Issue by juadk** [rancher/elemental#700]
Follow-up of https://github.com/rancher/elemental/issues/651

We should verify the upgrade happens without down time as fleet should orchestrate the upgrade to make it possible.
The idea is to deploy an application in the cluster and check its availability while upgrading the whole cluster.

**Comment by ldevulder** [comment]
Note: add the steps to deploy a small example application in the docs.

**Comment by ldevulder** [comment]
Test will be done in K3s client only for now. Easier to do as K3s already has a loadbalancer configured by default.
