### ISSUE TITLE
Boot assessment behavior on upgrades

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental#708]
This issue is to agree and eventually fix the boot assessment behavior on upgrades. The problem raises when rebooting during an upgrade and it fails to boot for some reason. In that case it boots the fallback partition. The question is what is expected to happen next. Currently system-upgrade-controller's plan will kick in again and try to upgrade, since there will be version mismatch it is expected to run again the same upgrade but from the fallback partition.

**Comment by frelon** [comment]
Another interesting issue i ran into when trying to upgrade to an image that is missing the `/usr/sbin/suc-upgrade` script:

![image](https://user-images.githubusercontent.com/10380995/229495455-eae84b84-a1fd-4b6b-9692-b594dd25d7a1.png)

**Comment by davidcassany** [comment]
> Another interesting issue i ran into when trying to upgrade to an image that is missing the `/usr/sbin/suc-upgrade` script:
> 
> ![image](https://user-images.githubusercontent.com/10380995/229495455-eae84b84-a1fd-4b6b-9692-b594dd25d7a1.png)
> 
> EDIT although removing the `ManagedOSImage` resource seems to clean it up...

mmm interesting, I guess upgrade failures are not really tracked neither monitored anywhere and the system just keeps trying... this another interesting issue, what happens if the upgrade job does not even reach the reboot stage.

**Comment by kkaempf** [comment]
We might not be able to solve each and every problem automatically.

It would be good to capture all these error scenarios in a "what if" section of the documentation.

**Comment by agracey** [comment]
Would it make sense to validate a few basics (like /boot existing) after pulling the image but before rebooting? That way you can't accidentally try and boot into a non-bootable image

**Comment by frelon** [comment]
> We might not be able to solve each and every problem automatically.
> 
> 
> 
> It would be good to capture all these error scenarios in a "what if" section of the documentation.

Absolutely, I will run some more tests to see what scenarios we have and then try to document/solve them accordingly!

**Comment by frelon** [comment]
> Would it make sense to validate a few basics (like /boot existing) after pulling the image but before rebooting? That way you can't accidentally try and boot into a non-bootable image

Good idea! Will have a look to see where we could implement this!
