### ISSUE TITLE
Rearrange OBS projects to match IBS setup

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental#711]
Rearrange OBS repositories (`Dev`, `Stable`, `Staging`) to match IBS setup. We should be consistent and have the same setup everywhere for the sake of clarity and maintainability.

See `Devel:Elemental:Teal53` project in IBS where all packages, containers and images are built within the same project under the repositories  `standard`, `charts`, `containers`, `images`. 

Also with this setup we could even think on attempting a next step automation goal, building a fully functional elemental artifacts in OBS based on PRs, allowing developers to have a full build ready to be deployed (images in the registry and helm charts rebuild accordingly) by just submitting a PR to github.

**Comment by davidcassany** [comment]
This is a breaking change to all our URLs and image references. Should be done a while after we are publishing in IBS through maintenance.  Marking as blocked

**Comment by kkaempf** [comment]
Should probably wait for Teal54 ?!

@agracey - this needs offline discussion

**Comment by agracey** [comment]
We should document the IBS builds as the primary images.

**Comment by davidcassany** [comment]
Going to be applied as part of #815
