### ISSUE TITLE
Include utilities for encrypted volumes and enable longhorn encrypted storage

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental#749]
**Describe the solution you'd like:**
Enable encrypted longhorn storage. For this luks utilities such as cryptsetup should be included and validated.

**Anything else you would like to add:**
Elemental-teal image does not include luks, hence IMHO this should be included by default as managing encrypted volumes should be possible with elemental-teal without having to relay on the inclusion of additional software at installation time.

**Environment:**

Luks is missing for all versions.

- Elemental release version (use `cat /etc/os-release`): 
- Rancher version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:

**Comment by kkaempf** [comment]
Is `cryptsetup-luks` part of SLE Micro ? 🤔

**Comment by agracey** [comment]
From Daniel: Looks like we only have cryptsetup but it should contain the luks-parts

**Comment by davidcassany** [comment]
By simply adding cryptsetup package within the node-image and following the https://longhorn.io/docs/1.4.1/advanced-resources/security/volume-encryption/ example I succeeded to set a longhorn volume. I believe we just need to require the package within the base image and we are done.

**Comment by kkaempf** [comment]
Tracked as SMO-212 now.
