### ISSUE TITLE
e2e: Automation to test cloud-init setup for seedimage

### ISSUE THREAD

**Issue by juadk** [rancher/elemental#771]
Follow-up of https://github.com/rancher/elemental/issues/764

We tested it manually and we should be able to automate it after the next release.

**Comment by ldevulder** [comment]
Add this test in CLI. First we have to use seedimage in CLI to generate the ISO.

**Comment by juadk** [comment]
Blocked by https://github.com/rancher/elemental-operator/issues/467

**Comment by juadk** [comment]
SeedImage is now used to build ISO in the CI https://github.com/rancher/elemental/pull/873 but I still have to check automatically if the SeedImage cloud-config works. It will avoid hitting https://github.com/rancher/elemental-operator/issues/467 again. CI will spot it!

**Comment by juadk** [comment]
I'm almost done, I have a last issue with virt-install return code: https://github.com/rancher/elemental/actions/runs/5356753229/jobs/9716686688
