### ISSUE TITLE
Unable to deploy new node after restore of Rancher Manager resources

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental#776]
**What steps did you take and what happened:**
- Installation of Rancher Manager 2.7.8-rcX
- Installation of Backup/Restore Operator v3.1.0-rc5 (see [here](https://github.com/rancher/backup-restore-operator))
- Installation of Elemental Operator Dev
- Configuration of a basic K3s cluster with Elemental (ISO from Dev)
- Do a backup of the whole cluster (simple test on local, see [here](https://ranchermanager.docs.rancher.com/pages-for-subheaders/backup-restore-and-disaster-recovery) for more information)
- Restore from the backup
- Try to deploy a new node on the existing K3s cluster: the node bootstrapping will fail with this error in the node logs:
```
Connect to https://k3s-rancher.work.lan.greatancien.eu/elemental/registration/vqwnmzcn7sm9wczp2lvqv2llfbksbrxs6ssmhmlq4tq79lhhqhngtf
Using TPM Auth with Hash f78b5541be0d0c81b93af6096eec1333aa5b4c99339a882b41d84e0c87952402 to dial wss://k3s-rancher.work.lan.greatancien.eu/elemental/registration/vqwnmzcn7sm9wczp2lvqv2llfbksbrxs6ssmhmlq4tq79lhhqhngtf
Local Address: 192.168.4.30:52890
Start TPM authentication
TPM authentication completed
elemental-register protocol version: 9
Negotiated protocol version: 9
Send SMBIOS data
Send system data
Send elemental annotations
sending local IP: 192.168.4.30
Get elemental configuration
Got configuration response: Error
failed to register machine inventory: no secrets associated to the fleet-default/machine-registration-master-cluster-k3s service account
```

**What did you expect to happen:**
- Be able to provision new node after a restore.

**Anything else you would like to add:**
N/A

**Environment:**
- Elemental release version (use `cat /etc/os-release`): 1.1.3 (Dev version from OBS)
- Rancher version: 2.7.2-rc8
- Kubernetes version (use `kubectl version`): v1.24.10+k3s1
- Cloud provider or hardware configuration: Virtual Machine on KVM

Please find attached the logs from elemental-support as well as the backup done with Rancher Manager:
[rancher-20845-2023-04-04T132803Z.tar.gz](https://github.com/rancher/elemental/files/11150351/rancher-20845-2023-04-04T132803Z.tar.gz)
[elemental-backup-05a63f5a-877d-4aa5-bb03-9950d1dc3edf-2023-04-04T11-54-49Z.tar.gz](https://github.com/rancher/elemental/files/11150355/elemental-backup-05a63f5a-877d-4aa5-bb03-9950d1dc3edf-2023-04-04T11-54-49Z.tar.gz)

**Comment by davidcassany** [comment]
Ok, managed to easily reproduce the issue, for some reason looks like the secret created [here](https://github.com/rancher/elemental-operator/blob/f8c584dfaafb875deb6725ba0fe7a21ee495f890/controllers/machineregistration_controller.go#L252-L268) is not part of the backup.

Need to run further tests, however in my environment if I restore on top of the just created backup all resources are there but the machine registration still fails, I don't really see how the secret changes after restoration, but in any case this secret would not have been recreated if lost for some reason by restoring the backup.

**Comment by fgiudici** [comment]
> Ok, managed to easily reproduce the issue, for some reason looks like the secret created [here](https://github.com/rancher/elemental-operator/blob/f8c584dfaafb875deb6725ba0fe7a21ee495f890/controllers/machineregistration_controller.go#L252-L268) is not part of the backup.
> 
> Need to run further tests, however in my environment if I restore on top of the just created backup all resources are there but the machine registration still fails, I don't really see how the secret changes after restoration, but in any case this secret would not have been recreated if lost for some reason by restoring the backup.

Good catch!
We added the Secret creation to comply with Kubernetes v1.24 change: the ServiceAccount previously generated an owned Secret automatically. From K8s 1.24 that happened no more, so we added the Secret generation there. Guess also for the Backup, restoring a ServiceAccount would have generated an associated secret in K8s < 1.24... still, it would had been different, so how could that work? 🤔

**Comment by davidcassany** [comment]
> Good catch! We added the Secret creation to comply with Kubernetes v1.24 change: the ServiceAccount previously generated an owned Secret automatically. From K8s 1.24 that happened no more, so we added the Secret generation there. Guess also for the Backup, restoring a ServiceAccount would have generated an associated secret in K8s < 1.24... still, it would had been different, so how could that work? thinking

Interesting 🤔 Gonna try to figure out equivalent changes in backup-restore controller regarding service account secrets.

So far I noticed a couple of anomalies that probably are related with the above:
* For some reason the backup does not include the secret even I verified it matches the criteria to be included (at first I thought it would be simple mismatch on the criteria defined in https://github.com/rancher/backup-restore-operator/commit/52640728ca972d03e3b9861bcf28d40cc6819ada) 🤷🏽‍♂️ 
* I manually hacked a backup tarball to add the missing secret, I checked it was restored in backup-restore pods logs, however the service account for some odd reason swallowed the secrets list of the service account while restoring. So after restoring the service account had not secrets associated. Patch the service account to refer to the already existing secret fixed the issue.

Feels like we might be missing some details about how backup-restore manages the service account secrets.

**Comment by davidcassany** [comment]
Indeed I believe we are hitting a consequence of https://github.com/rancher/backup-restore-operator/pull/138, still trying to figure out how those secrets and related service accounts should be stored and restored.

**Comment by davidcassany** [comment]
@ldevulder before completely closing this issue I'd like you give it another shot whenever you have time, so we also check this fixes your test case.

**Comment by davidcassany** [comment]
Missing documentation for the backup and restore of resources created before the patch.

**Comment by ldevulder** [comment]
@davidcassany it still fails with this error:
```
Jul 12 09:12:21 rancher-1358 elemental-register[1414]: E0712 09:12:21.847635    1414 log.go:70] failed to register machine inventory: %!w(*errors.fundamental=&{failed to get secret: secrets "machine-registration-worker-cluster-k3s-token" not found 0xc000012a50})
```

It's a different error, so we are progressing! :smile: 

Full log `elemental-register` log:
```
Jul 12 09:00:23 rancher-1358 systemd[1]: Starting Elemental Register...
Jul 12 09:00:24 rancher-1358 elemental-register[1414]: I0712 09:00:24.119314    1414 log.go:38] Debug logs enabled
Jul 12 09:00:24 rancher-1358 elemental-register[1414]: I0712 09:00:24.119446    1414 log.go:42] Register version 1.2.5, commit 989851fa, commit date 20230711
Jul 12 09:00:24 rancher-1358 elemental-register[1414]: I0712 09:00:24.119459    1414 log.go:50] Using live configuration in directory: /run/initramfs/live
Jul 12 09:00:24 rancher-1358 elemental-register[1414]: I0712 09:00:24.119465    1414 log.go:50] scanning config path /run/initramfs/live
Jul 12 09:00:24 rancher-1358 elemental-register[1414]: I0712 09:00:24.120190    1414 log.go:42] reading config file livecd-cloud-config.yaml
Jul 12 09:00:24 rancher-1358 elemental-register[1414]: I0712 09:00:24.120366    1414 log.go:50] input config:
Jul 12 09:00:24 rancher-1358 elemental-register[1414]: v1beta1.Config{
Jul 12 09:00:24 rancher-1358 elemental-register[1414]:   Elemental: v1beta1.Elemental{
Jul 12 09:00:24 rancher-1358 elemental-register[1414]:     Install: v1beta1.Install{
Jul 12 09:00:24 rancher-1358 elemental-register[1414]:       Firmware: "",
Jul 12 09:00:24 rancher-1358 elemental-register[1414]:       Device: "",
Jul 12 09:00:24 rancher-1358 elemental-register[1414]:       NoFormat: false,
Jul 12 09:00:24 rancher-1358 elemental-register[1414]:       ConfigURLs: nil,
Jul 12 09:00:24 rancher-1358 elemental-register[1414]:       ISO: "",
Jul 12 09:00:24 rancher-1358 elemental-register[1414]:       SystemURI: "",
Jul 12 09:00:24 rancher-1358 elemental-register[1414]:       Debug: false,
Jul 12 09:00:24 rancher-1358 elemental-register[1414]:       TTY: "",
Jul 12 09:00:24 rancher-1358 elemental-register[1414]:       PowerOff: false,
Jul 12 09:00:24 rancher-1358 elemental-register[1414]:       Reboot: false,
Jul 12 09:00:24 rancher-1358 elemental-register[1414]:       EjectCD: false,
Jul 12 09:00:24 rancher-1358 elemental-register[1414]:       DisableBootEntry: false,
Jul 12 09:00:24 rancher-1358 elemental-register[1414]:       ConfigDir: "",
Jul 12 09:00:24 rancher-1358 elemental-register[1414]:     },
Jul 12 09:00:24 rancher-1358 elemental-register[1414]:     Registration: v1beta1.Registration{
Jul 12 09:00:24 rancher-1358 elemental-register[1414]:       URL: "https://189.202.134.34.bc.googleusercontent.com/elemental/registration/h57vwlrpj5ks9mc7hkd5xlr4mt8wsnj2n8tt42px4mjxg6qxnkl5k4",
Jul 12 09:00:24 rancher-1358 elemental-register[1414]:       CACert: "-----BEGIN CERTIFICATE-----\nMIIBvjCCAWOgAwIBAgIBADAKBggqhkjOPQQDAjBGMRwwGgYDVQQKExNkeW5hbWlj\nbGlzdGVuZXItb3JnMSYwJAYDVQQDDB1keW5hbWljbGlzdGVuZXItY2FAMTY4OTE1\nMTA5ODAeFw0yMzA3MTIwODM4MThaFw0zMzA3MDkwODM4MThaMEYxHDAaBgNVBAoT\nE2R5bmFtaWNsaXN0ZW5lci1vcmcxJjAkBgNVBAMMHWR5bmFtaWNsaXN0ZW5lci1j\nYUAxNjg5MTUxMDk4MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE2W1HO5GO0sZL\nTO7e8clwuidp+hQXgYVPs/5vEqhMuITvJ+5clAuonZQH1BNFdZ9MTnj6CEioaacQ\nSD/i4QcviqNCMEAwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYD\nVR0OBBYEFB6IrO8u3yuZjYDhNmaQQXRzj7udMAoGCCqGSM49BAMCA0kAMEYCIQD7\nwK4/3QqnpxFmBUE8EB3bIjOyYRO1PJnmMkg05E+ymgIhAK2YhuVOtavXKUJ9RnXt\nC3Iqb5pf0ipkY3Jr04uS39sH\n-----END CERTIFICATE-----",
Jul 12 09:00:24 rancher-1358 elemental-register[1414]:       EmulateTPM: false,
Jul 12 09:00:24 rancher-1358 elemental-register[1414]:       EmulatedTPMSeed: -1,
Jul 12 09:00:24 rancher-1358 elemental-register[1414]:       NoSMBIOS: false,
Jul 12 09:00:24 rancher-1358 elemental-register[1414]:       Auth: "tpm",
Jul 12 09:00:24 rancher-1358 elemental-register[1414]:     },
Jul 12 09:00:24 rancher-1358 elemental-register[1414]:     SystemAgent: v1beta1.SystemAgent{
Jul 12 09:00:24 rancher-1358 elemental-register[1414]:       URL: "",
Jul 12 09:00:24 rancher-1358 elemental-register[1414]:       Token: "",
Jul 12 09:00:24 rancher-1358 elemental-register[1414]:       SecretName: "",
Jul 12 09:00:24 rancher-1358 elemental-register[1414]:       SecretNamespace: "",
Jul 12 09:00:24 rancher-1358 elemental-register[1414]:     },
Jul 12 09:00:24 rancher-1358 elemental-register[1414]:   },
Jul 12 09:00:24 rancher-1358 elemental-register[1414]:   CloudConfig: map[string]runtime.RawExtension(nil),
Jul 12 09:00:24 rancher-1358 elemental-register[1414]: }
Jul 12 09:00:24 rancher-1358 elemental-register[1414]: I0712 09:00:24.120417    1414 log.go:58] Attempting to perform first time registration...
Jul 12 09:00:24 rancher-1358 elemental-register[1414]: I0712 09:00:24.120422    1414 log.go:42] Connect to https://189.202.134.34.bc.googleusercontent.com/elemental/registration/h57vwlrpj5ks9mc7hkd5xlr4mt8wsnj2n8tt42px4mjxg6qxnkl5k4
Jul 12 09:00:24 rancher-1358 elemental-register[1414]: I0712 09:00:24.360458    1414 log.go:42] Using TPM Auth with Hash 880270fbce3a30e88282c6006ca516dc6c309e6e3c6a6d645eb97bab4069c6d3 to dial wss://189.202.134.34.bc.googleusercontent.com/elemental/registration/h57vwlrpj5ks9mc7hkd5xlr4mt8wsnj2n8tt42px4mjxg6qxnkl5k4
Jul 12 09:00:24 rancher-1358 elemental-register[1414]: I0712 09:00:24.379243    1414 log.go:42] Local Address: 192.168.122.6:53920
Jul 12 09:00:24 rancher-1358 elemental-register[1414]: I0712 09:00:24.379300    1414 log.go:50] Start TPM authentication
Jul 12 09:00:24 rancher-1358 elemental-register[1414]: I0712 09:00:24.525927    1414 log.go:42] TPM authentication completed
Jul 12 09:00:24 rancher-1358 elemental-register[1414]: I0712 09:00:24.525968    1414 log.go:50] elemental-register protocol version: 10
Jul 12 09:00:24 rancher-1358 elemental-register[1414]: I0712 09:00:24.526704    1414 log.go:42] Negotiated protocol version: 10
Jul 12 09:00:24 rancher-1358 elemental-register[1414]: I0712 09:00:24.526732    1414 log.go:42] Send SMBIOS data
Jul 12 09:00:24 rancher-1358 elemental-register[1414]: I0712 09:00:24.540793    1414 log.go:42] Send system data
Jul 12 09:00:24 rancher-1358 elemental-register[1414]: I0712 09:00:24.555053    1414 log.go:46] Send elemental annotations
Jul 12 09:00:24 rancher-1358 elemental-register[1414]: I0712 09:00:24.555087    1414 log.go:50] sending local IP: 192.168.122.6
Jul 12 09:00:24 rancher-1358 elemental-register[1414]: I0712 09:00:24.555785    1414 log.go:46] Get elemental configuration
Jul 12 09:00:24 rancher-1358 elemental-register[1414]: I0712 09:00:24.565388    1414 log.go:50] Got configuration response: Error
Jul 12 09:00:24 rancher-1358 elemental-register[1414]: E0712 09:00:24.565586    1414 log.go:70] failed to register machine inventory: %!w(*errors.fundamental=&{failed to get secret: secrets "machine-registration-worker-cluster-k3s-token" not found 0xc0003af680})
```

**Comment by ldevulder** [comment]
So I retested manually and I can confirm that:
- restore works well if no resources are deleted
- restore fails if the MachineRegistration is deleted, with the error describe previously.

Please find attached the backup file I used.
[elemental-backup-144fcdaa-611a-49b7-86c9-39d4b486873c-2023-07-13T12-58-45Z.tar.gz](https://github.com/rancher/elemental/files/12040164/elemental-backup-144fcdaa-611a-49b7-86c9-39d4b486873c-2023-07-13T12-58-45Z.tar.gz)

**Comment by davidcassany** [comment]
This is weird, as the error claims the `machine-registration-worker-cluster-k3s-token` is not found, but this clearly included within the backup tarball, so it should have been also restored. Gonna try to reproduce it locally again, thanks for the valuable information.

**Comment by kkaempf** [comment]
Given that restore simply replays the resources (one by one), could it be an ordering problem ?
