### ISSUE TITLE
Update elemental-system-agent to 0.3.2

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental#781]
Current [elemental-system-agent](https://build.opensuse.org/package/show/isv:Rancher:Elemental:Dev/elemental-system-agent) (v0.3.1) is behind the [latest upstream](https://github.com/rancher/system-agent/releases) (v0.3.2)

**Comment by davidcassany** [comment]
@kkaempf already did it https://build.opensuse.org/package/show/isv:Rancher:Elemental:Stable/elemental-system-agent :+1:
