### ISSUE TITLE
node stuck uncordoned after upgrade

### ISSUE THREAD

**Issue by abonillabeeche** [rancher/elemental#793]
**What steps did you take and what happened:**
Upgraded a cluster, image was applied, new version visible in /etc/*-release but node remains uncordoned.

**What did you expect to happen:**
Node back to Ready

**Anything else you would like to add:**
https://paste.opensuse.org/pastes/5e5eb1ef53b3

`time="2023-04-18T15:27:43Z" level=error msg="error syncing 'cattle-system/os-upgrader-all-clusters': handler system-upgrade-controller: secrets \"os-upgrader-all-clusters\" not found, handler system-upgrade-controller: failed to create cattle-system/apply-os-upgrader-all-clusters-on-m-d55602cg90612-with- batch/v1, Kind=Job for system-upgrade-controller cattle-system/os-upgrader-all-clusters: Job.batch \"apply-os-upgrader-all-clusters-on-m-d55602cg90612-with-\" is invalid: [metadata.name: Invalid value: \"apply-os-upgrader-all-clusters-on-m-d55602cg90612-with-\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.template.labels: Invalid value: \"apply-os-upgrader-all-clusters-on-m-d55602cg90612-with-\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')], requeuing"
`

**Environment:**

- Elemental release version (use `cat /etc/os-release`):
- Rancher version: 2.7.2
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:

**Comment by kkaempf** [comment]
Please run `elemental-support` on the node and attach its output.

**Comment by abonillabeeche** [comment]
@kkaempf Julien said
_looks like the name apply-os-upgrader-all-clusters-on-m-d55602cg90611-with-5c-22fbn is truncated to apply-os-upgrader-all-clusters-on-m-d55602cg90611-with- and then complain because it ends with -_
do we want a separate issue for that?

**Comment by abonillabeeche** [comment]
[m-d55602cg90611-2023-04-19T133430Z.tar.gz](https://github.com/rancher/elemental/files/11273651/m-d55602cg90611-2023-04-19T133430Z.tar.gz)

**Comment by kkaempf** [comment]
> @kkaempf Julien said _looks like the name apply-os-upgrader-all-clusters-on-m-d55602cg90611-with-5c-22fbn is truncated to apply-os-upgrader-all-clusters-on-m-d55602cg90611-with- and then complain because it ends with -_ do we want a separate issue for that?

If this turns out to be a/the problem 😉

**Comment by agracey** [comment]
So many random letters creating length/truncation issues... 

Is there a way with kube-builder to flag the truncation before it happens? (Is this even coming from kube-builder? Or is this issue actually in wranger?)

**Comment by juadk** [comment]
I didn't manage to reproduce it with my fresh Elemental stack, there are the components and versions used:
- Upstream cluster to host RM: `v1.24.11+k3s1`
- Rancher version: `2.7.2`
- Elemental operator: `latest stable`
- Elemental ISO: `https://updates.suse.com/SUSE/Products/ElementalTeal/5.3/x86_64/iso/elemental-teal.x86_64-1.1.4-GM.iso`
- Elemental UI extension: `1.1.0`
- Downstream clusters: `v1.25.7+k3s1` and `v1.25.7+rke2r1`

I created 3 one-node clusters and used the same name structure (`m-d55602cg90612`, `m-d55602cg90613` and `m-d55602cg90614`). Installed with IBS artifacts and then I created an update group all-clusters pointing to [registry.opensuse.org/isv/rancher/elemental/dev/teal53/15.4/rancher/elemental-teal/5.3](http://registry.opensuse.org/isv/rancher/elemental/dev/teal53/15.4/rancher/elemental-teal/5.3)
All clusters were updated as expected.
![image](https://user-images.githubusercontent.com/6025636/234294171-8974460f-55b7-499a-8825-9401ed07f14f.png)

![image](https://user-images.githubusercontent.com/6025636/234294206-5672be71-d95b-45bc-8b1f-1647ef6d6b76.png)
