### ISSUE TITLE
Release node-image-rt

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental#806]
**Describe the solution you'd like:**
[A clear and concise description of what you want to happen.]

Advance `node-image-rt` to `Stable`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Elemental release version (use `cat /etc/os-release`):
- Rancher version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:

**Comment by davidcassany** [comment]
`node-image-rt` is already released in `Stable`.  

The channel is not yet updated as I doubt about adding this image there. In staging the channel is already there and adding it in Rancher looks like


![Image](https://user-images.githubusercontent.com/6428768/234607654-2acb417f-c545-4b4e-99b8-7202d2f60cad.png)

I am not sure if this will turn to be confusing as long as we keep adding versions. I wonder if shouldn't we have a devoted channel for rt versions. I doubt users will keep changing from one to the other, so who ever needs the `rt` versions will only use `rt` and vice versa. I doubt there is much value on adding both in the same list. Moreover nothing prevents setting two different channels if want all them to appear on the list. The only counter part is some more manual work on updating the channel for each _flavour_ in each release, I'd say it is reasonable.

@kkaempf @agracey any thoughts about it. Do you agree on having a separate channel for rt? so by default rt versions are not listed unless the specific channel is added.

**Comment by agracey** [comment]
> I doubt users will keep changing from one to the other

I could definitely see people doing this earlier in the development lifecycle to get easier A/B tests. But I think having the options in two different channels makes more sense and any customer needing to switch between can set up both channels.

**Comment by davidcassany** [comment]
Channel is also published in stable
