### ISSUE TITLE
e2e: add openQA test for QAM

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental#808]
Do a quick and simple boot test of the ISO in openQA to validate latest version of SLE Micro packages in Elemental.

**Comment by kkaempf** [comment]
This is esp. important to automate releases and verifying that SLE Micro updates don't break Elemental.

**Comment by ldevulder** [comment]
PR created in openQA tests repo: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17122.

**Comment by ldevulder** [comment]
Set it as `blocked` until the PR/MR are merged (still under review).

**Comment by ldevulder** [comment]
PRs/MRs have been merged.
