### ISSUE TITLE
List/document available Elemental ISOs from IBS

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental#831]
In IBS releases ISO URL won't be browse-able, so I am wondering how should we provide the ISOs URLs. Despite delivering the ISOs wrapped in container in the future I do believe it is relevant having a downloadable ISO, not only for compliance purposes but also for testing/experimenting (us and eventual customers).

Should we list the URLs in docs? include the release URL within the github release notes?

**Comment by fgiudici** [comment]
Wondering if it is the right time to have a proper domain for the elemental project 😅 
Docs and github releases page look like good options 👍🏼

**Comment by davidcassany** [comment]
Closing as this should be part of the release notes, tracked in rancher/elemental-docs#165
