### ISSUE TITLE
Rancher and k3s is not getting installed in Elemental

### ISSUE THREAD

**Issue by divyashukla25** [rancher/elemental#833]
Hi,

I have build the elemental iso by using below documents.
https://elemental.docs.rancher.com/rancher-vmware
https://elemental.docs.rancher.com/quickstart-cli

But, when created the elemental server with above created ISO. k3s services are not present. This services are not getting installed.

<img width="626" alt="image" src="https://github.com/rancher/elemental/assets/112463911/4d48df43-ab86-425d-aaed-9adca2406d1d">

<img width="475" alt="image" src="https://github.com/rancher/elemental/assets/112463911/e389d91f-dfd6-4d9f-8bd5-3fb9a7d622a0">

Please tell me, how I can solve this issue. k3s services should work.

**Environment:**

- Elemental release version (use `cat /etc/os-release`):5.3
<img width="460" alt="image" src="https://github.com/rancher/elemental/assets/112463911/aaa7d44d-6c82-4699-94c5-e9151e2b6eae">

- Rancher version:v2.7.3
- Kubernetes version (use `kubectl version`):v2.7.3
- Cloud provider or hardware configuration:Vmware

**Comment by kkaempf** [comment]
Elemental is not for installing Rancher itself, but for creating cluster nodes under control of Rancher.

You need to start with a Rancher installation as the "management cluster" and go from there as described in the [documentation](http://elemental.docs.rancher.com/quickstart-ui)

**Comment by divyashukla25** [comment]
Hi @kkaempf Yes, I've a rancher server where I've performed the steps and created the endpoint. And also, again created a new system from the ISO. But it is still not working.

Elemental registration is getting failed and k3s not getting installed.

Error
<img width="536" alt="image" src="https://github.com/rancher/elemental/assets/112463911/606b0712-e373-49d1-ae6f-bb3535ce5585">

<img width="524" alt="image" src="https://github.com/rancher/elemental/assets/112463911/2d30ac9a-2a6a-4e6b-87e4-588db518aeea">

Please help, I need this on urgent basis.

**Comment by divyashukla25** [comment]
Hi, Please provide the update. Thanks

**Comment by agracey** [comment]
Hi @divyashukla25, thank you for your interest in the Elemental project but this is not a paid support channel so there should not be any expectation of response time. There are various holidays around the world this week meaning that many contributors are enjoying vacations.

The error you've shown tells you the issue: you didn't specify the target device to install onto. Check your MachineRegistration again and compare against the example in the docs.

**Comment by divyashukla25** [comment]
@agracey Sure.

Yes I know the error. Actually, I had mentioned the target device in registration.yaml file and even after the ISO boots it is showing the mentioned target device on my machine as you can see in the above attached screenshot.

<img width="385" alt="image" src="https://github.com/rancher/elemental/assets/112463911/1a38d556-512d-4c29-bad0-6735e998acff">


But, still I'm getting the target device not found error. Could you please help me in this issue? It would be great.

**Comment by agracey** [comment]
What devices _are_ show under `/dev/`?

**Comment by divyashukla25** [comment]
@agracey @kkaempf Hey, for both questions, yes it is showing sda only. I have already attached the screenshot above. Please have a look.

**Comment by kkaempf** [comment]
Please attach
- the _complete_ `MachineRegistration` yaml (via Rancher UI)
- `/run/initramfs/live/livcecd-cloud-config.yaml` (from the installation system)

**Comment by divyashukla25** [comment]
@kkaempf @agracey Hi, I have solved this problem. This is because the cluster is getting crash due to the resource. After deploying on another machine, it's started working.

 Thank you so much for your support.
