### ISSUE TITLE
Installation on Raspberry runs into a loop

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental#881]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Performing an installation according to the current documentation does not reboot but runs into a loop, restarting the installation.

**What did you expect to happen:**

Reboot at end of installation

Logs show

```
Jun 24 11:07:27 rancher-1826 elemental-register[1567]: DEBU[2023-06-24T11:07:27Z] Unmounting partition COS_GRUB
Jun 24 11:07:27 rancher-1826 elemental-register[1567]: Error: 1 error occurred:
Jun 24 11:07:27 rancher-1826 elemental-register[1567]:         * open /sys/firmware/efi/efivars/Boot0000-8be4df61-93ca-11d2-aa0d-00e098032b8c: read-only file system
Jun 24 11:07:27 rancher-1826 elemental-register[1450]: F0624 11:07:27.547204    1450 log.go:86] elemental installation failed: failed to install elemental: exit status 1
Jun 24 11:07:27 rancher-1826 systemd[1]: elemental-register.service: Main process exited, code=exited, status=255/EXCEPTION
Jun 24 11:07:27 rancher-1826 systemd[1]: elemental-register.service: Failed with result 'exit-code'.
Jun 24 11:07:27 rancher-1826 systemd[1]: Failed to start Elemental Register.
Jun 24 11:07:32 rancher-1826 systemd[1]: elemental-register.service: Scheduled restart job, restart counter is at 1.
Jun 24 11:07:32 rancher-1826 systemd[1]: Stopped Elemental Register.
Jun 24 11:07:32 rancher-1826 systemd[1]: Starting Elemental Register...
Jun 24 11:07:32 rancher-1826 elemental-register[1728]: I0624 11:07:32.682045    1728 log.go:38] Debug logs enabled
Jun 24 11:07:32 rancher-1826 elemental-register[1728]: I0624 11:07:32.682237    1728 log.go:42] Register version 1.2.5, commit 4f3b2c59, commit date 20230620
```

The error about efivars (to be expected, RPi only simulates EFI) happened before but was silently ignored. Now it re-triggers the installation process.

**Comment by kkaempf** [comment]
This happens only if
```
elemental:
  install:
     disable-boot-entry: false
```

setting `disable-boot-entry: true` make the installation succeed.

**Comment by davidcassany** [comment]
> 
> The error about efivars (to be expected, RPi only simulates EFI) happened before but was silently ignored. Now it re-triggers the installation process.

Indeed, the efi vars error might be specific to RPi, however the re-install loop not. The reinstall issue should be relatively easy to reproduce on x86, I guess the _problem_ (I still doubt if this is an issue or a feature) is that the registration runs on a service that simply restarts on failure. The service is defined here https://github.com/rancher/elemental/blob/692220f01bab24b4fd85abbcb468cd07ec6bec97/framework/files/usr/lib/systemd/system/elemental-register.service#L10-L13

I wonder if there should be count for retries or not. I also wonder if there is a chance to update the cloud-config registration data between retries, I mean if the registration process re-downloads the cloud-config data on every attempt to register, if so this is valuable as this could be a way to fix a failing installation remotely.

**Comment by kkaempf** [comment]
> I wonder if there should be count for retries or not. I also wonder if there is a chance to update the cloud-config registration data between retries, I mean if the registration process re-downloads the cloud-config data on every attempt to register, if so this is valuable as this could be a way to fix a failing installation remotely.

Actually, that (editing the `MachineRegistration`) was how I fixed my installation.

**Comment by kkaempf** [comment]
> Indeed, the efi vars error might be specific to RPi, however the re-install loop not. The reinstall issue should be relatively easy to reproduce on x86, I guess the _problem_ (I still doubt if this is an issue or a feature) is that the registration runs on a service that simply restarts on failure.

This error _might_ happen on any `ARM` system - not sure if any of them has a proper BIOS + eeprom to store efivars 🤷🏻

**Comment by davidcassany** [comment]
> > I wonder if there should be count for retries or not. I also wonder if there is a chance to update the cloud-config registration data between retries, I mean if the registration process re-downloads the cloud-config data on every attempt to register, if so this is valuable as this could be a way to fix a failing installation remotely.
> 
> Actually, that (editing the `MachineRegistration`) was how I fixed my installation.

Nice! Then in that case I'd say that the reinstallation loop was not really an issue. I'd say the real thing here is providing better feedback so there is a better and comprehensive feedback to actually understand the installation loop from a customer's PoV.

In any case I believe the core of this issue is figuring out a smooth behavior for `ARM`. I'd say that on `ARM` we should not relay on efivars at all, should be the other way round, not try to write any variable unless it is explicitly requested. More over, we should double check ARM support of the library we use to write efivars.

**Comment by kkaempf** [comment]
> I'd say the real thing here is providing better feedback so there is a better and comprehensive feedback to actually understand the installation loop from a customer's PoV.

:+1:

>  I'd say that on `ARM` we should not relay on efivars at all, should be the other way round, not try to write any variable unless it is explicitly requested.

💯

**Comment by davidcassany** [comment]
Splitting this card in two different issues:

- [ ] Providing installation progress/logs for rancher/elemental-operator#214
- [ ] Installation retries on failure logic configurable in MachineRegistration resource, related and eventually part of rancher/elemental-operator#471

**Comment by kkaempf** [comment]
Hyper-V also [doesn't support efivars](https://github.com/rancher/elemental-toolkit/issues/1803)
