### ISSUE TITLE
Test OS2 with bonding LAN

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental#90]
Asked by @agracey 

Maybe we will have to wiat for this: https://github.com/rancher/elemental-toolkit/issues/1255.

**Comment by ldevulder** [comment]
First test on a VM with 4 NICs connected to the same LAN:
![Screenshot from 2022-04-13 16-04-16](https://user-images.githubusercontent.com/25102165/163198449-82044b75-6749-428d-8767-4beb0cfe9988.png)

Installation was done automatically after configuring the node in my Rancher lab. By default each NIC are configured to use DHCP, so basic configuration is working well.
The default route is configured on `eth0`, as expected:
```
ros-node-6496:~ # ip route
default via 192.168.4.1 dev eth0 proto dhcp 
192.168.4.0/24 dev eth0 proto kernel scope link src 192.168.4.37 
192.168.4.0/24 dev eth1 proto kernel scope link src 192.168.4.36 
192.168.4.0/24 dev eth2 proto kernel scope link src 192.168.4.35 
192.168.4.0/24 dev eth3 proto kernel scope link src 192.168.4.34
```
But in configuration files we can see that only `eth0` is configured:
```
ros-node-6496:/etc/sysconfig/network # ls -l
total 76
-rw-r--r-- 1 root root  9691 Apr 13 10:38 config
-rw-r--r-- 1 root root 14770 Apr 13 10:38 dhcp
drwxr-xr-x 2 root root  4096 Apr 13 10:38 if-down.d
drwxr-xr-x 2 root root  4096 Apr 13 10:38 if-up.d
-rw------- 1 root root    36 Apr 13 14:03 ifcfg-eth0
-rw------- 1 root root   147 Apr 13 10:38 ifcfg-lo
-rw-r--r-- 1 root root 21738 Apr 13 10:38 ifcfg.template
drwx------ 2 root root  4096 Apr 13 10:38 providers
drwxr-xr-x 2 root root  4096 Apr 13 10:38 scripts
```
So clearly DHCP by default for all network interfaces.

In current os2 version wicked is used for network configuration, I don't know if this will still be the case in the released version.

AFAIK, cloud-config doesn't support wicked byt default, so some kind of scripts might be needed to achieve an automated bonded configuration.

**Comment by ldevulder** [comment]
Maybe this can be done if NetworkManager is used instead of wicked?

**Comment by kkaempf** [comment]
Closing for now because
- ElementalTeal 5.2 supports SLE wicked, with all its features
- ElementalTeal 5.3 _might_ switch to NetworkManager, with all its features

=> non working bonding would be a SLE bug, not an Elemental bug
