### ISSUE TITLE
e2e: Move test plans to QASE

### ISSUE THREAD

**Issue by juadk** [rancher/elemental#919]
We finally got licenses for the QASE tool, so we can think about moving our test plans there.
https://qase.io/

- [x] Define and document the process we will follow during a test release
- [x] Enable QASE in our release test (https://github.com/rancher/elemental/pull/932)
- [ ] ~Enable QASE for daily CI?~
- [x] Update test plan, make sure we have all items etc
- [x] Add support for CLI (Golang/Ginkgo) tests (see #936)
- [ ] Add Airgap test: in progress to [add the test in CI](https://github.com/rancher/elemental/pull/1184) and the workflows are also being [refactored](https://github.com/rancher/elemental/issues/1187)

**Comment by ldevulder** [comment]
Can be closed, the Airgap stuffs will be done in a dedicated PR.
