### ISSUE TITLE
DNS resolution fails in custom ISO built with buildah, preventing node registration

### ISSUE THREAD

**Issue by tserong** [rancher/elemental#935]
**What steps did you take and what happened:**

I build a custom ISO following the instructions at https://elemental.docs.rancher.com/customizing/#create-a-custom-bootable-installation-media, then booted it and discovered that DNS resolution was failing, meaning the node couldn't hit the registration endpoint:

```
# journalctl -f -u elemental-register
[...] Connect to https://192.168.121.198.sslip.io/elemental/registration/zfv5tmxdtgmc8mbhh95l6bwrhjtbnhl8qlqks24mzrgsb94rs5tt58
[...] Using TPM Auth with Hash d6e6afea69a6178691269c933f241a9641ac4e76b426d16db6d5e472bf139e02 to dial wss://192.168.121.198.sslip.io/elemental/registration/zfv5tmxdtgmc8mbhh95l6bwrhjtbnhl8qlqks24mzrgsb94rs5tt58
[...] failed to register machine inventory: dial tcp: lookup 192.168.121.198.sslip.io on [::1]:53: read udp [::1]:39458->[::1]:53: read: connection refused
```

Here's my Dockerfile. The only change I've made is to mess with `/etc/os-release` a bit:

```Dockerfile
FROM registry.opensuse.org/isv/rancher/elemental/stable/teal53/15.4/rancher/elemental-teal/5.3:latest as os

ARG IMAGE_REPO=norepo
ARG IMAGE_TAG=latest
RUN echo "IMAGE_REPO=${IMAGE_REPO}"          > /etc/os-release && \
    echo "IMAGE_TAG=${IMAGE_TAG}"           >> /etc/os-release && \
    echo "IMAGE=${IMAGE_REPO}:${IMAGE_TAG}" >> /etc/os-release

FROM registry.opensuse.org/isv/rancher/elemental/stable/teal53/15.4/rancher/elemental-builder-image/5.3:latest AS builder

ARG TARGETARCH
WORKDIR /iso
COPY --from=os / rootfs

RUN --mount=type=bind,source=./,target=/output,rw \
      elemental build-iso \
        dir:rootfs \
        --bootloader-in-rootfs \
        --squash-no-compression \
        -o /output -n "elemental-teal-with-broken-dns-wtf-${TARGETARCH}"

```

**What did you expect to happen:**

I expected DNS resolution to work properly.

**Anything else you would like to add:**

Earlier in the boot process we can see the following from NetworkManager:

```
[...] NetworkManager[1270]: ATTENTION: /etc/resolv.conf is not a link to /var/run/netconfig/resolv.conf
[...] NetworkManager[1270]: call "netconfig update -f" to adjust /etc/resolv.conf
[...] NetworkManager[1085]: <warn>  [1690514579.4554] dns-mgr: could not commit DNS changes: Error calling netconfig: exited with status 20
```

My custom image includes an empty `/etc/resolv.conf` file, whereas the original elemental teal image does not (hence no problem with a non-custom image). It's the existence of that file that prevents NetworkManager from setting up DNS properly. Logging into the node and running `netconfig update -f` does fix it, but obviously we don't want to have to do that.

I did some digging and found https://github.com/containers/buildah/issues/4242, so it looks like podman/buildah is putting that empty `/etc/resolv.conf` in the os image, which is the source of the problem.

I can think of a few solutions here:

1. Figure out how to fix podman/buildah so it doesn't do that thing.
2. Change https://elemental.docs.rancher.com/customizing/#create-a-custom-bootable-installation-media so it builds using docker rather than buildah (apparently docker doesn't have the problem with /etc/resolv.conf). I haven't tried this yet, so I'm not sure of the exact docker commands to use.
3. See if there's an option for NetworkManager and/or netconfig to make it do `netconfig update -f` by default (it seems reasonably safe to me to make the boot ISO opinionated about this)
4. Continue to document buildah usage, but work around the problem:

```diff
 ARG TARGETARCH
 WORKDIR /iso
 COPY --from=os / rootfs
+RUN rm rootfs/etc/resolv.conf
 
 RUN --mount=type=bind,source=./,target=/output,rw \
       elemental build-iso \
```

**Environment:**

- Elemental release version (use `cat /etc/os-release`): Sorry, my custom build overwrote `/etc/os-release` ;-)
- Rancher version: v2.7.5
- Kubernetes version (use `kubectl version`): v1.26.6+k3s1
- Cloud provider or hardware configuration: KVM virtual machines via virt-manager

**Comment by kkaempf** [comment]
Looking at containers/buildah#4242, I don't think buildah will fix anything anytime soon 😞 

Added the workaround to docs 🤞🏻 

Thanks Tim !
