### ISSUE TITLE
Parametrize Micro version in CI

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental#940]
**Describe the solution you'd like:**
[A clear and concise description of what you want to happen.]
I'd like to be capable to update the SLE Micro version without having to hunt URL references in the CI (see #939). Ideally we should only change the SLE Micro version value in a single place.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
There is a new OS version twice a year, so this is likely to happen relatively often.

**Environment:**

- Elemental release version (use `cat /etc/os-release`):
- Rancher version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:

**Comment by kkaempf** [comment]
no longer relevant
