### ISSUE TITLE
Update ISO urls in CI

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental#944]
I noted there are still missing some updates within the CI... In fact some ISO urls need to be addressed.

I can be checked by `$ grep -rin iso_to_test .github`. Note that URLS like:

```
https://download.opensuse.org/repositories/isv:/Rancher:/Elemental:/Staging:/Teal53/media/iso/elemental-teal.x86_64.iso
```

should be converted to

```
https://download.opensuse.org/repositories/isv:/Rancher:/Elemental:/Staging/containers/iso/elemental-teal.x86_64.iso
```

**Comment by kkaempf** [comment]
@ldevulder @juadk 👀

**Comment by ldevulder** [comment]
@kkaempf already on it.
