### ISSUE TITLE
Behaviour of https://github.com/rancher/elemental/blob/main/framework/files/usr/sbin/suc-upgrade

### ISSUE THREAD

**Issue by sudheermygapula** [rancher/elemental#946]
**What steps did you take and what happened:**
If the versions are same using force makes upgrade is recurrsive  . ( I feel according to curren logic it will be recurrsive even the versions are not same as force by pass all conditions ) .

**What did you expect to happen:**

**Anything else you would like to add:**
I feel that  **isEqualVersion**  should out of force scope to avoid recurrsive upgrade.
I observed in my test environment the system keeps restarting again and again and new upgrade jobs are get created.

**Environment:**

- Elemental release version (use `cat /etc/os-release`):
- Rancher version: 2.7.3
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:

**Comment by sudheermygapula** [comment]
This is custom elemental image we created and updates are done with system upgrade controller via plan .

**Comment by kkaempf** [comment]
Sorry, @sudheermygapula, not sure I can follow your bug report.

Can you provide a simple reproducer of your problem ?

Also can you please check if upgrading to [Staging](http://elemental.docs.rancher.com/quickstart-cli#non-stable-installations) fixes your problem ?

**Comment by sudheermygapula** [comment]
@kkaempf  sorry for late reply .

- we extended the elemental images and using using latest https://github.com/rancher/elemental/blob/main/framework/files/usr/sbin/suc-upgrade for upgrade ( As there is fix for https://github.com/rancher/elemental/issues/901 ) .  
- And we using the force flag to upgrade .

- i see that jobs will run twice , the first time it upgrades and triggers the reboot ,  Once it rebbots the same job runs again to confirm the it is upgraded ,However some time i have observed ( Expeceally if you use same version again to upgrade with force ) the jobs are performed in recurrsive manner ( The system reboots again and again for every job ) .

-  I believe the second job also runs the same script https://github.com/rancher/elemental/blob/main/framework/files/usr/sbin/suc-upgrade and in case of force flag applied , how it check if the upgrade is successfull or not  as force by passes the isEqualVersion check ? 

Note: The version is customized by us for airgap rancher and elemental operator running in same node . 

```
 if [ "$FORCE" != "true" ]; then
        if isEqualVersion; then
            echo "Upgrade already done with release:"
            cat ${HOST_DIR}${RELEASE_FILE}

            config
            exit 0
        fi
```

Please do let me know if am missing anything and i could repeat my tests.

**Comment by anmazzotti** [comment]
Same as #1255

**Comment by kkaempf** [comment]
Duplicate
