### ISSUE TITLE
e2e: add automated tests for reset option

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental#952]
See https://elemental.docs.rancher.com/next/reset/.

**Comment by juadk** [comment]
Check https://github.com/rancher/elemental/issues/973 to see what manual tests were done.

**Comment by juadk** [comment]
Done for the UI in https://github.com/rancher/elemental/pull/995
I would like to add the same test in the CLI tests but by deleting only one node instead of the cluster.

**Comment by juadk** [comment]
In the CI, the new automated test works perfectly with:
- K3S / RKE2 + Rancher stable (2.7.6)
- K3S + Rancher head (rancher:v2.7-head)

But it **fails** with RKE2 + rancher:v2.7-head
https://github.com/rancher/elemental/actions/workflows/ui-rke2-rancher_latest.yaml
