### ISSUE TITLE
Inventory of Machines does not reflect correct inventory state [BUG]

### ISSUE THREAD

**Issue by mak3r** [rancher/elemental#957]
## SURE-6785

**Rancher Server Setup**
- Rancher version: v2.7.5
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s
- Proxy/Cert Details: letsEncrypt + cert manager

**Information about the Cluster**
- Kubernetes version: v1.25.12+k3s1
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**

Using Elemental/OS Management, a machine is brought into inventory and it correctly displays as "unavailable" and the Cluster column is empty (correctly). Then when it is bound to a cluster, the machine inventory shows which cluster it is bound to however the status still shows as "unavailable". 

**To Reproduce**

1. Create a registration endpoint 
2. Create an ISO from the registration endpoint.
3. Install Elemental on a machine

    * In OS Management -> Inventory of Machines, note that the machine inventory has no cluster binding and is "unavailable"

4. Create the cluster.yaml and machine-inventory-selector.yaml
    
    * In OS Management -> Inventory of Machines, note that the machine inventory now has a cluster binding and is still "unavailable"

**Result**

**Expected Result**

When the inventory is assigned to a cluster the state should be "active"

**Screenshots**

![image](https://github.com/rancher/rancher/assets/6570708/fe84d99a-872a-4dde-9a96-55d0a4932d49)

![image](https://github.com/rancher/rancher/assets/6570708/84b1d233-5a76-47ab-9be1-cc5a54d51f8a)

![image](https://github.com/rancher/rancher/assets/6570708/c7f9744b-ac10-4500-8c72-e73dbfe2cb89)

**Additional context**

**Comment by kkaempf** [comment]
Can you attach the complete `MachineInventory` for this system please ?

**Comment by kkaempf** [comment]
~~~
{{apiVersion: elemental.cattle.io/v1beta1
kind: MachineInventory
metadata:
  annotations:
    elemental.cattle.io/auth: emulated-tpm
    elemental.cattle.io/registration-ip: 192.168.8.173
  creationTimestamp: '2023-08-14T18:16:42Z'
  generation: 1
  labels:
    location: us
    machineUUID: 30303030-3030-3030-3933-316364353165
    manufacturer: raspberrypi
    productName: rpi
    serialNumber: 00000000931cd51e
  managedFields:
    - apiVersion: elemental.cattle.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:conditions: {}
          f:plan:
            .: {}
            f:secretRef: {}
      manager: elemental-operator
      operation: Update
      subresource: status
      time: '2023-08-14T18:19:05Z'
    - apiVersion: elemental.cattle.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:elemental.cattle.io/auth: {}
            f:elemental.cattle.io/registration-ip: {}
          f:labels:
            .: {}
            f:location: {}
            f:machineUUID: {}
            f:manufacturer: {}
            f:productName: {}
            f:serialNumber: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"0db25ea9-e9e4-4d54-a765-b2e429b91c0e"}: {}
        f:spec:
          .: {}
          f:tpmHash: {}
      manager: elemental-operator
      operation: Update
      time: '2023-08-17T17:52:14Z'
  name: m-7f8b6f27-fe9d-4e00-ad35-b4efb595fc5e
  namespace: fleet-default
  ownerReferences:
    - apiVersion: elemental.cattle.io/v1beta1
      controller: true
      kind: MachineInventorySelector
      name: jfk-machine-selector-g7dwb
      uid: 0db25ea9-e9e4-4d54-a765-b2e429b91c0e
  resourceVersion: '1390783'
  uid: f1757bd2-bd63-418e-bcc7-455277691742
spec:
  tpmHash: a2e5b231dac4e90151454e2ebc76a6b118f7d1b826b810d22868b2d09b38b7f7
status:
  conditions:
    - lastTransitionTime: '2023-08-14T18:16:42Z'
      message: waiting for plan to be applied
      reason: WaitingForPlan
      status: 'False'
      type: Ready
    - lastTransitionTime: '2023-08-14T18:19:05Z'
      message: Successfully adopted
      reason: SuccessfullyAdopted
      status: 'True'
      type: AdoptionReady
  plan:
    secretRef:
      name: m-7f8b6f27-fe9d-4e00-ad35-b4efb595fc5e
      namespace: fleet-default}}
~~~

**Comment by kkaempf** [comment]
Unsupported scenario (ARM, Raspberry, and emulated TPM), moving out of rancher/rancher.

**Comment by kkaempf** [comment]
Hmm, this looks as if things are ok within the `MachineInventory` 🤔 
~~~
status:
  conditions:
    - lastTransitionTime: '2023-08-14T18:16:42Z'
      message: waiting for plan to be applied
      reason: WaitingForPlan
      status: 'False'
      type: Ready
    - lastTransitionTime: '2023-08-14T18:19:05Z'
      message: Successfully adopted
      reason: SuccessfullyAdopted
      status: 'True'
      type: AdoptionReady
~~~

@fgiudici - is this set by `elemental-operator` or rancher provisioning ?

**Comment by fgiudici** [comment]
> @fgiudici - is this set by `elemental-operator` or rancher provisioning ?

This is set by the `elemental-operator`.
It may be related to the recent changed in the staging version of the operator 🤔  ... will check.

**Comment by kkaempf** [comment]
I cannot reproduce this problem with Rancher 2.7.5. elemental-operator 1.3.1, OBS `Staging` and a Raspberry Pi.

Edit: Based on "normal" Rancher UI views. Haven't tested with Elemental UI yet.

**Comment by kkaempf** [comment]
Cannot reproduce even within Elemental UI extension 🤷🏻

**Comment by fgiudici** [comment]
Hey @mak3r 👋🏼 
Which Elemental Operator version have you used? Do you have the version or do you remember the source?
Do you have by chance still around the MachineRegistration you used to build the ISO? Mainly interested in the TPM seed if you set one there, but the full MachineRegistration may be useful.
Last question: did you just build one ISO (or boot image) and booted just one host one time with it? Or did you made some "tests" or other booting trials?

**Comment by mak3r** [comment]
@fgiudici 
I did not set the `emulated-tpm-seed` on this one. I have only booted the one so far but I can boot more. I just booted the one because it demonstrated the same error the prospect is seeing. Let me know if there's something else I should test.

### Additional Info

elemental extension (Rancher UI):  1.2.0
elemental operator: registry.opensuse.org/isv/rancher/elemental/stable/teal53/15.4/rancher/elemental-operator/5.3:1.2.5

`registration-rpi.yaml`:
```
apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: rpi-demo
  namespace: fleet-default
spec:
  config:
    cloud-config:
      users:
        - name: mak3r
          sudo: ALL=(ALL) NOPASSWD:ALL
          groups: mak3r, users, admin
        - name: root
          passwd: root
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHVZtKeG7C1CmMYh07Rgm6JkbIZ90DpjuKip1Aexhm5qz0O/E6w6tB0FTd2rCWO+FtOYpFMT2ao9dqeMvBTkTRGGQZ1nG+QaWYFGExS5lGUm+n9GXJU34LK6fcVx7xgZ3rw7RKWYXPmS/hIujSKRL0Qj9RMuVHIVMzDUzUL9zYOEHyLtY5OkHgzCp8wcVyx7CdBY/G3gru42MQmLoN3yJV1mti7YS9IjY99i55M5FeUe4/NcukHoYkMuyHtHugHlXeficAhpUrsouKRnMaXDFCK4sGmZucF8zpyXpG8qcGE+S6b5e/NderR+HlWTbpURiFJRthwCr2pAR90pvanuUN markabrams@marks-mbp.lan
      write_files:
      - content: |
          # /etc/udev/rules.d/11-ftdi.rules

          # FT232H
          SUBSYSTEM=="usb", ATTR{idVendor}=="0403", ATTR{idProduct}=="6014", GROUP="plugdev", MODE="0664"
        path: /etc/udev/rules.d/11-ftdi.rules
        permissions: "0644"
      - encoding: b64
        content: W2Nvbm5lY3Rpb25dCmlkPWdsaW5ldAp0eXBlPXdpZmkKaW50ZXJmYWNlLW5hbWU9d2xhbjAKcGVybWlzc2lvbnM9CnRpbWVzdGFtcD0xNjcxNTQ5NjQxCgpbd2lmaV0KbWFjLWFkZHJlc3MtYmxhY2tsaXN0PQptb2RlPWluZnJhc3RydWN0dXJlCnNzaWQ9R0wtQVI3NTBTLWFmOC01RwoKW3dpZmktc2VjdXJpdHldCmtleS1tZ210PXdwYS1wc2sKcHNrPWJvb3RsZWctYmFsc2EtZGljdGF0ZQoKW2lwdjRdCmRucy1zZWFyY2g9Cm1ldGhvZD1hdXRvCgpbaXB2Nl0KYWRkci1nZW4tbW9kZT1zdGFibGUtcHJpdmFjeQpkbnMtc2VhcmNoPQptZXRob2Q9YXV0bw==
        path: /etc/NetworkManager/system-connections/glinet.connection
      - encoding: b64
        content: W2Nvbm5lY3Rpb25dCmlkPW1vYmlsZVdBUAp0eXBlPXdpZmkKaW50ZXJmYWNlLW5hbWU9d2xhbjAKcGVybWlzc2lvbnM9CnRpbWVzdGFtcD0xNjcxNTQ5NjQxCgpbd2lmaV0KbWFjLWFkZHJlc3MtYmxhY2tsaXN0PQptb2RlPWluZnJhc3RydWN0dXJlCnNzaWQ9TWFrM3JzTW9iaWxlCgpbd2lmaS1zZWN1cml0eV0Ka2V5LW1nbXQ9d3BhLXBzawpwc2s9T0pkQS01Mno2LVZvcnAtZEJ5VgoKW2lwdjRdCmRucy1zZWFyY2g9Cm1ldGhvZD1hdXRvCgpbaXB2Nl0KYWRkci1nZW4tbW9kZT1zdGFibGUtcHJpdmFjeQpkbnMtc2VhcmNoPQptZXRob2Q9YXV0bw==
        path: /etc/NetworkManager/system-connections/mobileWAP.connection
    elemental:
      install:
        poweroff: true
        device: /dev/mmcblk0
        debug: true
        disable-boot-entry: true
      registration:
        emulate-tpm: true
  # machineName: "${System Information/UUID}"
  machineInventoryLabels:
    location: "us"
    manufacturer: "${System Information/Manufacturer}"
    productName: "${System Information/Product Name}"
    serialNumber: "${System Information/Serial Number}"
    machineUUID: "${System Information/UUID}"
```

**Comment by fgiudici** [comment]
Hey @mak3r 👋🏼 , thanks for the info!
Spent some time on this, so let me share some notes:
1 - I was not able to reproduce. I went with a fresh Rancher 7.5 installed on a k3s cluster. Went with the provided Registration, TPM emulation is fixed to TPM seed 1 by default and this is fine for just one node. I have tried anyway to mess up registering multiple hosts with the same TPM seed but that would not lead to the issue here.
2 - the plan status in the shared MachineInventory doesn't report the `checksum` : the checksum is updated by the elemental controller once the rancher system agent (which should apply the plan) updates either the "applied-checksum" or the "failed-checksum" inside the referenced plan secret. So, from the elemental controller PoV, the plan is still being applied as we don't get the ack (or nack) from the rancher-system-agent.
Still, obviously the node was correctly provisioned with the cluster as it appeared in the Rancher console.
3 - comparing the machine inventory with the cluster screenshot, the node has changed the IP after the reboot (192.168.8.173 first and 192.168.8.123 later). Not sure if this is due to the setup which changed slightly or if it could be even be related in any way to the failure (e.g., impacting the system-agent updating the plan secret), but at least lets just note here.

At this point I would resort getting the logs of the rancher-system-agent from the host tracked by the machine inventory (192.168.8.123?):
Journalctl -u rancher-system-agent.service
It could also be interesting checking inside the plan secret to see what is inside the last plan applied (or tried to apply): secret  m-7f8b6f27-fe9d-4e00-ad35-b4efb595fc5e` in the `fleet-default` namespace. I expect it to be "just" the plan to deploy the cluster, but it may be worth to double check.
Would it be possible to share those data?
Be aware that there could be sensitive info there related to your cluster (maybe encoded as base64 but still...): so it could be perfectly fine sharing via a private channel 😄

**Comment by mak3r** [comment]
Unfortunately, I cleaned up this cluster and the Rancher instance it was bound to. I have pretty consistently been able to recreate this in both the RaspberryPi and with VMs on ESXi though. 

One thing of interest is item #3 on your list. This device has definitely been connected to this network before and typically holds the .123 address. This may or may not explain the same issue on VMWare as I believe each VM should get a new MAC address. 

I know that this particular network device caches dhcp-MAC address combos so maybe it is related. I am going to see if I can reproduce on the same network and then again on a different (new to the device) network. We can also check the secret if that's still relevant after the network trial.

**Comment by kkaempf** [comment]
Not reproducible
