### ISSUE TITLE
Fix broken CI

### ISSUE THREAD

**Issue by juadk** [rancher/elemental#963]
The elemental CI is almost entirely red so let's fix it before starting new topics.

**Comment by juadk** [comment]
Issue from my side:
https://github.com/rancher/elemental/actions/runs/5924363625/job/16061767843
Tests which use `rancher-head` fail, it looks like the status never switches to `Active`, it stays to `Updating`

**Comment by juadk** [comment]
After debugging the tests using the rancher head version, the issue is with the CAPI controller introduction.
It comes with Rancher 2.7.7, a JIRA ticket has been opened and I think we will have the Rancher head CI red for a while.

**Comment by juadk** [comment]
UI upgrade fixed by https://github.com/rancher/elemental/commit/273a8f0cd6742cc56f0a2e2a14cdc4082e7db4b1
Rancher head tests fixed by https://github.com/rancher/elemental-operator/pull/500

**Comment by ldevulder** [comment]
CLI tests fixed with PR #972.
