### ISSUE TITLE
/usr/libexec missing on aarch64

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental#98]
After [copying firmware and bootloader files](#97) on aarch64, cOS comes up nicely but then fails to mount `/usr/libexec`, resulting in a locked root account and no way out.

(Not sure if this is a ros-installer or a cOS-toolkit issue 🤷🏻 )

**Comment by mudler** [comment]
This looks like an issue while creating the base image. [`os2` **requires** the `/usr/libexec` path in the container image used to boot](https://github.com/rancher-sandbox/os2/blob/master/framework/files/system/oem/01_ros-rootfs.yaml#L39).

**Comment by mudler** [comment]
aarch64 support depends on https://github.com/rancher/elemental-toolkit/issues/1258 - otherwise can be achieved using the `arm_image_builder.sh` script in the toolkit repository.

**Comment by kkaempf** [comment]
This is considered fixed.
