### ISSUE TITLE
Supporters training template

### ISSUE THREAD

**Issue by mbologna** [rancher/elemental#982]
Fill out the support training template 2.8 for Elemental

**Comment by mbologna** [comment]
https://confluence.suse.com/display/CECO/Support+Training

cc: @davidstauffer @kkaempf

**Comment by kkaempf** [comment]
✅

**Comment by davidstauffer** [comment]
✅ Added the masterclass as a video from David, Klaus, and Francesco.

**Comment by kkaempf** [comment]
reviewed, accepted
