### ISSUE TITLE
e2e - Use registry.suse.com instead of OBS stable

### ISSUE THREAD

**Issue by juadk** [rancher/elemental#998]
OBS stable will be deprecated soon so we agreed to use `registry.suse.com` as stable in our tests.

**Comment by kkaempf** [comment]
We should probably remove OBS Stable soon 🤔 /cc @davidcassany

**Comment by davidcassany** [comment]
> We should probably remove OBS Stable soon 🤔 /cc @davidcassany

Yes agreed, as soon as we are not using it for anything I vote to completely remove it. First UI version has the ISO URL hardcoded there pointing to Stable though, something discuss with @aalves08 before actually removing it, an equivalent ISO is also available in a suse.com domain. 
Anyway, first thing is stop using Stable internally.
